### ISSUE TITLE
Add database connection pool details to Process state

### ISSUE THREAD

**Issue by bensheldon** [bensheldon/good_job#1014]
It might be helpful to provide a snapshot of the database connection pool settings and usage to the Process state.

For the database used by GoodJob (e.g. take it off the `GoodJob::Process` connection):

- Size of the database connection pool
- Number of active connections being used right now

**Comment by dixpac** [comment]
@bensheldon  did I understand this correctly:

You want to this information inside`GoodJob::Process#current_state`

Something like this:

```ruby
    def self.ns_current_state
      {
        ...
        db_conection_pool_size: connection_pool.size,
        db_connection_pool_busy: connection_pool.connections.count(&:in_use?)
      }
    end
```

For the "Size of the database connection pool" do you want

- `connection_pool.size` - Total capacity of the connection pool
- `connection_pool.connections.size` - Total number of opened connections (idle or in_use)

**Comment by bensheldon** [comment]
@dixpac that looks perfect! 

One naming request: what do you think of "active" instead of "busy"?

**Comment by dixpac** [comment]
Awesome!
I'll submit PR then

Agree about the naming 🤘🏽
