### ISSUE TITLE
Replace webrick with a small/simple custom rack-compatible http server

### ISSUE THREAD

**Issue by bensheldon** [bensheldon/good_job#1017]
I would like to drop the runtime dependency on webrick. Webrick is only used for the [probe server functionality](https://github.com/bensheldon/good_job#cli-http-health-check-probes) which is intended to be a private interface.

I think webrick could be replaced with <100 lines of Ruby to implement a bare minimum http server to be used for the probe server, thus it would only need to implement simple GET and string paths, and not do other query-parsing/etc.

**Comment by dixpac** [comment]
Can I take this?

**Comment by bensheldon** [comment]
@dixpac yes please 🙏

**Comment by bensheldon** [comment]
And to calibrate the level of polish I'm expecting (low): I have previously fed this into GitHub Copilot and ChatGPT and the result seemed fine. There already is some integration testing, so maybe 1 or 2 more test cases in this pattern should be sufficient:

https://github.com/bensheldon/good_job/blob/3bc2f85e46b58254b4272c00e08a415967b05c9e/spec/lib/good_job/probe_server_spec.rb#L14-L30
