### ISSUE TITLE
Cron job by default runs on the web server even when "async" execution mode is not specified

### ISSUE THREAD

**Issue by yaseen-oakrev** [bensheldon/good_job#1026]
Cron jobs are by default running as soon as I start my web server.
Here are the relevant config variables:
`config.active_job.queue_adapter = :good_job

  config.good_job.enable_cron = true
  config.good_job.cron = {
    task_A: {
      cron: '*/20 * * * * *',
      class: 'ClassA',
      description: 'A task'
    }
  }`
  
  No good_job process is running. Also I see the task-relevant logs and the 'LISTEN' statements when I start my rails web server. I couldn't find any relevant documentation, thus this issue.

**Comment by yaseen-oakrev** [comment]
I'd want to know the desired config so that jobs (both normal tasks and cron jobs) are handled only by the good_job process spawned with `bundle exec good_job start`

**Comment by bensheldon** [comment]
Hi @yaseen-oakrev 👋🏻 Happy to help. 

What environment are you seeing this in? By default, GoodJob runs `:async` in Development, `:inline` in Test, and `:external` in Production environments.

If you don't want to run in `:async` in the Development environment you could set:

```
# config/environments/development.rb
config.good_job.execution_mode = :external
```

Alternatively, if you only want Cron in production, you could run:

```
config.good_job.enable_cron = Rails.env.production?
```

Let me know if that helps. If you already have that something like that configured and it's still not working, let me know (it's always possible there is a bug somewhere too).

**Comment by yaseen-oakrev** [comment]
Oh mb., this was in development. I'll switch to :external mode to test this. Thanks a lot for the prompt response.
