### ISSUE TITLE
3.17.0 breaks health check endpoints

### ISSUE THREAD

**Issue by aldent95** [bensheldon/good_job#1033]
I noticed my background worker pod for one of my websites was in a restart loop after a release today.

It looks like 3.17.0 has broken the health check endpoints that are listed in the docs to use for K8 clusters.

I can't get the exact error message, but in essence the K8s cluster couldn't reach either of the endpoints (/status/started or /status/connected) once deployed.

I've reverted back for now and everything is working again.
Happy to help debug if needed.

**Comment by bensheldon** [comment]
@aldent95 ah nuts! Thanks for opening the issue. v3.17.0 replaced Webrick with our own simple http server (#1030), and we must have missed something. I'm looking at it now.

**Comment by bensheldon** [comment]
I think I found the problem. A `return` was breaking the server loop when it should have just re-looped: https://github.com/bensheldon/good_job/pull/1034

I'm going to let CI run through, and barring anything unforeseen I'll cut a patch release.

**Comment by bensheldon** [comment]
@aldent95 I just released v3.17.1. I hope that fixes it! 😰 

https://github.com/bensheldon/good_job/releases/tag/v3.17.1

**Comment by aldent95** [comment]
@bensheldon Yep, looks to be working fine now, cheers!
