### ISSUE TITLE
NoMethodError in ProcessHeartbeat if ActiveRecord logger is nil

### ISSUE THREAD

**Issue by afn** [bensheldon/good_job#1036]
We have ActiveRecord logging disabled in our application (`config.active_record.logger = nil`), which results in a NoMethodError in GoodJob::Notifier::ProcessHeartBeat#refresh_process [here](https://github.com/bensheldon/good_job/blob/d26b94835b87d6b8514c4578dabcc498775aa9f3/lib/good_job/notifier/process_heartbeat.rb#L26-L28):

```ruby
            GoodJob::Process.logger.silence do
              @process&.refresh_if_stale(cleanup: true)
            end
```

The error is:
```
Notifier errored: NoMethodError: undefined method `silence' for nil:NilClass
```

I'll follow up with a pull request shortly.

**Comment by bensheldon** [comment]
Thank you @afn! The fix has been released: https://github.com/bensheldon/good_job/releases/tag/v3.17.2

**Comment by afn** [comment]
Awesome! Thanks for the quick turnaround :)
