### ISSUE TITLE
An idea for better .silence handling

### ISSUE THREAD

**Issue by alokhmutov** [bensheldon/good_job#1046]
Hi everyone! I noticed an issue with the upgrade related to #1036. Checking for nil logger is a good fix for cases where GoodJob is trying to call silence on a nil logger. However, there is another case that the nil check will not cover: if the logger does not implement the method at all. 

I was using a custom logger with an approach similar to that outlined in a [stackoverflow answer](https://stackoverflow.com/a/51227446) to skip cache hits from logging. I am not sure it is a good practice but in any case there is a simple solution in a more fool-proof check than checking for nil:

https://github.com/alokhmutov/good_job/commit/625bc6eb2f8e80341654f1787ceca312a654c88d

`if logger.respond_to? :silence`

Do you think this is worth considering?

Tagging @afn as the original author :)

**Comment by afn** [comment]
Makes sense to me.

**Comment by bensheldon** [comment]
Released: https://github.com/bensheldon/good_job/releases/tag/v3.17.4
