### ISSUE TITLE
Fix documentation to always include space in "Active Job", "Active Record", etc.

### ISSUE THREAD

**Issue by bensheldon** [bensheldon/good_job#1048]
Took me a decade to learn that the Rails libraries' names are two separate words, "Active Record" whereas the class names are "`ActiveRecord`"

**Comment by andyatkinson** [comment]
HI @bensheldon I used to write for "This Week in Rails", which was eventually folded into the official Ruby on Rails weblog. This was one of the first things that was taught to me, and that I taught to other new editors. 😁 

I will take a quick look on this one.

**Comment by bensheldon** [comment]
I think we did it! Thank you @andyatkinson 🙇🏻
