### ISSUE TITLE
[Feature Request?] Config Option to Inline Child-Jobs in Worker Processes

### ISSUE THREAD

**Issue by marvinscharle** [bensheldon/good_job#1052]
Hi @bensheldon! First of all – thank you for the great work. 

We're using GoodJob to schedule all our async/delayed background processes. However, we also have a set of very heavy jobs that currently spawn a lot of (>100k) child jobs. While heavy jobs are executed on a special queue, the child jobs are enqueued on another queue, thus delaying other time-critical jobs.

Since the child jobs and the regular (time-critical) jobs use the same ActiveJob classes as the regular jobs, my question is:

Can GoodJob be configured so that child jobs spawned by the workers will be executed automatically inline? We already tried it by using this in production.rb, however it does not seem to work:

```ruby
config.good_job.execution_mode = ENV['RUN_JOBS_INLINE'] ? :inline : :external
```

If there is already a way to configure it and I was too stupid to read the manual, I'd appreciate a hint how to do it.

Otherwise, I'd suggest this as a feature.

Cheers & thank you in advance!

**Comment by bdewater** [comment]
Sounds like this could be solved by [setting](https://api.rubyonrails.org/classes/ActiveJob/Core/ClassMethods.html#method-i-set) the queue for these child jobs instead of using the default time-critical one?

**Comment by bensheldon** [comment]
Thanks for opening this issue. I think it makes sense conceptually that GoodJob should allow this but it doesn't currently:

https://github.com/bensheldon/good_job/blob/3cff9eef26bfdc18ac94c70f3d25e5d8ac303e30/lib/good_job/configuration.rb#L92-L98


But why I think it makes sense is because "Execution Mode" is mainly a function of the Adapter at enqueue: when a job is enqueued, should it be simply put on the queue (`:external`), executed in a background thread in the current process (`:async`), or run in the foreground immediately (`:inline`). 

When running the CLI, I guess that all of those should hold true for jobs that are enqueued as part of executing other jobs. I imagine that even` :async` could imply process-fixation.

I guess the question I have is: would this imply a breaking change? The situation I'm imagining is that someone has global ENV set for like `:inline` in the web process _and_ they are also running a background GoodJob CLI process. That seems pretty rare though. 

In the meantime though, a workaround would be to manually assign the adapter:

```ruby
MyJob.queue_adapter = GoodJob::Adapter.new(execution_mode: :inline)
# or do it everywhere
config.active_job.queue_adapter = GoodJob::Adapter.new(execution_mode: :inline) if ENV['RUN_JOBS_INLINE']
```

**Comment by marvinscharle** [comment]
> Sounds like this could be solved by [setting](https://api.rubyonrails.org/classes/ActiveJob/Core/ClassMethods.html#method-i-set) the queue for these child jobs instead of using the default time-critical one?

Unfortunately, this does not work for us since most of the child jobs are enqueued during `after_save`/`after_save_commit` hooks.


> In the meantime though, a workaround would be to manually assign the adapter:

Thank you much! I'm gonna test this on our staging system and give you feedback.

> I guess the question I have is: would this imply a breaking change? The situation I'm imagining is that someone has global ENV set for like :inline in the web process and they are also running a background GoodJob CLI process. That seems pretty rare though.

For me, this behavior was not clear. I'd assume that the setting of `execution_mode` would overwrite any default set by GoodJob.

---

Yesterday we also stumbled upon another interesting behavior: We use Puma as webserver, depending on the evironment also in clustered mode. 

We discovered that GoodJob automatically runs a worker on all threads.

Is there a way to prevent GoodJob from executing any jobs on the web servers (jobs should only be run on the workers)? As a workaround, we set the ENV `GOOD_JOB_QUEUES` to the non-existing queue `none`, but this seems more like a "hacky" approach:

![SCR-20230829-d6b](https://github.com/bensheldon/good_job/assets/5916903/1c5f6456-3a99-4cb3-94f7-e44a31bc8e56)

Is there an official way to do this?

**Comment by bensheldon** [comment]
> Is there a way to prevent GoodJob from executing any jobs on the web servers (jobs should only be run on the workers)? 

GoodJob's default execution mode in the Development Environment is `:async` aka, execute jobs on the webserver. The production environment default is `:external`, which should not execute jobs on the webserver

Can you confirm you're seeing this in production, and the execution mode has not been configured to `:async`?

**Comment by marvinscharle** [comment]
Yes, I can confirm that this is happening in production. How can I support you to reproduce this?

**Comment by bensheldon** [comment]
Do you have production console access? If so, could you run `GoodJob.configuration.execution_mode` and tell me the output?

Also, do you have this in your `config/puma.rb`? 

```ruby
on_worker_boot do
  GoodJob.restart
end
```

Looking into it, I think this will unfortunately _start_ GoodJob's executor regardless of the execution mode. If that's what you have, the workaround would be:

```ruby
on_worker_boot do
  GoodJob.restart if GoodJob.configuration.execution_mode == :async
end
```

...but I should also make that work better if that is the problem.

**Comment by bensheldon** [comment]
Oops, didn't mean to close that 😰

**Comment by marvinscharle** [comment]
> Do you have production console access? If so, could you run `GoodJob.configuration.execution_mode` and tell me the output?

Yes, it returns `:external`
<img width="661" alt="grafik" src="https://github.com/bensheldon/good_job/assets/5916903/40f046e3-74b2-49db-9a51-394a76c3ea31">

---

`on_worker_boot` is also present in `puma.rb`. I'm gonna deploy the workaround to our staging environment to see if the processes are no longer started.

**Comment by marvinscharle** [comment]
After deployment of the workaround to the staging environment, I can confirm that the worker processes are no longer started via Puma.

**Comment by bensheldon** [comment]
@marvinscharle fhew, glad we could figure out a workaround. I'll take a look at the design for `GoodJob#restart` and think about how to make it less surprising.

**Comment by marvinscharle** [comment]
Thank you much!

**Comment by bensheldon** [comment]
I just released both changes mentioned here 🎉 : https://github.com/bensheldon/good_job/releases/tag/v3.18.1
