### ISSUE TITLE
 ActiveRecord::RecordNotUnique good_jobs.id error in rspec test suite

### ISSUE THREAD

**Issue by ajmanlove** [bensheldon/good_job#1072]
Upgrading from 3.7.4 -> 3.18.2. 

Seeing intermittent errors in our rspec test suite for `ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "good_jobs_pkey")`.

Relevant bits:
Rails: 7.0.7.2
Postgres 14
Using transactional fixtures.
`config.good_job.execution_mode = :inline`

This issue occurs within the scope of tests that rapidly create/updates test records in quick succession. These records use an after_commit lifecycle hook to enqueue a future job at a delay. Intermittently, we will see the enqueue result in a duplicate key violation.

Simplified repro case: 

Given a model
```
class MyModel < ApplicationRecord
  after_commit :enqueue_the_job

  def enqueue_the_job
    jitter_seconds = rand(0.1..10.0)
    MyJob.set(wait: jitter_seconds)
                        .perform_later(argument: 1)
  end
end
```

And a spec:
```
  it 'should cause the issue intermittently' do
    create(:my_model)
    create(:my_model)
    create(:my_model)
    create(:my_model)
    create(:my_model)
    create(:my_model)
    create(:my_model)
  end
```

At some frequency, we will see the test fail with a duplicate primary key error. For example this logging, showing the enqueue of the job prior and the job failing:

```
D, [2023-09-13T11:46:09.255323 #64698] DEBUG -- :   GoodJob::Execution Create (0.4ms)  INSERT INTO "good_jobs" ("id", "queue_name", "priority", "serialized_params", "scheduled_at", "performed_at", "finished_at", "error", "created_at", "updated_at", "active_job_id", "concurrency_key", "cron_key", "retried_good_job_id", "cron_at", "batch_id", "batch_callback_id", "is_discrete", "executions_count", "job_class", "error_event") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21) RETURNING "id"  [["id", 84], ["queue_name", "default"], ["priority", 0], ["serialized_params", "{\"job_class\":\"MyJob\",\"job_id\":\"84e4afd4-7e6d-42bd-bc70-03eac884998b\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[{\"argument\":1,\"_aj_ruby2_keywords\":[\"argument\"]}],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2023-09-13T17:46:09Z\"}"], ["scheduled_at", "2023-09-13 17:46:15.820369"], ["performed_at", nil], ["finished_at", nil], ["error", nil], ["created_at", "2023-09-13 17:46:09.254109"], ["updated_at", "2023-09-13 17:46:09.254202"], ["active_job_id", "84e4afd4-7e6d-42bd-bc70-03eac884998b"], ["concurrency_key", "MyJob"], ["cron_key", nil], ["retried_good_job_id", nil], ["cron_at", nil], ["batch_id", nil], ["batch_callback_id", nil], ["is_discrete", true], ["executions_count", 0], ["job_class", "MyJob"], ["error_event", nil]]
D, [2023-09-13T11:46:09.255937 #64698] DEBUG -- :   SQL (0.1ms)  NOTIFY good_job, '{"queue_name":"default","scheduled_at":"2023-09-13T17:46:15.820Z"}'
D, [2023-09-13T11:46:09.261774 #64698] DEBUG -- :   GoodJob::Execution Create (0.9ms)  INSERT INTO "good_jobs" ("id", "queue_name", "priority", "serialized_params", "scheduled_at", "performed_at", "finished_at", "error", "created_at", "updated_at", "active_job_id", "concurrency_key", "cron_key", "retried_good_job_id", "cron_at", "batch_id", "batch_callback_id", "is_discrete", "executions_count", "job_class", "error_event") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21) RETURNING "id"  [["id", 0], ["queue_name", "default"], ["priority", 0], ["serialized_params", "{\"job_class\":\"MyJob\",\"job_id\":\"eb2468ae-8c77-442b-9426-23aef6bb3318\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[{\"argument\":1,\"_aj_ruby2_keywords\":[\"argument\"]}],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2023-09-13T17:46:09Z\"}"], ["scheduled_at", "2023-09-13 17:46:13.614897"], ["performed_at", nil], ["finished_at", nil], ["error", nil], ["created_at", "2023-09-13 17:46:09.258493"], ["updated_at", "2023-09-13 17:46:09.258599"], ["active_job_id", "eb2468ae-8c77-442b-9426-23aef6bb3318"], ["concurrency_key", "MyJob"], ["cron_key", nil], ["retried_good_job_id", nil], ["cron_at", nil], ["batch_id", nil], ["batch_callback_id", nil], ["is_discrete", true], ["executions_count", 0], ["job_class", "MyJob"], ["error_event", nil]]
D, [2023-09-13T11:46:09.262048 #64698] DEBUG -- :   TRANSACTION (0.2ms)  ROLLBACK TO SAVEPOINT active_record_1
E, [2023-09-13T11:46:09.262147 #64698] ERROR -- : Failed enqueuing MyJob to GoodJob(default): ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "good_jobs_pkey"
DETAIL:  Key (id)=(0) already exists.
)
```

I _think_ this would be an isolated race condition to the nature of a test suite, but also trying to gauge if this would be an issue on a production environment with good_job running in an external mode.  I am also not familiar enough with the code base here to guess why an explicit `id` is being provided to a table with an auto-incremented primary key.

If I slap an arbitrary `sleep` before the job `.perform_later` I am no longer able to reproduce the issue -- however would prefer not to introduce a sleep into code for the benefit of a test.

**Comment by bensheldon** [comment]
Hmmmm. So what's really strange here is that your logs indicate that an integer is being INSERTed into the `good_jobs` table which as a UUID as the `id` column: `[["id", 84],`, `[["id", 0]`. That is not normal.

You could take a look in your schema.rb to verify that the column type is a UUID and looks something like:

https://github.com/bensheldon/good_job/blob/3c45787add63c72f6c365275f518121664faa126/spec/test_app/db/schema.rb#L61

The newer versions of GoodJob do use the Active Job ID as the primary key:

https://github.com/bensheldon/good_job/blob/3c45787add63c72f6c365275f518121664faa126/app/models/good_job/execution.rb#L499

That ID should always be a `SecureRandom.uuid` according to Active Job:

https://github.com/rails/rails/blob/edd43af862ef3701f4b7ca91ce659fde4e3e06b3/activejob/lib/active_job/core.rb#L95

...unless maybe there is something in your test suite that is overriding that value?

**Comment by ajmanlove** [comment]
Our schema has good_jobs using the bigint id:

```
  create_table "good_jobs", force: :cascade do |t|
```

It has been bigint since we first integrated with good_job looks like back since 1.9.6.

**Comment by bensheldon** [comment]
welp, that's going to cause problems 😞 

The id column has always been generated as a UUID, so maybe someone edited that in your setup migration. Here's the template from v1.9.6: https://github.com/bensheldon/good_job/blob/e83d27448abf54195fa09eb03a872eefb39b9a03/lib/generators/good_job/templates/migration.rb.erb#L5

You'll need to change the primary key over to be a UUID. Do you need help making that change?

**Comment by ajmanlove** [comment]
welp indeed, no idea why that change was made. Yeah, do you have a stable strategy for me to employ to fix that? Is it as simple as making the id column the same value as the `active_job_id` column?

**Comment by bensheldon** [comment]
Based on [this blog post](https://pawelurbanek.com/uuid-order-rails), I think something like this should do it:


```ruby
class AddUuidToGoodJobs < ActiveRecord::Migration
  def up
    add_column :good_jobs, :uuid, :uuid 

    execute "UPDATE good_jobs SET uuid = active_job_id"
    change_column :good_jobs, :uuid, :uuid, default: "gen_random_uuid()", null: false

    rename_column :good_jobs, :id, :integer_id
    rename_column :good_jobs, :uuid, :id
   
    execute "ALTER TABLE good_jobs drop constraint good_jobs_pkey;"
    execute "ALTER TABLE good_jobs ADD PRIMARY KEY (id);"

    # Optionally you remove auto-incremented
    # default value for integer_id column
    execute "ALTER TABLE ONLY good_jobs ALTER COLUMN integer_id DROP DEFAULT;"
    change_column_null :good_jobs, :integer_id, true
    execute "DROP SEQUENCE IF EXISTS good_jobs_id_seq"
  end

  def down
    raise ActiveRecord::IrreversibleMigration
  end
end
```

I'm not sure how many records you'll be updating, but if it's not a lot it probably wouldn't block for too long 😬

**Comment by ajmanlove** [comment]
Alrighty, seems straightforward to me. We'll manage the migration pathway. Appreciate the time and correction here. Cheers.

**Comment by bensheldon** [comment]
@ajmanlove happy to help and you have all my sympathy in making that fix. I hope the rest of the updates go smoothly 🤞🏻 💛
