### ISSUE TITLE
Add retries exhaused callback

### ISSUE THREAD

**Issue by krivospitsky** [bensheldon/good_job#1080]
I need to detect if job exceeds all retries and still fail.
Is any options to handle this situation like sidekiq_retries_exhausted in sidekq?

**Comment by bensheldon** [comment]
👍🏻 That's a feature of Active Job. You can [pass a block to `retry_on`](https://api.rubyonrails.org/classes/ActiveJob/Exceptions/ClassMethods.html#method-i-retry_on):

```ruby
retry_on MyError, attempts: 3 do
  # called when retries are exhausted 
end
```

If you needed to hook in for instrumentation, the event name is `retry_stopped.active_job`: https://guides.rubyonrails.org/active_support_instrumentation.html#retry-stopped-active-job
