### ISSUE TITLE
Add environment variable to mirror `cleanup_preserved_jobs --before-seconds-ago=SECONDS`

### ISSUE THREAD

**Issue by bensheldon** [bensheldon/good_job#110]
The CLI should have an environment variable option for all parameters. `cleanup_preserved_jobs --before-seconds-ago=SECONDS` is missing an environment variable option.

Add `GOOD_JOB_CLEANUP_PRESERVED_JOBS_BEFORE_SECONDS_AGO` as an environment variable that defers to the parameter.

**Comment by gadimbaylisahil** [comment]
I have finished with the PR including documentation change, please review :pray:
