### ISSUE TITLE
Dashboard blocked in iframe tag

### ISSUE THREAD

**Issue by icyleaf** [bensheldon/good_job#1111]
I want use good_job instead of sidekiq but some issues happened to me:

1. i can not use url_helper, because good job root path redirect to jobs. workaround `GoodJob::Engine.routes.url_helpers.jobs_path`
2. good job can not use in `iframe` tag, brower returns **blocked:other** and render `localhost refused to connect.`

Any help please, thanks.

**Comment by bensheldon** [comment]
For 1., you should be able to use `good_jobs.jobs_path`: https://guides.rubyonrails.org/engines.html#routes

For 2., can you tell me about what you want to achieve by embedding in an iframe? That is blocked by default for security: https://github.com/bensheldon/good_job/blob/101fc86e01875d3db1333e6a93e0d2cb5f5678fe/app/controllers/good_job/application_controller.rb#L19

If the defaults don't work for your security situation, you can override that by doing something like:

```ruby
ActiveSupport.on_load("good_job_application_controller") do 
  content_security_policy do |policy|
    # set your own directives
  end
end
```

**Comment by icyleaf** [comment]
> For 1., you should be able to use good_jobs.jobs_path: https://guides.rubyonrails.org/engines.html#routes

Thank you very much, I missed that part of the document!

> can you tell me about what you want to achieve by embedding in an iframe?

I can re-use the dashbord web ui to developers in zealot [background jobs](https://zealot.ews.im/docs/user-guide/administrator/monitoring/background-jobs).

I'll dig it, some breaking changes to migrating, such like:

- [x] keep tracking failures jobs (built-in)
- [x] dynamic scheduler (formerly [sidekiq-scheduler](https://github.com/sidekiq-scheduler/sidekiq-scheduler))
- [ ] job status (formerly [activejob-status](https://github.com/inkstak/activejob-status))

**Comment by bensheldon** [comment]
aha! Thanks for that context! Yep, I think do the csp-override like I shared is the best way right now to make granular changes to GoodJob's default.

I think activejob-status should continue to work, as it's compatible with Active Job and just adds some before/after/around/rescue_from hooks: https://github.com/inkstak/activejob-status/blob/main/lib/activejob-status.rb#L22-L31

**Comment by icyleaf** [comment]
Embed dashboard works! tiny fix: `ActiveSupport .on_load` only accepts symbol hook name.

> ...though if all you want to do is simply see if jobs are completed, you could use the GoodJob::Job model to query the table directly.

I use [this logical code](https://github.com/tryzealot/zealot/blob/refactor/new-background-job/app/models/backup.rb#L163-L172) to reslove dynamic scheduler. 

I used hard code for job status (operate redis directly), may be i need rewrite full logical about this part. 😢
