### ISSUE TITLE
Mac forking exception when using Spring

### ISSUE THREAD

**Issue by HashNotAdam** [bensheldon/good_job#1115]
We are running RSpec via Spring and certain tests throw the following exception:
```
objc[24658]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[24658]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

This exception disappears if I perform any of the following:

- Remove GoodJob
- Put GoodJob into async mode in the test environment
  - Interestingly, this only works when set in an initializer, not when added to `environments/test.rb`
- Completely disable Spring
- Add the env var `OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` and then reboot Spring

I'm not seeing this issue in CI (GitHub Actions running Ubuntu 22.04.3), only on development Macs.

Our stack is:
- M2 Mac
- good_job (3.19.4)
- spring (4.1.1)
- rails (7.0.8)
- rspec-rails (6.0.3)

I'd be happy to offer an example to reproduce the issue, but I can't seem to identify what makes the failing tests different. None of the tests use GoodJob; I've only just added it to the project and we haven't started using it yet. These are unit tests—so Puma doesn't coming play—so when might there be forking running a unit test with GoodJob in the default inline mode?

**Comment by bensheldon** [comment]
Hmm, I wonder if you are running into this issue: https://github.com/rails/rails/issues/38560

I don't imagine anything directly in GoodJob would cause this because GoodJob is pure Ruby, no C extensions. But maybe adding GoodJob bumped your version of `pg` or some other gem that is susceptible to this.

**Comment by HashNotAdam** [comment]
> Hmm, I wonder if you are running into this issue: [rails/rails#38560](https://github.com/rails/rails/issues/38560)
> 
> I don't imagine anything directly in GoodJob would cause this because GoodJob is pure Ruby, no C extensions. But maybe adding GoodJob bumped your version of `pg` or some other gem that is susceptible to this.

Thanks for a quick response. I've checked the commit, and it only added new dependencies; none were updated.

Do you have any theories as to why moving into async mode would make the issue go away? I don't mind putting in debugging time, I'm just short on ideas. Any insights you might have would be super helpful.

**Comment by bensheldon** [comment]
I'd love to figure this out too, though I'm short of ideas. 

Specifically on async vs inline, that makes me wonder if you are enqueuing jobs in your tests that are raising this exception? I'm imagining that async mode, in many tests, will not actually execute the jobs (async only executes jobs in the webserver, unless you're using `:async_all`), whereas inline does simply run the jobs inline/immediately in the current thread.

Also, it's a little strange about your comment about test.rb behaving different than an initializer. That could be unrelated to the error, but I'm curious what's that about: are you overriding the config in an initializer elsewhere, or maybe using Active Job TestHelper, which will override the queue adapter with TestAdapter?

**Comment by HashNotAdam** [comment]
We're not using GoodJob yet. I installed it so I could start using it either today or next week, so none of the tests call GoodJob/Active Job.

I just looked at the config thing; it looks like a silly mistake. `environments/test.rb` included:
```
config.good_job.execution_mode = :async
```
But `environments/test.rb` is run before `initializers/good_job.rb` and the initializer was using:
```
config.good_job = {
  ...
}
```
So it was overwriting the previous settings

**Comment by bensheldon** [comment]
oh no! That mistake with assigning individual keys then clobbering with a hash is very common 😞

Does that mean now that it's _always_ causing this weird `+[__NSCFConstantString initialize]` exception in all modes? Consistency is good, at least for debugging 😊

**Comment by HashNotAdam** [comment]
No, sorry, I've been keeping my test environment in async mode to avoid the exceptions, but I've moved that setting from my initializer to the test environment file.

I've had a lot on, but I can try to debug a bit more soon. If I understand your earlier comments, this issue should be related to a gem that includes C-extensions? I could safely avoid checking Ruby-only gems?

**Comment by HashNotAdam** [comment]
While I never got to the bottom of this, the problem has gone away. I wish I could have left a note about what the underlying issue was, but I'm afraid I don't know

**Comment by chrisortman** [comment]
@bensheldon This could maybe be re-opened. I encountered this issue but my situation is different.

Ruby 3.3.0, Rails 7.1.3

Mine fails when running tests. I suspect this is related to rails parallelization code and forking & threads.

I'm not aware that rails provides any test hooks similar to puma in order to control what good job is doing. 
My workaround was to set the active_job queue_adapter to :test in the environments/test.rb
