### ISSUE TITLE
Show whether or not cron scheduler is enable in dashboard (UI)

### ISSUE THREAD

**Issue by bforma** [bensheldon/good_job#1117]
It would be great if I could see whether or not (in any process) the cron scheduler is enabled. Perhaps add a column to the processes table view?

**Comment by bforma** [comment]
I just noticed that when I click on the "info" (i) button of a process, I can see whether or not cron is enabled. A bit hidden, but still useful 👍 .

**Comment by bensheldon** [comment]
👍 I'd accept a PR if you wanted to add it as a new column in the Processes table.

**Comment by bensheldon** [comment]
Done in #1127
