### ISSUE TITLE
Use partial indices for cron_key?

### ISSUE THREAD

**Issue by defkode** [bensheldon/good_job#1161]
Hi @bensheldon

I observed constantly growing indices:

```
'good_jobs::index_good_jobs_on_cron_key_and_created_at' bloat 35372.5 waste 553 MB
'good_jobs::index_good_jobs_on_cron_key_and_cron_at' bloat 33274.0 waste 520 MB
```

The problem is that the application **does not use the CRON functionality** - thus cron_key and cron_at are always NULL.

Application uses PG version 14.7, good_jobs table has a lot of churn, but except occasional bursts - enqueued jobs count is low (< 100). VACUUMS are triggered regularly, but for some reason those indices' size stay intact. Non-production databases (staging/sandbox) manifest themselves in the same way.

I wonder if other users have also experienced this problem?

Problem can be mitigated with `VACUUM FULL good_jobs` or `REINDEX ...`, but I think the correct solution is to use partial indices:

```rb
add_index :good_jobs, [:cron_key, :created_at], name: :index_good_jobs_on_cron_key_and_created_at, where: 'cron_key IS NOT NULL'
add_index :good_jobs, [:cron_key, :cron_at], name: :index_good_jobs_on_cron_key_and_cron_at, where: 'cron_key IS NOT NULL', unique: true
```

Is there any downside to this approach? If not, I'll be happy to prepare a PR to fix it.

**Comment by bensheldon** [comment]
Not to scope creep, but it would be helpful if you also could drop this index too: #900

**Comment by defkode** [comment]
> Not to scope creep, but it would be helpful if you also could drop this index too: #900

In our scenario, both indexes are used intensively:

```
index_good_jobs_on_active_job_id_and_created_at; 12 MB; 540986 (scans)
index_good_jobs_on_active_job_id; 800 kB; 133125100 (scans)
```

I am not sure if this is a good idea to drop it 🤔

**Comment by DanielHeath** [comment]
Looks like a good change. When I upgraded, my CI instrumentation pointed out that these migrations do not rollback to the old state if you run them "down" (instead, they mark themselves as rolled back but keep the new schema).

If you would like to enforce upgrade migrations having a working rollback path (to use if something goes wrong during the deploy, etc), I'd be happy to contribute a CI check for that.

**Comment by bensheldon** [comment]
@DanielHeath yep, I'd appreciate the additional test. I'm kind of curious about them not being rollbackable because I definitely QA'd that (though automated testing would be better).

**Comment by DanielHeath** [comment]
The `down` migration creates an index with `where: "(cron_key IS NOT NULL)"`, where previously it lacked that condition.

**Comment by bensheldon** [comment]
Oh yep, I messed that up 🤦🏻
