### ISSUE TITLE
Storing backtrace in database?

### ISSUE THREAD

**Issue by abali96** [bensheldon/good_job#1162]
Loving GoodJob so far, thanks so much for this!

I was wondering if there's an option to store the backtrace (or at least a few lines of it) in the good_job_executions table. It'd be handy to have that information in the database and UI in order to determine the specific cause of a failure, and so that once I fix a bug, I can easily identify all jobs caused by that same bug and retry them. The `error` column often isn't specific enough for me to pinpoint this.

Am I correct in my read that the best way to get the backtrace right now is to set `on_thread_error` and report the error to Rails, which then would have it printed to the logs and/or sent to a tool like Sentry?

Thanks!

**Comment by bensheldon** [comment]
> Am I correct in my read that the best way to get the backtrace right now is to set `on_thread_error` and report the error to Rails, which then would have it printed to the logs and/or sent to a tool like Sentry?

Yep, I recommend using a different tool.

Storing backtraces is frequently requested, but I've generally believed that debugging _jobs_ is largely the same as debugging web requests (or anything else in Rails) so not specific to background jobs.

...but I dunno. It gets asked for frequently enough that I guess I'm open if someone wanted to contribute it. The thoughts that come to mind are:

- How should backtrace be stored in the database (string, postgres array, json?). Is it just for manual inspection in the Dashboard or would someone automate against it?
- Would it just store the equivalent of the log output, or should it walk the exception `cause` tree too, and in that case, what's the structure?
- Are there any security concerns to design for?
- Is there necessary context to make it actionable? (e.g. application version)

"Good enough" is the mantra of GoodJob, so I would never imagine it needs to be perfect, but there are some design decisions there.

And then, thinking laterally, what are alternative improvements? e.g. allow adding a custom link to the dashboard to search for a particular error in Sentry or the error reporter.

**Comment by abali96** [comment]
Great points, will give it some thought! Thank you for the quick response.

**Comment by bensheldon** [comment]
I noticed the Solid Queue is storing backtrace. I went to see how it stores the backtrace, and it stores the backtrace as an array in serialized JSON String:

https://github.com/basecamp/solid_queue/blob/bf6bcf2b63a4f82164dd121a312c6eb3b576fda7/app/models/solid_queue/failed_execution.rb#L33

**Comment by jesseduffield** [comment]
+1 for this feature. Also worth noting that both sidekiq (and its sibling project Faktory) store backtraces too. As somebody familiar with sidekiq wanting to remove redis from their stack and use postgres for a job queue, seeing the backtrace in the dashboard is a huge benefit for debugging, because it typically all the information I need to fix the bug without needing to try and dig into another system to find the logs related to the failing job

**Comment by bensheldon** [comment]
I'd be ok if someone wanted to add this to GoodJob. I think it should be a Postgres array of text, stored on the `good_job_executions` table (the DiscreteExecution model).

**Comment by Intrepidd** [comment]
@bensheldon 👋 contemplating doing a PR for just this, would you prefer it to be opt-in, opt-out, or just default ? 

> Database migrations introduced in minor releases are not required to be applied until the next major release.

By reading this in the doc, I guess we would need to test for the presence of the column anyway

**Comment by bensheldon** [comment]
Thanks for considering working on this!

Default. I think the column should live on the `GoodJob::DiscreteExecution` model / `good_job_executions` table. The code should check for the column existence before writing or reading from the column (you can find examples searching for `_migrated?` methods or places where the `columns_hash` is inspected)

**Comment by jesseduffield** [comment]
@bensheldon great that this is now done. Do you know roughly when this will be released?

**Comment by bensheldon** [comment]
👍 Released! https://github.com/bensheldon/good_job/releases/tag/v3.28.0

**Comment by jesseduffield** [comment]
Awesome, thanks
