### ISSUE TITLE
Install PgHero on the Demo app

### ISSUE THREAD

**Issue by bensheldon** [bensheldon/good_job#1166]
The demo app tries to touch all the GoodJob features (anything missing?) so it would be nice to get any helpful performance telemetry from it.

**Comment by andyatkinson** [comment]
Hi @bensheldon I've installed PgHero a handful of times and mucked around a bit in the source code. Can you link up the demo app and just to clarify, are you looking for external help here (I may be interested)? Thanks.

**Comment by bensheldon** [comment]
Yes please to help. The Demo app (a full Rails app) lives in this same repository, in the `demo/` directory: https://github.com/bensheldon/good_job/tree/main/demo
