### ISSUE TITLE
Wrong quoting of the query to spot new jobs?

### ISSUE THREAD

**Issue by marcomarcianesi** [bensheldon/good_job#1179]
Hello.
Using `good_job (3.18.2)` and `rails (7.0.4)`

I'm seeing something weird in the logs, that makes the jobs in one of my queues never picked for execution.

As per screenshot,

<img width="860" alt="Screenshot 2023-12-12 at 19 05 14" src="https://github.com/bensheldon/good_job/assets/19145520/a03fddc8-60e6-4aa3-90b8-6da5f5741982">

the query to find new jobs to execute is using a triple quote before the queue name.
This doesn't make PG fail, in fact the query is complete, with 0 results.
I've tried removing the triple quotes into a single one, and I do get as a result 1 job that should be executed

I'm sure it's something I'm not getting about escaping, could you give me a small hand?

Thanks

**Comment by bensheldon** [comment]
That's weird!  Where are those quotes coming from? 🤔 

I'm imagining that maybe the quotes are being passed in via the `--queues` configuration? 

Are you able to access the Rails Console? 

```ruby
# bin/rails c

# Show all queues that jobs are actually enqueued on
GoodJob::Job.group(:queue_name).count

# Show all of the schedulers and the queues they're pulling from
GoodJob::Process.pluck(:state).map { |state| state["schedulers"].map { |s| s["name"] } }.flatten.uniq

```

**Comment by Earlopain** [comment]
I've had something similar happen. Using docker, I have a env var in my compose file for the goodjob service, like so:
`GOOD_JOB_EXEC: bundle exec good_job --queues="queue1:1;queue2"`. I execute this using a procfile: `good_job: $GOOD_JOB_EXEC`

Before that setup I had the command as is directly in the Procfile but after moving it to Docker something changed and I had to drop the quotes around the queues parameter since the quote was part of the name for the first queue (not the last one though (I think, it's been a while)). Not exactly the same as this issue but perhaps relevant.

**Comment by marcomarcianesi** [comment]
@bensheldon I think you have a point, look at this

```
  GoodJob::Job Count (1.2ms)  SELECT COUNT(*) AS "count_all", "good_jobs"."queue_name" AS "good_jobs_queue_name" FROM "good_jobs" WHERE "good_jobs"."retried_good_job_id" IS NULL GROUP BY "good_jobs"."queue_name"
=> {"sitemap"=>126, "deferrable"=>9, "transactional"=>9, "default"=>19}
irb(main):002:0> GoodJob::Process.pluck(:state).map { |state| state["schedulers"].map { |s| s["name"] } }.flatten.uniq
  GoodJob::Process Pluck (1.2ms)  SELECT "good_job_processes"."state" FROM "good_job_processes"
=> ["GoodJob::Scheduler(queues='transactional max_threads=5)", "GoodJob::Scheduler(queues=deferrable max_threads=4)", "GoodJob::Scheduler(queues=sitemap max_threads=1)"]
irb(main):003:0> 
```

I'm starting it with Docker in this way

```
CMD ["bundle", "exec", "good_job", "--queues='transactional:5;deferrable:4;sitemap:1'"]
```

and this is exactly what @Earlopain is mentioning!

I solved it by transforming into 

```
CMD ["bundle", "exec", "good_job", "--queues=transactional:5;deferrable:4;sitemap:1"]
```

I'm sorry to have raised an issue for something that wasn't a problem with good job at all, I just hope this issue can be helpful for who'll have the same problem
