### ISSUE TITLE
Show last update on top nav bar

### ISSUE THREAD

**Issue by Pauloparakleto** [bensheldon/good_job#1183]
Based on this [discussion](https://github.com/bensheldon/good_job/discussions/1109), it was suggested by @simi as an initial idea moving the footer message to the top.
![image](https://github.com/bensheldon/good_job/assets/52010485/f2f3ea94-db59-427a-acb8-1310174752f4)
About been not sure what to include in footer, I think should be useful author name(with link to author) and github(with link to goodjob repository).
![image](https://github.com/bensheldon/good_job/assets/52010485/81bf852c-02f5-4e1e-a4ec-6811aed0c1b6)

**Comment by bensheldon** [comment]
❤️

I think the time should always be visible so it's usable on a passive wallboard ("is that screen frozen?")

I had an idea to move the footer up to a secondary nav and it could live there: https://github.com/bensheldon/good_job/issues/1116

**Comment by Pauloparakleto** [comment]
@bensheldon printing screen on ubuntu hides the hover information, then I needed to take a picture with my phone :D

**Comment by simi** [comment]
@Pauloparakleto this doesn't work for me. I would like to have info visible without any additional effort (like moving mouse).

**Comment by Pauloparakleto** [comment]
@bensheldon can you please add a expected behavior since it became cumbersome what to do.
1. Only move the footer to a new navbar?
2. Add a new nav bar with configuration to add or remove the blocks/elements needed?
Has the first approach conflicting with the second idea?

How to add at least what we need to this first version?

**Comment by Pauloparakleto** [comment]
Doing so, what would remain in the footer?

**Comment by bensheldon** [comment]
Sorry, to be explicit:

1. Move the footer up into a secondary navbar that is immediately below the primary navbar
2. Add the last-updated timestamp to the secondary navbar.
3. Allow the content of the secondary navbar (entirely) to be overridden. (this comes a distant third; I realized from #1197 that so long as it lives in its own template, it's trivially overridden by the main app)

**Comment by bensheldon** [comment]
> Doing so, what would remain in the footer?

I guess it would go away entirely. I'm not sure what else would go in there (though it is nice to be clear "This is the bottom of the page")
