### ISSUE TITLE
Dashboard Missing Translation?

### ISSUE THREAD

**Issue by lloydpick** [bensheldon/good_job#1192]
Just started to play with GoodJob and the Dashboard seems to be throwing up a lot of missing translation errors...

<img width="1723" alt="Screenshot_2023-12-18_at_1_20_44_PM" src="https://github.com/bensheldon/good_job/assets/71318/f99c48a0-bce7-43c5-9b37-418a321d1dfe">

I do have i18n with in the Rails app I have, but I don't see anything that could be causing issues.

Rails 7.1.2
GoodJob 3.21.5

**Comment by bensheldon** [comment]
That's strange! You can see what it's supposed to look like on the Demo, which is also running Rails 7.1.2: https://goodjob-demo.herokuapp.com/good_job/jobs

I noticed that the translation key it's looking for is a little strange:

```
Translation missing: en.good_job.datetime.distance_in_words.minutes
```

The Rails [`distance_of_time_in_words` key is `.x_minutes`](https://github.com/rails/rails/blob/462e8e8b1c74d46a78e7077c5b07bfbc6fab08b0/actionview/lib/action_view/helpers/date_helper.rb#L122) whereas yours just shows `.minutes`.

Any change you're monkeypatching one of those helpers?

**Comment by lloydpick** [comment]
Ugh, my bad. I forgot I had this gem loaded... https://github.com/radar/distance_of_time_in_words as it appears in the Gemfile as `dotiw`.

If I remove it, then it works correctly.
