### ISSUE TITLE
Limiting by executed jobs count by period

### ISSUE THREAD

**Issue by Marcovecchio** [bensheldon/good_job#1198]
I have a situation where I need to limit job execution by a given period of time. Example: I want to limit a given job to 50 executions per minute. When the limit is reached, GoodJob would wait until the time (1 minute) expires, to resume picking new jobs for execution.

The reason for this is that the job will call an external API that rete-limits us.

In other words: is there a way to rate limit GoodJob? Or should I go for implementing this myself in the application?

Thanks!

Eduardo

**Comment by bensheldon** [comment]
This sounds similar to #716, which is not implemented.

I think you could likely do something like this though:

```ruby
class YourJob < ApplicationJob
  LimitExceededError = Class.new(StandardError)
  LIMIT_PER_MINUTE = 50

  retry_on LimitExceededError, retry: :polynomially_longer

  before_perform do
    # It's a little tricky/racy to try to get the perfect count
    # GoodJob::DiscreteExecution is not a public API, so it could change
    recent_executions = GoodJob::DiscreteExecution.where(job_class: self.class.name)
                                                  .where("created_at > ?", 1.minute.ago)
                                                  .where.not(error: "YourJob::LimitExceededError")
                                                  .count
    raise LimitExceededError if recent_jobs > LIMIT_PER_MINUTE
  end
end
```

**Comment by Marcovecchio** [comment]
Thanks a lot! That seems to be a good solution, at least while it's not officially implemented in Good job.

I have only a last question, regarding this implementation: it will raise an exception, to force a retry, right? Is there a way to make it not consume one of the retries? Thinking about an extreme scenario, where the limiter takes a long time to be released, the retries might go exhausted. If I could prevent the limiter to consume retries, that would be perfect! Is there a way to do that?

Thanks again,

Eduardo

**Comment by bensheldon** [comment]
> I have only a last question, regarding this implementation: it will raise an exception, to force a retry, right?

Unfortunately not. the `before_perform` happens after the job has already been dequeued. 

I updated the example to do infinite retries. This is also how the non-throttling Concurrency Control extension works:

https://github.com/bensheldon/good_job/blob/b2f0344a449a2beb39761a0784de09612e5dc0de/lib/good_job/active_job_extensions/concurrency.rb#L45-L49

**Comment by Marcovecchio** [comment]
Many thanks, that will solve our problem! And congratulations for the great job on good job :)

Eduardo

**Comment by bensheldon** [comment]
Thank you! Please report back about how that works for you. I would like to have similar functionality in GoodJob so knowing about your experience is helpful 👍🏻

**Comment by marckohlbrugge** [comment]
> I updated the example to do infinite retries.

@bensheldon I don't see it in the code example. Did you mean to add `, attempts: Float::INFINITY` ?

Just checking, because I'm in the process of migrating from Sidekiq Enterprise and looking for an alternative to their Rate Limiting API. Your proposed solution seems like a good fit.

**Comment by bensheldon** [comment]
@marckohlbrugge oops! I missed that. btw, there is a better example (or at least with more bugs worked through) in this gist: https://gist.github.com/bensheldon/89f772eb8f55058e87959b008e5081b9

**Comment by marckohlbrugge** [comment]
@bensheldon Thanks Ben! Super helpful. I've left a comment with some modifications and a question: https://gist.github.com/bensheldon/89f772eb8f55058e87959b008e5081b9?permalink_comment_id=4934860#gistcomment-4934860

**Comment by marckohlbrugge** [comment]
> @marckohlbrugge oops! I missed that. btw, there is a better example (or at least with more bugs worked through) in this gist: https://gist.github.com/bensheldon/89f772eb8f55058e87959b008e5081b9

Got a question about your code example. It seems like the following line…

```ruby
.where("performed_at > ?", throttle_period.ago)
```

…would prevent `allowed_active_job_ids` from ever including `job.job_id`, because it's called in the `before_perform` callback, so `job` would never have a chance to get performed.

See here:

```ruby
raise GoodJob::ActiveJobExtensions::Concurrency::ConcurrencyExceededError unless allowed_active_job_ids.include?(job.job_id)
```

Am I misunderstanding?

Maybe the check should be something more like this:

```ruby
        job_allowed = allowed_active_job_ids.include?(job.job_id)
        within_threshold = allowed_active_job_ids.count < throttle_count

        raise GoodJobThrottleExceededError unless job_allowed || within_threshold
```

**Comment by marckohlbrugge** [comment]
Here's my current attempt with (partially failing) test coverage:

https://gist.github.com/marckohlbrugge/e345fd64c587d77ceedd32a61308143c

**Comment by marckohlbrugge** [comment]
@bensheldon Made a PR: https://github.com/bensheldon/good_job/pull/1270

**Disclaimer:** a lot of this is copy/pasting and getting help from AI. The specs seems to pass, but it's no guarantee this is good code 😅 (I have plenty of experience writing Rails apps, but not so much writing library code).
