### ISSUE TITLE
Lint - Introduce line character limits

### ISSUE THREAD

**Issue by gadimbaylisahil** [bensheldon/good_job#122]
Hi, I would like to get an opinion on what's your take on introducing line limits? 100~110ish characters? 

Most of the codebase is easy to read and navigate. There are also occurrences with long lines 110+ which slows down readability speed especially when working on small screen laptops.

**Comment by bensheldon** [comment]
I am opposed to enforced line-lengths. I find they create blockers for less-experienced developers.

I am welcome to refactors to address readability challenges, eg "this is difficult to understand on a small screen".
