### ISSUE TITLE
Buggy theme animation while switching tabs

### ISSUE THREAD

**Issue by AbhayVAshokan** [bensheldon/good_job#1224]
![flaky-theme-animation](https://github.com/bensheldon/good_job/assets/35297280/db906779-61b8-49f4-8b54-35e337267004)

**Link**: [goodjob-demo.herokuapp.com/](https://goodjob-demo.herokuapp.com/)
**Arc Browser**: Version 1.25.1 (45028) Chromium Engine Version 120.0.6099.216
**OS**: macOS 14.2.1 (23C71) M1

**Comment by bensheldon** [comment]
Thanks for reporting! That looks bad. I can look into that unless you have a theory already.

**Comment by bensheldon** [comment]
hmmm, I'm having trouble reproducing this. 

- Does that happen on any link navigation or just when using the tabbed navbar?
- Am I correct in assuming that your operating system is in Dark Mode, and you've set the Dashboard to light mode? (maybe that's related to the problem, though I think that shouldn't have a flash either)

**Comment by AbhayVAshokan** [comment]
1. It happens for every link navigation
2. Correct.

Every navigation reloads the entire website. It briefly defaults to theme="auto" before going to theme="light".
![theme](https://github.com/bensheldon/good_job/assets/35297280/c5dcd1df-9709-447b-a76a-b7ad935865e9)

**Comment by bensheldon** [comment]
Note to self: maybe related https://github.com/twbs/bootstrap/pull/39224

**Comment by carlosmintfan** [comment]
@bensheldon From a quick look, I think that isn't related because it only fixes an edge case for light OSes with "default" color mode. Anyway, make sure that the color-modes.js is included BEFORE the bootstrap CSS/JS (not only before the bootstrap js, but even before the bootstrap css) to make sure that color modes classes are applied to the page DOM before Bootstrap CSS styles it.

**Comment by carlosmintfan** [comment]
> Note to self: maybe related [twbs/bootstrap#39224](https://github.com/twbs/bootstrap/pull/39224)

Ah, yeah, related if it defaults to auto...but anyway we have a fix now :smile:
