### ISSUE TITLE
Broken pipe @ io_writev - <STDERR> (Errno::EPIPE)

### ISSUE THREAD

**Issue by wrmk** [bensheldon/good_job#1233]
Hi, recently I updated the good_job version and forgot to run `bin/rails g good_job:update`. 
As a result, good_job tries to inform about pending migrations but something goes wrong and I received a lot of copies of one error: 
`Broken pipe @ io_writev - <STDERR> (Errno::EPIPE)`

good_job version: 3.23.0
rails version: 7.0.8
ruby version: 3.2.2

the part of stacktrace of the error:
```
activesupport (7.0.8) lib/active_support/deprecation/behaviors.rb in write at line 21
activesupport (7.0.8) lib/active_support/deprecation/behaviors.rb in puts at line 21
activesupport (7.0.8) lib/active_support/deprecation/behaviors.rb in block in <class:Deprecation> at line 21
activesupport (7.0.8) lib/active_support/deprecation/reporting.rb in block (2 levels) in warn at line 26
activesupport (7.0.8) lib/active_support/deprecation/reporting.rb in each at line 26
activesupport (7.0.8) lib/active_support/deprecation/reporting.rb in block in warn at line 26
<internal:kernel> in tap at line 90
activesupport (7.0.8) lib/active_support/deprecation/reporting.rb in warn at line 22
good_job (3.23.0) app/models/good_job/base_record.rb in migration_pending_warning! at line 12
good_job (3.23.0) app/models/good_job/base_execution.rb in labels_migrated? at line 63
```

**Comment by bensheldon** [comment]
That's strange! I don't imagine that's related to GoodJob specifically as GoodJob reports through Active Support's deprecation reporter, which writes to STDERR.

Have you seen it reoccur?

**Comment by wrmk** [comment]
No, ran pending migrations and the error disappeared.

**Comment by bensheldon** [comment]
🙌
