### ISSUE TITLE
Batch callbacks not run when job fails, then succeeds

### ISSUE THREAD

**Issue by mikehale** [bensheldon/good_job#1239]
Given the following code, the success callback is never invoked. Is that expected?

```ruby
class CronCheckInJob < ApplicationJob
  class SuccessCallback < ApplicationJob
    def perform(batch, _params)
      # record success
    end
  end

  def perform(**kwargs)
    klass = kwargs[:class]
    GoodJob::Batch.enqueue(on_success: CronCheckInJob::SuccessCallback, check_in_keys: check_in_keys) do
       klass.constantize.perform_later
    end
  end
end

class TestJob < ApplicationJob
  def perform
    raise 'failing' if executions < 2
  end
end

CronCheckInJob.perform_later(klass: 'TestJob')
```

**Comment by bensheldon** [comment]
Thanks for opening this issue! I just poked at it and I think there's a bug with how a job is treated if it errors, but then later succeeds. I will dig into this more.

**Comment by bensheldon** [comment]
oh, let me ask: Is your `batch.on_success = 'CronCheckInJob::SuccessCallback'` a job? It must be a job.

**Comment by mikehale** [comment]
yes, and the callback works in the case where there are no errors on the original job

**Comment by bensheldon** [comment]
Are you seeing this in production, or just in test with :inline execution? (I ask because the issue I discovered is specifically with :inline)

**Comment by mikehale** [comment]
Good question. I'm running locally in development mode. It's running under the puma web process, but I'm not sure if that means it is :inline or not.

**Comment by mikehale** [comment]
I just tried changing :execution_mode to :external, and still seeing the same result.

**Comment by bensheldon** [comment]
Just wanted to briefly follow up: I think I've found the problem:

When #928 was introduced, I think I overlooked how that would interact with this line:

https://github.com/bensheldon/good_job/blob/ab4114af83cc05f4c6690ea19b900ca94d60d35d/app/models/good_job/batch_record.rb#L49

I think the simple fix is to add `&& execution.finished_at` there, but I want to add a few more tests and make sure that's truly the issue. But happy to have narrowed it down with your help.

**Comment by bensheldon** [comment]
This is released in https://github.com/bensheldon/good_job/releases/tag/v3.24.0

Thank you so much for reporting this!

**Comment by mikehale** [comment]
Wow, thanks for fixing this so quickly!
