### ISSUE TITLE
What's the difference between 'reschedule' and 'retry' in the dashboard?

### ISSUE THREAD

**Issue by jesseduffield** [bensheldon/good_job#1241]
![image](https://github.com/bensheldon/good_job/assets/8456633/de6fcbf8-f407-4188-b366-29a764581d9a)

First off, awesome work on this project, it's great.

When viewing failed jobs, it's not clear to me what the difference is between 'reschedule' and 'retry'. I couldn't find anything about the distinction in the readme or existing issues, so I figured to ask here.

**Comment by bensheldon** [comment]
Thanks! Good question:

- Reschedule: when a job is scheduled in the future and you want it to run _right now_. 
- Retry: when job has been _discarded_ and you want to run it again. 

Those buttons maybe could use some titles or hovers to explain.

**Comment by jesseduffield** [comment]
Thanks

**Comment by MSeneadza** [comment]
> Thanks! Good question:
> 
> * Reschedule: when a job is scheduled in the future and you want it to run _right now_.
> * Retry: when job has been _discarded_ and you want to run it again.
> 
> Those buttons maybe could use some titles or hovers to explain.

I came here to find out if "reschedule" was actually "run now".  Why not change the name of the buttons & menu items to "enqueue" or "run now"?  That seems clearer to me.
