### ISSUE TITLE
Production deployment question

### ISSUE THREAD

**Issue by mayank23** [bensheldon/good_job#1257]
Hi!

Pardon the noob question.

Let's say I wanted to build a cluster of good job instances that are separate from my rails servers. Is there a process to do that? Or is the only way to add more rails servers and start a good job process along side them?

Thanks

**Comment by bensheldon** [comment]
Happy to help 😊 The default production execution mode is `config.good_job.execution_mode = :external`, which will not execute jobs in the enqueuing process (eg your webserver).

You'll then want to run one or more instances of `bundle exec good_job` to execute the jobs.

**Comment by mayank23** [comment]
Ah ok great thanks!
