### ISSUE TITLE
Plain HTTP 500 Error when retrying a job for deleted record

### ISSUE THREAD

**Issue by padde** [bensheldon/good_job#1263]
When attempting to retry a job that takes a record (via GlobalID) as argument, and that record has already been deleted, it will raise an `ActiveJob::DeserializationError`. This results in a blank HTTP 500 error response which is not a nice experience.

Even worse, when trying to retry *all* discarded jobs as bulk operation it will not attempt any retries at all. It will also just respond with a plain HTTP 500 error, effectively not allowing to use this functionality any more if just one single job's arguments cannot be deserialized. It is not made visible to the user which job is affected and needs to be deleted first before being able to proceed.

Of course the same situation applies in case the deserialization fails for other reasons, but deleted records are a pretty common scenario that can happen at any time in most applications. 

For the single retry action it would be great to give better feedback to the user, e.g. a that a retry is not possible any more because the arguments cannot be deserialized. For the bulk action, I'd still expect the non-affected jobs to be retried.

Idea: Maybe there is also the possibility to not attempt deserializing the arguments at all before a retry? We would then see the deserialization error only during the next execution, and would completely avoid having to catch complex error scenarios on the side performing the retry?

**Comment by bensheldon** [comment]
Ooh, thanks for reporting this. It looks like this was already fixed for discarding jobs (#771), but not for retries 🤦 

I can fix this real quick 👍

**Comment by bensheldon** [comment]
No prob! I forget to release this last night, but it is now released: https://github.com/bensheldon/good_job/releases/tag/v3.26.1
