### ISSUE TITLE
support cronjob style for jobs also

### ISSUE THREAD

**Issue by newbenji** [bensheldon/good_job#129]
Suppose you have job you want to run each hour.
could be nice if this one also supports running it cronstyle also

**Comment by morgoth** [comment]
@newbenji It is a duplicate of https://github.com/bensheldon/good_job/issues/53

**Comment by newbenji** [comment]
sorry missed that one, but seem he made wont fix for that one ..

**Comment by bensheldon** [comment]
@newbenji Cron-like scheduling is outside of scope for GoodJob because it's not a native ActiveJob convention. If it exists upstream in ActiveJob, GoodJob will support it: https://discuss.rubyonrails.org/
