### ISSUE TITLE
Adapter to implement `enqueue_after_transaction_commit`

### ISSUE THREAD

**Issue by luizkowalski** [bensheldon/good_job#1310]
hey Ben 👋🏻 

I'm running an app on edge and noticed my jobs started failing after I updated Rails this afternoon. I tracked it down to [this commit](https://github.com/rails/rails/commit/a134d9166e4d34ab0d97fb82f3e4f0092b3b98ee) and I think [Adapter](https://github.com/bensheldon/good_job/blob/main/lib/good_job/adapter.rb) should implement `enqueue_after_transaction_commit?` too

**Comment by bensheldon** [comment]
You noticed quick! Would you be willing to make a PR for that?

**Comment by luizkowalski** [comment]
sure, let me play around with it a little bit
