### ISSUE TITLE
Potential documentation error in GoodJob::ActiveJobExtensions::NotifyOptions

### ISSUE THREAD

**Issue by pgvsalamander** [bensheldon/good_job#1321]
The documentation for using the NotifyOptions extension mention including `GoodJob::ActiveJobExtensions::Notify` in order to make use of those features, but the module defined is `GoodJob::ActiveJobExtensions::NotifyOptions`.  Is that a typo, or is there some magic I'm missing that defines that module elsewhere?

https://github.com/bensheldon/good_job/blob/d01b5456bd73584d61281aee6faa525a39b34d69/lib/good_job/active_job_extensions/notify_options.rb#L12

I'll submit a PR if this is an error.

**Comment by bensheldon** [comment]
Definitely a typo. Thanks!

**Comment by pgvsalamander** [comment]
Created #1322
