### ISSUE TITLE
`erb_lint` doesn't lint all files

### ISSUE THREAD

**Issue by Earlopain** [bensheldon/good_job#1329]
Something I noticed. There are quite a few template files just ending in `.erb`. These won't be picked up as they have to end with `.html.erb` for erb_lint to care.

**Comment by bensheldon** [comment]
WEIRD AND TIL. I just opened a PR. I'll fix that up. Thank you for reporting it.

I found this old old PR: https://github.com/Shopify/erb-lint/pull/86
