### ISSUE TITLE
How do I add jobs to an existing batch? 

### ISSUE THREAD

**Issue by gap777** [bensheldon/good_job#1337]
I'm having trouble understanding how to add new jobs to an existing batch.

Here's what I'm doing:

1. creating a batch

```
GoodJobs::Batch.new(metadata: 'foo').enqueue { TestJob.perform_later(bar: 1) } 
```

2. some time later, I'm adding a new job to the batch:

```
GoodJobs::Batch.find(that_batch_id).enqueue { TestJob.perform_later(bar: 2) }
```

3. I see my jobs performing wonderfully.

4. I see a batch created

5. There are no jobs in my batch (neither in Batch panel in GoodJobs dashboard, or is the GoodJobs::Job#batch_id set)

Can you advise on how to do this?

**Comment by bensheldon** [comment]
That's weird! I just tried this exploratory test and it passes:

```ruby
describe 'adding to an existing batch' do
  it 'will add jobs to the existing batch' do
    batch = GoodJob::Batch.new(metadata: 'foo')
    batch.enqueue { TestJob.perform_later }

    GoodJob::Batch.find(batch.id).enqueue { TestJob.perform_later }

    batch = GoodJob::Batch.find(batch.id)
    expect(batch.active_jobs.count).to eq 2
  end
end
```

Have you done anything to the `preserve_job_records` configuration?

**Comment by gap777** [comment]
Hmmm..... 
I have a config initializer:

```
Rails.application.configure do
  config.good_job.preserve_job_records = true
```

Also, maybe of note,  I am trying to test this using the Rails test job adapter. 

Finally, this doesn't work outside of the test (in a manual integration test) either.

**Comment by bensheldon** [comment]
> Also, maybe of note, I am trying to test this using the Rails test job adapter.

That's it ☝ (or at least one issue). Batches can only batch jobs that are enqueued to GoodJob.

That makes me think I could at least add a logger to the Batch job extension to log on enqueue like "This job was enqueued within a batch capture but not to the GoodJob Adapter; the job will not appear in the batch."

**Comment by gap777** [comment]
That seems good.

**Comment by bensheldon** [comment]
I just opened https://github.com/bensheldon/good_job/pull/1339 with a warning message. Could you try that locally and see if it helps debug better?

**Comment by gap777** [comment]
Thank you!

**Comment by bensheldon** [comment]
I just released those debug messages in https://github.com/bensheldon/good_job/releases/tag/v3.28.2
