### ISSUE TITLE
Whitespace in `queues` configuration can cause issues.

### ISSUE THREAD

**Issue by TAGraves** [bensheldon/good_job#1351]
We had the following `queues` config for a worker:
```
"queues": "+workload_5s: 3; +workload_15s,workload_5s:3; +workload_1m,workload_15s,workload_5s:2; +workload_2m,workload_1m,workload_15s,workload_5s:2; +workload_5m,workload_2m,workload_1m,workload_15s,workload_5s:2",
```

We observed that with this configuration, `workload_5m` jobs were never being worked. I removed all the spaces from the above configuration:
```
"queues": "+workload_5s:3;+workload_15s,workload_5s:3;+workload_1m,workload_15s,workload_5s:2;+workload_2m,workload_1m,workload_15s,workload_5s:2;+workload_5m,workload_2m,workload_1m,workload_15s,workload_5s:2",
```

Then the `workload_5m` jobs started getting picked up. So it seems like the space between the `;` and the `+workload_5m,` was causing an issue. I don't see it documented anywhere that whitespace is relevant, and indeed the readme even has several examples of whitespace being used in the queue configuration, so I suspect this is a bug.

**Comment by bensheldon** [comment]
GoodJob should be whitespace tolerant. I'm probably missing some `strip`'s 🤔  Here's where the string gets broken down into a configuration hash:

- Where the configuration constant is broken down: https://github.com/bensheldon/good_job/blob/2586313af6637ee3b865f5cb5d08ebbc435c132a/lib/good_job/multi_scheduler.rb#L12-L15

- Where the comma-separated list of queues gets broken down: https://github.com/bensheldon/good_job/blob/2586313af6637ee3b865f5cb5d08ebbc435c132a/app/models/good_job/execution.rb#L42-L68 

Also, I love how you've set up your queues 😍 

Let me make a test case, but I think it needs more `strip`ing

**Comment by bensheldon** [comment]
> Also, I love how you've set up your queues 😍

Unrelated: my one piece of feedback would be not to use the `+`-queue ordering. That has performance downsides and you likely _want_ to clear faster-SLO jobs first rather than the slower-SLO ones.
