### ISSUE TITLE
[BUG] [Dashboard] count isn't following by the filter

### ISSUE THREAD

**Issue by hotrungnhan** [bensheldon/good_job#1376]
You guy can look at the picture, job count currently is the sum of all queues, intstead of filter by queues `manga`
![image](https://github.com/bensheldon/good_job/assets/40029631/22b2f4e3-b888-40d0-afa8-d605c6ca7112)

**Comment by bensheldon** [comment]
Thanks for opening the issue. Would you want to try updating the counts to use the appropriately filtered query? Here's where they're calculated:

https://github.com/bensheldon/good_job/blob/ed7bbe33fde7127a85ef1005722a8afa99afe58e/app/filters/good_job/jobs_filter.rb#L10-L20

**Comment by hotrungnhan** [comment]
> Thanks for opening the issue. Would you want to try updating the counts to use the appropriately filtered query? Here's where they're calculated:
> 
> https://github.com/bensheldon/good_job/blob/ed7bbe33fde7127a85ef1005722a8afa99afe58e/app/filters/good_job/jobs_filter.rb#L10-L20

i've try this weekend.

**Comment by hotrungnhan** [comment]
@bensheldon  btw, i think it front end issue, cuz i didn't see the params is sent.
<img width="1361" alt="Screenshot 2024-06-18 at 09 51 09" src="https://github.com/bensheldon/good_job/assets/40029631/c32b4474-38ab-42db-8789-c99462e7623e">

**Comment by bensheldon** [comment]
Sorry, this is fixed in #1373. I will release shortly.

**Comment by hotrungnhan** [comment]
Really appreciate yours @bensheldon  and @SebouChu efforts, you're guy are making a really goods library, can't wait to apply it in my products. 

Now we can close this issue.

**Comment by SebouChu** [comment]
@hotrungnhan Haha, thanks, but all goes to @bensheldon, I'm just a small contributor 😄
