### ISSUE TITLE
Job retried infinitely 

### ISSUE THREAD

**Issue by jcrate** [bensheldon/good_job#1384]
I have a job that used to be run in a separate process, and early in the job code a condition was checked and if met, `exit` was called. This caused GoodJob to retry this job continously, even though `retry_on_unhandled_error` was not set anywhere and should default to false.

I've fixed the problem by simply raising an error so my error handler catches this condition, instead of using `exit`. But I'm curious why the job would be retried continuously.

**Comment by bensheldon** [comment]
Oh! It could be clearer in the docs but `retry_on_unhandled_error` refers to `StandardError` exceptions. The Readme say:

> Instances of `Exception`, like `SIGINT`, will always be retried, regardless of this attribute’s value.

That also applies to `exit` which raises an `SystemExit < Exception` that GoodJob won't catch. The intention behind this is that GoodJob can't distinguish between:

```ruby
def perform
  do_important_work
  exit # happily
end

# and

def perform
  exit # catastrophically
  do_important_work
end
```

I can totally sympathize though if you're adapting code that may previously have run as a script into a job. There'll be things like `exit` lurking around 💖

**Comment by jcrate** [comment]
Aha...I guess I didn't read far enough. Thanks for clearing that up for me.
