### ISSUE TITLE
undefined method `duration=' for an instance of GoodJob::Execution

### ISSUE THREAD

**Issue by benoittgt** [bensheldon/good_job#1404]
Hello

If you have this message, because of a bump by dependabot on GoodJob (from 3.29.5 to 4.0.0):
```
NoMethodError:
       undefined method `duration=' for an instance of GoodJob::Execution
```

The best idea is to go version 3.99 then look at logs. Mostly you need to do:

```sh
rails generate good_job:update
RAILS_ENV=test rails db:migrate
rails db:migrate
```

More infos: https://island94.org/2024/07/introducing-goodjob-v4

Maybe `duration=` you should still print a warning about what to do?

**Comment by bensheldon** [comment]
Thanks for opening this for visibility. This was the very last migration that was made just _last week_ before I cut the major upgrade. I even missed this on one of my own websites when I upgraded it 🎗

**Comment by benoittgt** [comment]
Nothing to fix but if people are looking to fix this issue. Please follow the initial message.

**Comment by gdonald** [comment]
Trying to upgrade, I get the error

    undefined method `duration=' for an instance of GoodJob::Execution.

I tried the suggestion above and got a skip:

    > be rails generate good_job:update
        skip  db/migrate/20240716000842_create_good_jobs.rb

Then there's nothing to migrate.

**Comment by bensheldon** [comment]
It looks like you're running `rails g good_job:update` while already on 4.0.3. You'll need to generate the migrations while pinned to v3.99.x.
