### ISSUE TITLE
How to maximise amount of jobs executed in parallel 

### ISSUE THREAD

**Issue by drale2k** [bensheldon/good_job#1418]
I am struggling to increase the amount of jobs goodjob will process at any given time. It seems hard stuck at max 5 running jobs. 

I have a queue named "meilisearch" which handles a job which sends API requests to the meilisearch API for indexing data. My Procfile has 3 workers defined. One of them is exclusive to meilisearch with 10 threads:

```ruby
good_job_fast_queue: bundle exec good_job --queues="fast:3"
good_job_meilisearch_queue: bundle exec good_job --queues="meilisearch:10"
good_job_queues: bundle exec good_job --queues="default,fast:5;*:5"
```

All the queues are properly recognized and jobs are queued within those queues. I can see the job when filtering jobs by queue name in the dashboard. I would think with the above settings, good job would run at least 10 jobs in the meiliesarch queue in parallel, but it only ever runs 5 max at a time. 

I have attached a video showing this, with the constantly refreshing the page. I would love to know how i can have goodjob handle a lot more than 5 at a time. 

https://github.com/bensheldon/good_job/assets/271416/bc57ac27-b001-42a6-846f-e79d2d2067cc

I am hosting on heroku, and have a dedicated dyno for all the queues 

<img width="1217" alt="Screenshot 2024-07-11 at 16 29 33" src="https://github.com/bensheldon/good_job/assets/271416/7b092f08-6a59-4d03-a586-9333074ab09b">

**Comment by drale2k** [comment]
I also tried increasing the amount of workers experimentally to 5 (5 dyno in heroku) but i gain absolutely no increase in jobs processed per second. Still stuck at max 5 at the "Running" tab.

<img width="1026" alt="Screenshot 2024-07-11 at 17 08 35" src="https://github.com/bensheldon/good_job/assets/271416/a8e0e238-c765-435f-aef1-e84ec2e8d56f">

**Comment by bensheldon** [comment]
That's weird. 

That you have a `*` queue that is set to 5, and you're only seeing 5 concurrent jobs: can you double check your jobs are enqueuing on the correctly spelled queue?

Also to double check: you're not using concurrency controls?

**Comment by drale2k** [comment]
Hi Ben,

shouldn't * queue that is set to 5 spawn 5 jobs the most at once? To me the weird part is that i have a dedicated meilisearch queue set to 10 threads. Doesn't the amount of threads directly relate to the number of jobs that can concurrently run on that queue? 

I am also surprised that even when showing all queues in the dashboard, there are never more than 5 jobs executed - ever. Even across queues combined. 

> Can you double check your jobs are enqueuing on the correctly spelled queue?

I checked in code (Procfile + queue name for the job) and also they appear under the correct queue in the dashboard as can be seen in the video. 

> Also to double check: you're not using concurrency controls?

For meiliesearch i am not using any concurrency controls. Using the [meilisearch-rails](https://github.com/meilisearch/meilisearch-rails) gem directly which does the job enqueueing. 

I have other jobs with concurrency controls but all of them are only limiting the same job not to be run at the same time for that record id. I don't think this is related in any way?

**Comment by bensheldon** [comment]
Sorry, the video must not have a problem because I only see a looping like 2 seconds zoomed in on the chart. Oddly the dropdown looks like the queue name is `_meilisearch` with a leading underscore or something, like it's cut off. 

Can you try increasing the number of processes on that one worker with a `*` queue and see if you get more than 5 jobs working? I really do think there is a mismatch between the queues the jobs are on and the queues the workers are pulling from (they must match exactly, GoodJob doesn't use `prepend_queue_prefix` or any other queue transformation stuff Active Job offers)

**Comment by drale2k** [comment]
> Oddly the dropdown looks like the queue name is _meilisearch with a leading underscore or something, like it's cut off.

I noticed that but thought it is normal or a goodjob thing. I have no idea why the queues in the dashboard are prefixed like that. Here is a screenshot. It seems to have a pattern of app_name + env + queue_name. I wonder where this naming is coming from. So in other words, my Procfile has to change?

From:
good_job_meilisearch_queue: bundle exec good_job --queues="meilisearch:10"
To:
good_job_meilisearch_queue: bundle exec good_job --queues="podsentry_production_meilisearch:10"

I will try that straight way. Would still love to know why my queues are named like this o.O

**Comment by bensheldon** [comment]
That prefixing isn't coming from GoodJob. WEIRD! Do a search on your code base for `queue_name_prefix` (oops, got that name wrong in my previous comment). 

I think we're getting closer to the problem 🤞

**Comment by drale2k** [comment]
Oh my, that was the solution and the prefix is coming from my env files 🤦‍♂️

`config.active_job.queue_name_prefix = "podsentry_production"` 

Thank you very much 🙏🏻

On a side note, 1 job should be running on 1 thread correct? Meaning if i want to run 100 jobs simultaneously, i would have 1 worker with 100 threads - or would i rather have multiple workers handling the same queue with less threads? 

Would you recommend one over the other?

good_job_meilisearch_queue: bundle exec good_job --queues="podsentry_production_meilisearch:100"

**Comment by bensheldon** [comment]
100 threads is much too many. You'll probably max out at ~10-20 threads before thread/GVL lock contention gives diminishing returns (jobs usually are better able to have more threads than Puma, but not by a lot). 

So if you want 100 concurrent jobs, I'd split that across at least 10 separate processes each with 10 threads.
