### ISSUE TITLE
Could not find the inverse association for execution (:discrete_executions in GoodJob::Execution)

### ISSUE THREAD

**Issue by tom-kuca** [bensheldon/good_job#1424]
After recent update in my application, `good_job start` prints 
`GoodJob error: ActiveRecord::InverseOfAssociationNotFoundError: Could not find the inverse association for execution (:discrete_executions in GoodJob::Execution)` with a [backtrace](https://gist.github.com/tom-kuca/5c91df6c47cee0e08672f57aca1c7d86) multiple times per second and fails to do anything else.

I checked the sources, the relation `discrete_executions` is defined only for `Job`:

https://github.com/bensheldon/good_job/blob/2dcb518f5e12b14e8cc4d11c3b4edde8dd10a94f/app/models/good_job/job.rb#L23

There are two associations in the project that have `discrete_executions` listed as inverse association, they are in `DiscreteExecution`:

https://github.com/bensheldon/good_job/blob/2dcb518f5e12b14e8cc4d11c3b4edde8dd10a94f/app/models/good_job/discrete_execution.rb#L10-L11

The first one looks suspicious to me. Should it be there? `GoodJob::Execution` doesn't have primary key `active_job_id`, association `discrete_executions` is not defined for Execution.

I noticed the error after I updated good_job from `4.0.2` to `4.0.3`. I updated other gems too.

**Comment by bensheldon** [comment]
oops! You're correct that `DiscreteExecution` should _not_ `belongs_to` Execution (in GoodJob v4 a DiscreteExecution _is_ an Execution).

I can fix that. Though odd nothing else has caught that until now (and I'm definitely running it in production on several of my apps) 🤔

**Comment by tom-kuca** [comment]
Wow, that was fast, thanks!

My app is running on Rails 7.1.0.rc2, maybe it's related to that? If you are interested in, I can try to pinpoint what change triggered the error.
