### ISSUE TITLE
RuntimeError when running good_job executable after updating v3 -> v4

### ISSUE THREAD

**Issue by maxim** [bensheldon/good_job#1445]
Having updated from v3 to v4, launching `bin/good_job start` spams this error repeatedly in the logs and won't start:

```
ERROR -- : [GoodJob] Notifier errored: RuntimeError: Undeclared attribute type for enum 'lock_type'. Enums must be backed by a database column or declared with an explicit type via `attribute`.
```

This behavior is the same when running directly on MacOS, and in Ruby-based Docker-container.

Here's the output of `bin/rails g good_job:update`

```
❯ bin/rails g good_job:update
        skip  db/migrate/20240719202056_create_good_jobs.rb
```

So no new migrations are being added for me to run.

Any idea what it might be?

(Ruby 3.3.4, Rails 7.1.3.4, GoodJob v4.1)

**Comment by bensheldon** [comment]
hmm. I'm guessing that all of the v3.99 migrations weren't applied when upgrading. You'll need to set your version to v3.99, then run `rails g good_job:update` to generate the migrations.

Migrations get squashed down every major GoodJob version increase; that's why you're not seeing new ones.

**Comment by maxim** [comment]
Ahhh, that caught me off guard. Reading docs, I thought that 3.99 is an optional stepping stone (you even provide a sql query to check v4 readiness without using 3.99), but turns out it's not optional. Also possible that I forgot to run an update on a prior minor version. 🤔 (And it worked fine somehow.)

Since it's rare that you must go through any intermediate versions for updates, could be a good idea to stress it in README "Do not skip the latest minor version, it could have critical db migrations that you will miss if you skip over."

That's actually an interesting way of dealing with the migration puzzle. Another option might be to only squash migrations 1 major version ago. For example, when transitioning to 3, squash everything in 1. When 4, squash up to 2. This could make consecutive major version jumps a little smoother, but of course not a foolproof solution.

**Comment by bensheldon** [comment]
Sorry about that. You're not the first to overlook it. I'll try to highlight it some more.

> Another option might be to only squash migrations 1 major version ago.

oooh, that is a really good suggestion! 🤔

**Comment by maxim** [comment]
No apology needed, you're running this free oss more thoughtfully than most I've seen.
