### ISSUE TITLE
Searching for an integer type argument (on the dashboard) does not yeild any results

### ISSUE THREAD

**Issue by swaathi** [bensheldon/good_job#1458]
I encountered an issue while searching for jobs that have two parameters: an integer and a string. When performing a search using the string parameter, the results are accurate. However, no results are returned when searching using the integer parameter.

Additionally, the current test specifications only cover searches with the string parameter, not the integer parameter.

https://github.com/bensheldon/good_job/blob/b0c9707b487652d69264cb145ec8ec9c2aa74263/spec/app/models/concerns/good_job/filterable_spec.rb#L21-L23

Screenshots:
Accurate results when searching with a string query
<img width="1436" alt="Screenshot 2024-08-05 at 6 11 21 PM" src="https://github.com/user-attachments/assets/42a08f5d-0372-410a-932a-cfc5a7aa4671">

Nothing when searching for an integer
<img width="1440" alt="Screenshot 2024-08-05 at 6 10 20 PM" src="https://github.com/user-attachments/assets/4571932d-ebcd-4dab-ad73-0159bbef93aa">

**Comment by bensheldon** [comment]
Nuts! Thanks for looking into the code and finding that scenario isn't tested. GoodJob uses Postgres fulltext search, which I'm not an expert in. Here's where the search happens: 

https://github.com/bensheldon/good_job/blob/b0c9707b487652d69264cb145ec8ec9c2aa74263/app/models/concerns/good_job/filterable.rb#L38

**Comment by djalmaaraujo** [comment]
I use active record IDs as the argument for Jobs, so it's impossible to search executed jobs later because of this problem.

**Comment by bensheldon** [comment]
Thanks for the ping on this. I think I have something that works in #1504
