### ISSUE TITLE
`perform_limit` and `perform_throttle` don't work both

### ISSUE THREAD

**Issue by doits** [bensheldon/good_job#1469]
Can it be that there is a bug when `perform_limit` and `perform_throttle` are *both* specified so that `perform_throttle` is ignored? Isn't [this "next" at line 153](https://github.com/bensheldon/good_job/blob/59c3300bde2b64bfc135e7f37fb93a59db7db899/lib/good_job/active_job_extensions/concurrency.rb#L153) skipping throttling if the limit isn't reached, which means you cannot have both?

https://github.com/bensheldon/good_job/blob/59c3300bde2b64bfc135e7f37fb93a59db7db899/lib/good_job/active_job_extensions/concurrency.rb#L146-L156

Shouldn't it only skip throttling if it is exceeded already?

```rb
   unless allowed_active_job_ids.include?(job.job_id)
     exceeded = :limit  
     next 
  end
```

_Originally posted by @doits in https://github.com/bensheldon/good_job/issues/1353#issuecomment-2293881345_

**Comment by doits** [comment]
I think this bug was introduced by refactoring in https://github.com/bensheldon/good_job/pull/1439

**Comment by bensheldon** [comment]
Thanks for opening this issue. I'm staring at it for a couple minutes now and I think you're correct that the current logic is wrong. We want to `next`/jump only if the job should be rescheduled, and continue testing the following conditions otherwise.

Is this a PR you'd be comfortable making?

**Comment by doits** [comment]
sure, I'll add a spec do a PR

**Comment by doits** [comment]
Please see https://github.com/bensheldon/good_job/pull/1470 for the PR

**Comment by bensheldon** [comment]
Thank you! This fix has been released: https://github.com/bensheldon/good_job/releases/tag/v4.2.0
