### ISSUE TITLE
Rails 7.2.1 breaks enqueuing without enqueue_after_transaction_commit? method on queue adapter

### ISSUE THREAD

**Issue by tostart-pickagreatname** [bensheldon/good_job#1477]
Rails 7.2.1 requires that queues implement the enqueue_after_transaction_commit? method.

The impact of not having this method and upgrading to 7.2.1 is that all job enqueuing fails.

This method is described in https://github.com/rails/rails/commit/e922c59207c406d51541622690737783e0ec338e

This commit also introduced ActiveJob::QueueAdapters::AbstractAdapter which all rails queues now inherit from.

In the future, the best path would be to have the adapter inherit from AbstractAdapter, to avoid new methods breaking job enqueuing.

At this time, however, its default behaviour could simply be implemented.

**Comment by bensheldon** [comment]
I think GoodJob should be ok. `enqueue_after_transaction_commit?` was introduced in [GoodJob v3.7.4](https://github.com/bensheldon/good_job/releases/tag/v3.27.4).

**Comment by bensheldon** [comment]
Also, maybe that setting will be reverted eventually (discussion in these comments): https://github.com/rails/rails/pull/52659

**Comment by tostart-pickagreatname** [comment]
Oh I see the method now, thank you! I'll close this issue.

**Comment by buncis** [comment]
@bensheldon I use 3.25

and got this 

```
Failed enqueuing ActionMailer::MailDeliveryJob to GoodJob(default): NoMethodError (undefined method `enqueue_after_transaction_commit?' for an instance of ActiveJob::QueueAdapters::GoodJobAdapter)
↳ app/models/user.rb:59:in `send_devise_notification'
app/models/user.rb:59:in `send_devise_notification': undefined method `enqueue_after_transaction_commit?' for an instance of ActiveJob::QueueAdapters::GoodJobAdapter (NoMethodError)

          queue_adapter.enqueue_after_transaction_commit?
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from (myapp):4:in `<main>'
```

**Comment by bensheldon** [comment]
@buncis whoops! I just edited my content. Sorry for the confusion! ➡ `v3.27.4` ⬅
