### ISSUE TITLE
GoodJob Timezone Day Light Savings

### ISSUE THREAD

**Issue by josueadelima** [bensheldon/good_job#1480]
Hello, sorry for asking here, I didn't find another place to ask and any documentation about this.

I have a use case which I'm not fully sure is covered by GoodJob:

Basically I have a cron job that needs to run every day at `6:00 PM ET`, so I use an expression for the cron like this: `"0 18 * * * America/New_York" `. `Fugit` is able to parse this and assign the right timezone (I can see it when I do `GoodJob::CronEntry.all`), however I'm wondering what is going to happen when `Day Light Savings` occurs, is it going to run at 6:00 PM ET or it is going to get delayed 1 hour or viceversa? 

Thanks in advance.

**Comment by bensheldon** [comment]
Thanks for asking! GoodJob uses `Fugit#next_at` to schedule when to enqueue the job next:

https://github.com/bensheldon/good_job/blob/9a781889eb6c66d713695352e4bfd509f96bc70b/app/models/good_job/cron_entry.rb#L65

So maybe this is more of a Fugit question, but I'm like 90% certain that Fugit works across time zone boundaries.

**Comment by josueadelima** [comment]
Thanks for your answer, I know Fugit works perfectly when returning the right time. My question is, if each time the cron job is going to be scheduled it will use Fugit#next_time. 

To be more clear, does Fugit#next_time gets called when Good Job initialize or it is called on each cron run, because if it is called only during initialization, then I will need to redeploy after Day Light Savings.

I hope I made my self clear.

Thanks

**Comment by bensheldon** [comment]
Ah, I think I understand your question. 

This is called after every scheduled task (that enqueues the job) to schedule the next task ie "each cron run":

https://github.com/bensheldon/good_job/blob/9a781889eb6c66d713695352e4bfd509f96bc70b/lib/good_job/cron_manager.rb#L84-L89

**Comment by josueadelima** [comment]
Great! Thank you! I will review the code.
