### ISSUE TITLE
Multiple same values in cron_keys_disabled, cron_keys_enabled in good_job_settings table

### ISSUE THREAD

**Issue by falegk** [bensheldon/good_job#1490]
Hello all,

I'm using the .disable, .enable cron entries from the API and I realized that if I call the .disable multiple times the value array fills with multiple same values.
Of course, it doesn't affect the functionality anywhere from what I tried.

Example:

```
GoodJob::CronEntry.find("heartbeat_schedules").disable
=> good_job_settings table has: cron_keys_enabled, ["heartbeat_schedules"]

# call it again
GoodJob::CronEntry.find("heartbeat_schedules").disable
=> good_job_settings table has: cron_keys_enabled, ["heartbeat_schedules", "heartbeat_schedules"]
```
![Screenshot 2024-09-18 at 14 15 51](https://github.com/user-attachments/assets/b6009c3a-2c25-4f8a-94c2-aa02988ff830)

**Comment by Earlopain** [comment]
There's some basic logic which is supposed to prevent this: https://github.com/bensheldon/good_job/pull/1289. Just making sure, what's your good_job version? Apparently this got changed in [3.27.0](https://github.com/bensheldon/good_job/releases/tag/v3.27.0)

**Comment by falegk** [comment]
Hey @Earlopain 

the version is 4.2.0 (updated from previous major versions.)
I can spend more time trying to find out why this happens (check good_jobs code), maybe on the weekend cause my program is full this week.

**Comment by Earlopain** [comment]
PR welcome if you want to do some investigating, and take your time (:
But no worries if you don't want to, let me know if I should take a look instead.

**Comment by mohammednasser-32** [comment]
Heyy, I found this inactive for a while so I jumped into it :sweat_smile: 
Created a [PR](https://github.com/bensheldon/good_job/pull/1498) with the reason of the issue in the description
