### ISSUE TITLE
scheduled_at not respecting given timezone

### ISSUE THREAD

**Issue by mbajur** [bensheldon/good_job#1491]
Hey! I'm trying to schedule a job for a time in a specific timezone. Here is the code I'm using:

```ruby
time = ActiveSupport::TimeZone['Warsaw'].parse('12 Aug 2024 12:00')
# => Mon, 12 Aug 2024 12:00:00.000000000 CEST +02:00
Campaigns::SendJob.set(wait_until: time).perform_later
GoodJob::Job.last.scheduled_at
# => Mon, 22 Aug 2024 12:00:00.000000000 UTC +00:00
```

Am i misunderstanding something in here? Shouldn't these two timestamps match? I'm on `GJ 3.27.4` (EDIT: I just updated to `4.3.0` and it's still happening)

**Comment by bensheldon** [comment]
Thanks for opening this issue! Those timezones sure look different to me.

I can do some exploratory testing to see if I can reproduce it. The value gets passed through Active Job to GoodJob to the database and back again, so I’ll have to track down where it seems like some of that time context is being dropped.

**Comment by bensheldon** [comment]
What version of Rails are you on?

**Comment by mbajur** [comment]
Thanks for rapid reply - I'm on Rails 7.0.8 :)

**Comment by mbajur** [comment]
Ok, i have absolutely no idea what's going on in here but i copied your test to my job specs file and it also passes all green. Timezones in programming is something that always bends my mind bad so let me play with that around a bit more and let me get back to you once i know anything more.
