### ISSUE TITLE
Inline adapter doesn't retry jobs that throw a retryable error

### ISSUE THREAD

**Issue by thomasschafer** [bensheldon/good_job#1497]
Given the following job:

```ruby
class MyJob < ApplicationJob
  JobNotComplete = Class.new(StandardError)
  retry_on(JobNotComplete)

  def perform(job_id:)
    puts "MyJob: #{job_id}"

    if job_id >= 10
      puts "Succeeded"
      return
    end

    raise JobNotComplete if job_id == 2

    MyJob.perform_later(job_id: job_id + 1)
  end
end
```

And a simple test like the following:

```ruby
require 'rails_helper'

describe MyJob do
  it "Runs successfully" do
    described_class.perform_later(job_id: 0)
  end
end
```

When `bundle exec rspec` is run, the following will happen:

```
$ bundle exec rspec
MyJob: 0
MyJob: 1
MyJob: 2
.

Finished in 0.18838 seconds (files took 0.99919 seconds to load)
1 example, 0 failures
```

This is occurring because `JobNotComplete` is being thrown from `MyJob`, which is a retriable error, but the error is not being retried, and the spec incorrectly passes.

If `retry_on(JobNotComplete)` is commented out, we see the following:

```
$ bundle exec rspec
MyJob: 0
MyJob: 1
MyJob: 2
F

Failures:

  1) MyJob Runs successfully
     Failure/Error: raise JobNotComplete if job_id == 2

     MyJob::JobNotComplete:
       MyJob::JobNotComplete
     # ./app/jobs/my_job.rb:13:in `perform'
     # ./app/jobs/my_job.rb:15:in `perform'
     # ./app/jobs/my_job.rb:15:in `perform'
     # ./spec/jobs/my_job_spec.rb:5:in `block (2 levels) in <top (required)>'

Finished in 0.17487 seconds (files took 1.03 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/jobs/my_job_spec.rb:4 # MyJob Runs successfully
```

If the error is not thrown, all jobs succeed:

```
$ bundle exec rspec
MyJob: 0
MyJob: 1
MyJob: 2
MyJob: 3
MyJob: 4
MyJob: 5
MyJob: 6
MyJob: 7
MyJob: 8
MyJob: 9
MyJob: 10
Succeeded
.

Finished in 0.22215 seconds (files took 1.01 seconds to load)
1 example, 0 failures
```

I created a repo [here](https://github.com/thomasschafer/goodjob-inline-adapter-issue) with a complete Rails application showing the issue, if that helps at all.

**Comment by bensheldon** [comment]
I'm fairly certain this is because `retry_on`'s default wait is 3 seconds:

https://github.com/rails/rails/blob/0d30e84878223df68efda3b0e1741611d9682a45/activejob/lib/active_job/exceptions.rb#L62-L62

If you want it to retry immediately and thus inline, you can use `retry_on JobNotComplete, wait: 0`

**Comment by thomasschafer** [comment]
> I'm fairly certain this is because `retry_on`'s default wait is 3 seconds:
> 
> https://github.com/rails/rails/blob/0d30e84878223df68efda3b0e1741611d9682a45/activejob/lib/active_job/exceptions.rb#L62-L62
> 
> If you want it to retry immediately and thus inline, you can use `retry_on JobNotComplete, wait: 0`

Thanks for getting back to me - that makes sense, so something like

```ruby
retry_on(
  JobNotComplete,
  wait: Rails.env.test? ? 0 : interval,
)
```

should work when I want a non-zero wait. Appreciate your help 🙌

**Comment by bensheldon** [comment]
Glad I could help! Just cause I'm curious, could you say more about the kind of tests you are writing? I generally would say it's not necessary to specifically test `retry_on` because it's declarative and you'd just be testing the framework.

**Comment by thomasschafer** [comment]
> Glad I could help! Just cause I'm curious, could you say more about the kind of tests you are writing? I generally would say it's not necessary to specifically test `retry_on` because it's declarative and you'd just be testing the framework.

I have a bunch of jobs that run sequentially, and some make external requests to kick off long-running processes which subsequent jobs poll to check the status of before continuing. This is why the job has the retriable `JobNotComplete` error with a non-zero wait as there's no point polling continuously given that the external processes take a long time. I'm writing some tests to verify the behaviour of the sequence of jobs, which is where I was running in to the issue with the job not being retried - I'm not testing `retry_on`, I just want to have a non-zero wait in production while also being able to run the jobs with the inline runner during tests.
