### ISSUE TITLE
Modify error color for Running tab when a job has 1 attempt

### ISSUE THREAD

**Issue by Wittiest** [bensheldon/good_job#1518]
## Problem
When a job is running and has 1 attempt, the badge with Attempts has an error color
<img width="1860" alt="Screenshot 2024-10-14 at 7 45 38 AM" src="https://github.com/user-attachments/assets/885f1cce-3c06-49a3-91f1-64f8fad70092">

## Proposed Solution
For this tab when the attempt count is equal to 1, show a neutral gray color like the Succeeded tab

**Comment by bensheldon** [comment]
good catch, that makes sense to me to not have the error color. I imagine we'd have to thread down the context into that row which sounds messy, but probably worth it.

**Comment by bensheldon** [comment]
oh no, it's much easier than that. This logic with the job state just needs to be a little more complex:

https://github.com/bensheldon/good_job/blob/ecf6df74d7aa8b5d480a6c50ec0e5ce84f90d01a/app/views/good_job/jobs/_table.erb#L87C1-L98C26

Is that a PR you'd be able to make?

**Comment by Wittiest** [comment]
@bensheldon I am wondering if we have any guarantees from good_job that would make the implementation cleaner.

Specifically, will there **always** be data inside of `recent_error` or another field if a job has experienced a failed execution before? If so, we could simply change the logic to be:
```ruby
<% if job.recent_error && job.status != :finished %>
# Show span
```

If there isn't something simple like that, this slightly-messy logic would work to do the following:
- For :running jobs, only show error span if executions_count > 1
- For :succeeded jobs, never show error span
- For all other statuses, show error_span if executions_count > 0
```ruby
<% show_error = (job.status == :running && job.executions_count > 1) || (![:finished, :running].include?(job.status) && job.executions_count > 0) %>
<% if show_error %>
   <%= tag.span job.executions_count, class: "badge rounded-pill bg-danger",
        data: {
          bs_toggle: "popover",
          bs_trigger: "hover focus click",
          bs_placement: "bottom",
          bs_content: job.recent_error,
        }
      %>
  <% else %>
    <span class="badge bg-secondary rounded-pill"><%= job.executions_count %></span>
  <% end %>
```

**Comment by bensheldon** [comment]
> Specifically, will there always be data inside of recent_error or another field if a job has experienced a failed execution before?

Good call! Yes, I think you're correct that this could more simply be (use `job.error` so it doesn't access any associated `executions`): 

```ruby
<% if job.error && job.status != :finished %>
# Show span
```

...also just fyi, I think `recent_error `is vestigial of GoodJob <v4 and should be deprecated and aliased to `error`. It used to be necessary because a `Job` _was_ simply the most recent `Execution` but that's no longer the case and previous error from a job is not cleared when the job is re-executed.
