### ISSUE TITLE
Can't load Dashboard

### ISSUE THREAD

**Issue by alienxp03** [bensheldon/good_job#1532]
I can't seems to load my main dashboard located at `/jobs` due to it's taking too long to load. Previously I had 3.5millions job. And now it's down to 700k after I manually run `cleanup_preserved_jobs`. However the issue still persist. Is there any configuration that I need to be aware of. My current config is pretty simple, just enabled cron and setup few crons to run every few minutes.

![Screenshot 2024-10-31 at 9 31 22 AM](https://github.com/user-attachments/assets/fd07912f-b0ed-4414-bc44-a37edb906bf1)

![Screenshot 2024-10-31 at 9 54 43 AM](https://github.com/user-attachments/assets/35e4b3d2-9b1e-48ce-aeb1-b12941e9fe3f)

GoodJob Version: `3.99`

**Comment by bensheldon** [comment]
Hmmm. Could you try running `REINDEX TABLE good_jobs` and `REINDEX TABLE good_job_executions` on your database. There's been [reports that helps](https://github.com/bensheldon/good_job/issues/896#issuecomment-1792587341).

I also wonder if the counts in counts in the Dashboard need to _all_ be moved async. This was done to some of the tabs, but not the dropdowns or the chart (#1231)

**Comment by alienxp03** [comment]
Thanks for the tips Ben. Unfortunately I've moved away from using GoodJob for now, so won't be able to confirm the suggested solution 😅

**Comment by bensheldon** [comment]
No worries 💖
