### ISSUE TITLE
Lower Ruby Thread priority for jobs by default when running in Async mode

### ISSUE THREAD

**Issue by bensheldon** [bensheldon/good_job#1554]
It's possible for GoodJob to introduce latency into web requests when running in async mode, especially if the GoodJob job is heavily CPU-bound, as can happen, for example, when rendering out views for Turbo broadcasts

Thread scheduling and priority seems to be a less-than-well understood area of Ruby

- https://ivoanjo.me/blog/2023/07/23/understanding-the-ruby-global-vm-lock-by-observing-it/ goes into a lot of depth
  - Some related discussion on Reddit with familiar user names: https://www.reddit.com/r/ruby/comments/16xsjxl/threads_vs_fibers/ 
- GitLab has an open issue about [setting job priority based on workload type](https://gitlab.com/gitlab-org/gitlab/-/issues/35577). It seems like they've categorized their jobs based on whether they are CPU bound, but not yet set a Thread priority
- The Rails issue about setting default Puma thread count which sorta glances off this topic: https://github.com/rails/rails/issues/50450
- An issue opened on Rails this month about configuring the Thread Quantum separately from priority: https://bugs.ruby-lang.org/issues/20861
  
## An attempt to explain

Ruby threads are OS threads; and OS threads are preemptive, meaning the OS is entirely responsible for switching execution between threads. _But,_ because of the GVL (Global VM Lock), the Ruby VM _actually_ has a say in when that switching happens.

The Ruby VM has a default thread "Quantum" of `100ms`. That means that the Ruby VM will grant a thread the GVL for a maximum of 100ms before the Ruby VM takes it back and gives it to another thread. That is 100ms of Ruby processing _unless_ the thread goes into IO or sleeps or otherwise the thread releases the GVL on its own.

This is an ok way to balance execution across threads, unless those thread workloads are wildly different (homogenous tasks are always better!)

The dreaded "Tail Latency" of multithreaded behavior can happen, related to the Ruby Thread Quantum, when you have what might otherwise be a very short request, for example:

- A request that could be 10ms because it's making ten 1ms calls to Memcached/Redis to fetch some cached values and then returns them (IO-bound Thread)

...but when it's running in a thread next to:

- A request that takes 1 second and largely spends its time doing string manipulation, for example a background thread that is taking a bunch of complex hashes and arrays and serializing them into a payload to send to a metrics server. Or rendering slow/big/complex views for Turbo Broadcasts (CPU-bound Thread)

...then the CPU-bound thread will be very greedy with holding the GVL and it will look like

1. IO-bound Thread: Starts 1ms network request and releases GVL
2. CPU-bound Thread: Does 100ms of work on the CPU before the GVL is taken back
3. IO-bound Thread: Gets GVL back and starts next 1ms network request and releases GVL
4. CPU-bound Thread: Does 100ms of work on the CPU before the GVL is taken back
....

See where this is going? The IO-bound thread is taking waaaaaaay longer than the 10ms it could ideally take if the other thread wasn't so greedy with the GVL.

I wrote a quick script to simulate this (starting with the script Aaron Patterson wrote in the Ruby issue linked above). As you can see the IO-bound Thread took more than 1 second to complete, more than the 10ms we expected! 

```bash
❯ THREAD_PRIORITY=0 vernier run --interval 1 -- ruby script.rb
starting profiler with interval 1 and allocation interval 0
fib(36) took 1.3904600000241771 seconds
io_total: 1.1013240000465885 seconds
cpu_total: 1.405722999945283 seconds
#<Vernier::Result 6.421998 seconds, 3 threads, 193236 samples, 268 unique>
written to /var/folders/5y/9zpy_s_n6sd6vv3wr62qvp9m0000gn/T/profile20241206-32191-a99iaa.vernier.json.gz
```

And here's what that looks like in Vernier, where you can see the GVL switch back to the IO-bound Thread every 100ms to do the teensy amount of work before handing back to the CPU-bound Thread:

![Image](https://github.com/user-attachments/assets/92c6aa2c-1b49-44ae-9fcb-afd21674d34e)

Lowering the thread priority, in this case to -3, causes the IO thread to have a much more expected value without hugely affecting the CPU-bound thread:

```
❯ THREAD_PRIORITY=-3 vernier run --interval 1 -- ruby script.rb
starting profiler with interval 1 and allocation interval 0
fib(36) took 1.411104999948293 seconds
io_total: 0.21908700000494719 seconds
cpu_total: 1.4277810000348836 seconds
#<Vernier::Result 6.518035 seconds, 3 threads, 197646 samples, 295 unique>
written to /var/folders/5y/9zpy_s_n6sd6vv3wr62qvp9m0000gn/T/profile20241206-32053-u4zn6o.vernier.json.gz
```

<details>
<summary>Example script
</summary>

```ruby
#
# THREAD_PRIORITY=-3 vernier run --interval 1 -- ruby script.rb
#

def measure
  x = Process.clock_gettime(Process::CLOCK_MONOTONIC)
  yield
  Process.clock_gettime(Process::CLOCK_MONOTONIC) - x
end

def fib(n)
  if n < 2
    n
  else
    fib(n - 2) + fib(n - 1)
  end
end

# find fib that takes ~1 second
fib_i = 50.times.find { |i| measure { fib(i) } >= 1 }
sleep_i = measure { fib(fib_i) }

puts "fib(#{fib_i}) took #{sleep_i} seconds"

# Simulate a thread that makes ten 1ms IO calls in quick succession
io_thread = Thread.new {
  Thread.current.name = "io_thread"
  io_total = measure {
    10.times { sleep 0.001 }
  }
  puts "io_total: #{io_total} seconds"
}
Thread.pass

# Simulate a thread that makes a CPU-bound call for 1 second
cpu_thread = Thread.new {
  Thread.current.name = "cpu_thread"
  Thread.current.priority = ENV['THREAD_PRIORITY'].to_i if ENV['THREAD_PRIORITY']
  cpu_total = measure {
    fib(fib_i)
  }
  puts "cpu_total: #{cpu_total} seconds"
}
Thread.pass

io_thread.join
cpu_thread.join
```

</details>

## How does Thread Priority work:

**Ruby Thread Priority** "is just hint for Ruby thread scheduler. It may be ignored on some platform." But now that that's out of the way, C Ruby's thread priority is calculated as:

[The number of bit-shifts of the default Thread Quantum](https://github.com/ruby/ruby/blob/bb71a128eb6e901d3d7deb895971a6706eb7110d/thread.c#L2264) (100ms). Meaning either multiplying (if positive) or dividing (if negative) by powers of 2.

| Thread#priority | Calculation   | Result |
|-----------------|---------------|--------|
| -N              | 100ms / (2^N) |        |
| -3              | 100ms / (2^3) | 12.5ms |
| -2              | 100ms / (2^2) | 25ms   |
| -1              | 100ms / (2^1) | 50ms   |
| 0               | 100ms         | 100ms  |
| 1               | 100ms * (2^1) | 200ms  |
| 2               | 100ms * (2^2) | 400ms  |
| 3               | 100ms * (2^3) | 800ms  |
| N               | 100ms * (2^N) |        |

This makes sense because a lower priority (negative) should release its GVL more frequently (and thus be less greedy).

## What does this mean for GoodJob

When running jobs async, in the same process as web requests, we should probably lower the priority. Maybe to `-3` ?

I dunno if we should allow the priority to be set directly via config or just have a configuration setting like `lower_thread_priority = true` with a default based on the execution mode that _could_ be overriden.

**Comment by mperham** [comment]
Thanks for doing this research Ben. Lower priority seems to make sense when embedding in another process.

**Comment by bensheldon** [comment]
Chatting with @jhawthorn, CRuby can never go higher/lower than -3 to 3.

The priority calculation is: 12.5ms, but then that gets rounded down to 12ms, but then the `tick` is every 10ms, so in practice the minimum quantum via priority is 20ms.
