### ISSUE TITLE
Attaching metadata to jobs

### ISSUE THREAD

**Issue by olivier-thatch** [bensheldon/good_job#1558]
I spent some time looking into how feasible it would be to integrate Sentry's [queue monitoring](https://docs.sentry.io/product/insights/backend/queue-monitoring/) feature in GoodJob.

Simply monitoring how much time passes between the time a job is enqueued and the time it is picked up by a worker is probably doable using the ActiveJob `around_enqueue` and `around_perform` callbacks. I need to do some more testing for things such as `perform_now` vs. `perform_later`, job retries, etc. but it sounds easy enough.

One thing that doesn't so easy with GoodJob's current state is [trace propagation](https://docs.sentry.io/platforms/ruby/tracing/trace-propagation/). This is a feature that allows Sentry to group events across different services. E.g. if a web request enqueues a job and the job is then picked up by a worker, with trace propagation Sentry will group the 2 events under the same trace, which is very useful for debugging.

This feature works by passing a specific set of headers between events. Sentry's Ruby gem provides an integration for Sidekiq which takes advantage of this:
- when a job is enqueued, the trace propagation headers are included ([code](https://github.com/getsentry/sentry-ruby/blob/a9b3687d3ce5d00d5586ef3fe76ae8233d8405f1/sentry-sidekiq/lib/sentry/sidekiq/sentry_context_middleware.rb#L91))
- when a job is picked up by a worker, the trace propagation headers are read and used to "continue" the existing Sentry transaction ([code](https://github.com/getsentry/sentry-ruby/blob/a9b3687d3ce5d00d5586ef3fe76ae8233d8405f1/sentry-sidekiq/lib/sentry/sidekiq/sentry_context_middleware.rb#L38))

This works for Sidekiq because `job` is just an arbitrary hash that gets stored in Redis.

I tried to achieve the same thing with GoodJob, but unfortunately I couldn't find a good way to store the trace propagation headers. I hacked something by storing the headers inside `serialized_params` then removing them before the job is actually called, but this is obviously a terrible and unreliable hack.

Anyway, the above was just for context. What do you think of the idea of adding a `metadata` column to GoodJob's job model? Ideally a JSONB column, though just text would work too.

**Comment by olivier-thatch** [comment]
That looks like it'd work! I'll give it a try and report back. Thanks for the quick reply as always, Ben :)

**Comment by olivier-thatch** [comment]
I was able to achieve what I was after using your suggestion. Thanks again!

**Comment by ScotterC** [comment]
@olivier-thatch I would love to incorporate this. Would you mind sharing your final concern/module?

**Comment by olivier-thatch** [comment]
@ScotterC I haven't had a chance to work on this as much as I wanted, but I can share this: https://gist.github.com/olivier-thatch/6baf7bf12b0f4862e53a4c333e3570d9

I did some light testing and it appears to work, but here are a few things I haven't had a chance to look into:
* behavior when using `perform_now` (i.e. executing jobs inline without enqueuing)
    * I'm pretty sure this would emit a `queue.process` transaction without a matching `queue.publish`
 * behavior when a job fails and is retried
     * I think each attempt will emit a `queue.process` transaction and the latency will increase each time with the retry delay
 * more importantly, I realized that sentry-rails already has an ActiveJob integration that does some of this (https://github.com/getsentry/sentry-ruby/blob/master/sentry-rails/lib/sentry/rails/active_job.rb) so I was hoping to submit a PR to augment it, but haven't had a chance to yet

**Comment by ScotterC** [comment]
👏  thanks for this! It looks like a lot of hard won knowledge to build on.

That active job integration exists but if it's on by default then it doesn't seem to be setting up any queuing information for me so something's off. I can't seem to find any documentation about it on their site - unless somehow it falls under the cron job monitoring.

**Comment by olivier-thatch** [comment]
> That active job integration exists but if it's on by default then it doesn't seem to be setting up any queuing information for me so something's off. 

It should be active by default as it's loaded from one of sentry-rails' railties. You can check if it's active with this snippet:
```ruby
ActiveJob::Base.ancestors.include?(Sentry::Rails::ActiveJobExtensions)
```

but you're right it doesn't emit anything when a job is _enqueued_. It only emits a `queue.active_job` event when a job is _performed_.

In contrast, the concern class I shared in a gist will emit two different events:
1. `queue.publish` when a job is enqueued
2. `queue.process` when a job is performed

(Those are the same names that are used in [Sentry's documentation](https://docs.sentry.io/platforms/ruby/tracing/instrumentation/custom-instrumentation/queues-module/) as well as sentry-rails' [Sidekiq integration](https://github.com/getsentry/sentry-ruby/blob/a9b3687d3ce5d00d5586ef3fe76ae8233d8405f1/sentry-sidekiq/lib/sentry/sidekiq/sentry_context_middleware.rb).)

**Comment by renchap** [comment]
Thats very interesting, thanks for sharing that. I opened an issue in the Sentry repo to add GoodJob support, and they seem interested. Maybe you could contribute it upstream? https://github.com/getsentry/sentry-ruby/issues/2594
