### ISSUE TITLE
JRuby Support

### ISSUE THREAD

**Issue by tedhexaflow** [bensheldon/good_job#160]
Hello,

Is there any plan to support for JRuby?

Many Thanks.

Ted

**Comment by bensheldon** [comment]
@tedhexaflow What version of JRuby are you using? I'll add it to the testing matrix.

Theoretically GoodJob should be compatible with JRuby (ConcurrentRuby is compatible), but I don't have any experience with jRuby.

**Comment by tedhexaflow** [comment]
Hi @bensheldon,
 
I'm currently using 9.2.12.0 and the latest one is 9.2.13.0.

We will need to replace 'pg' gems with 'activerecord-jdbcpostgresql-adapter' for JRuby.

Thanks.
Ted

**Comment by bensheldon** [comment]
I'm close to having a JRuby-compatible release of GoodJob in #167. 

One wrinkle is that `activerecord-jdbcpostgresql-adapter` does not support Postgres LISTEN notifications; it does not have an analog of `pg` gem's `#wait_for_notify`,. GoodJob continues working with polling. I looked at how the `que` gem works: Que originally used the `jruby-pg` gem, but has since [dropped support for jruby](https://github.com/que-rb/que/commit/0845f4243bd3ee306db5d6ecf9208fbac5429001#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR25): "JRuby support has been dropped. It will be reintroduced whenever the jruby-pg gem is production-ready."

**Comment by tedhexaflow** [comment]
Hi Ben,

Thank you so much for the update. 🙏

**Comment by bensheldon** [comment]
@tedhexaflow JRuby support was just released in GoodJob `v1.4.0` 🎉  

Please open up any issues you run into or add them to this thread.

**Comment by tedhexaflow** [comment]
Hi Ben,

Thank you so much for spending your holiday time.
I'll arrange for the testing with our product and will keep you update.

Thanks, and wish you a Happy New Year.

**Comment by tedhexaflow** [comment]
Hi Ben,

I just had a chance to test and all 3 adapter options are working fine in development mode.
But for production mode, the server cannot be started (for all adapter options).
Below is the error message. Many thanks.

There is a file with the name "migration.rb.erb" exist in this folder. (/Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/good_job-1.4.0/lib/generators/good_job/templates)

LoadError: no such file to load -- /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/good_job-1.4.0/lib/generators/good_job/templates
                               const_get at org/jruby/RubyModule.java:3707
                              eager_load at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/zeitwerk-2.4.0/lib/zeitwerk/loader.rb:399
                                      ls at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/zeitwerk-2.4.0/lib/zeitwerk/loader.rb:742
                                    each at org/jruby/RubyDir.java:739
                                 foreach at org/jruby/RubyDir.java:541
                                      ls at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/zeitwerk-2.4.0/lib/zeitwerk/loader.rb:734
                              eager_load at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/zeitwerk-2.4.0/lib/zeitwerk/loader.rb:387
                             synchronize at org/jruby/ext/thread/Mutex.java:164
                              eager_load at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/zeitwerk-2.4.0/lib/zeitwerk/loader.rb:376
                                    each at org/jruby/RubyArray.java:1809
                          eager_load_all at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/zeitwerk-2.4.0/lib/zeitwerk/loader.rb:494
                                Finisher at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/railties-6.0.3.4/lib/rails/application/finisher.rb:122
                           instance_exec at org/jruby/RubyBasicObject.java:2694
                                     run at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/railties-6.0.3.4/lib/rails/initializable.rb:32
                        run_initializers at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/railties-6.0.3.4/lib/rails/initializable.rb:61
                              tsort_each at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/stdlib/tsort.rb:228
       each_strongly_connected_component at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/stdlib/tsort.rb:350
  each_strongly_connected_component_from at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/stdlib/tsort.rb:431
       each_strongly_connected_component at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/stdlib/tsort.rb:349
                                    each at org/jruby/RubyArray.java:1809
                                    call at org/jruby/RubyMethod.java:131
       each_strongly_connected_component at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/stdlib/tsort.rb:347
                              tsort_each at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/stdlib/tsort.rb:226
                              tsort_each at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/stdlib/tsort.rb:205
                        run_initializers at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/railties-6.0.3.4/lib/rails/initializable.rb:60
                             initialize! at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/railties-6.0.3.4/lib/rails/application.rb:363
                                  <main> at /Users/tedhexaflow/Codes/beescm/gBEE/config/environment.rb:7
                                 require at org/jruby/RubyKernel.java:974
                        require_relative at org/jruby/RubyKernel.java:1002
                         new_from_string at config.ru:5
                                    eval at org/jruby/RubyKernel.java:1048
                         new_from_string at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/rack-2.2.3/lib/rack/builder.rb:116
                               load_file at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/rack-2.2.3/lib/rack/builder.rb:105
                              parse_file at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/rack-2.2.3/lib/rack/builder.rb:66
       build_app_and_options_from_config at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/rack-2.2.3/lib/rack/server.rb:349
                                     app at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/rack-2.2.3/lib/rack/server.rb:249
                             wrapped_app at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/rack-2.2.3/lib/rack/server.rb:422
                                   start at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/rack-2.2.3/lib/rack/server.rb:312
                        handle_profiling at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/rack-2.2.3/lib/rack/server.rb:379
                                   start at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/rack-2.2.3/lib/rack/server.rb:311
                                   start at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:39
                                 perform at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:147
                                     tap at org/jruby/RubyKernel.java:1897
                                 perform at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138
                                     run at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/thor-1.0.1/lib/thor/command.rb:27
                          invoke_command at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/thor-1.0.1/lib/thor/invocation.rb:127
                                dispatch at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/thor-1.0.1/lib/thor.rb:392
                                 perform at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/railties-6.0.3.4/lib/rails/command/base.rb:69
                                  invoke at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/railties-6.0.3.4/lib/rails/command.rb:46
                                  <main> at /Users/tedhexaflow/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared/gems/railties-6.0.3.4/lib/rails/commands.rb:18
                                 require at org/jruby/RubyKernel.java:974
                                  <main> at bin/rails:6

**Comment by bensheldon** [comment]
@tedhexaflow thanks for the update! I've re-opened this Issue and will figure out why it's not working in the production environment.

**Comment by bensheldon** [comment]
@tedhexaflow I just released GoodJob v1.4.1 with a fix for your error message. I had trouble reproducing the problem; I'm sorry if we have to play whackamole on these errors. I'm committed to getting jruby working for you.

**Comment by tedhexaflow** [comment]
Hi Ben,

Thank you so much. 🙏
I just tested with all 3 adapter options in production mode, and working beautifully now.
At this moment, I've tested only with puma.
Normally, most of the JRuby apps are deployed with Java Servlet (i.e., ApacheTomcat).
I'll organize to test with the Tomcat server and will keep you update.
Once again, thank you so much.

**Comment by tedhexaflow** [comment]
Hello Ben,

I just tested with ApacheTomcat, and it is working flawlessly as well.  🎉🍾🤩

I believe this is a huge help for the JRuby community.

Most of the JRuby Apps are for Enterprise Application, and the way we deploy is different from the normal Rails app deployment (i.e., Heroku.)

We normally package the app with https://github.com/jruby/warbler and drop the war file to ApacheTomcat.
We do not even require to have source code on the production server.

With other gems (i.e., DelayedJob), we cannot run the external command (i.e., delayed_job start) as a daemon without having the source code on the production server.

But with the GoodJob :async execution mode, we no longer need to have the source code on the production server and no more daemon to run, monitor, and maintain.

As far as I'm aware, there are no other ActiveJob Backend gems that work as mentioned above without any additional work for JRuby (with ApacheTomcat).

I think the JRuby community should be aware of these precious gems. 
Maybe you could keep in touch with Charles https://github.com/headius, and he can share these gems with the wider JRuby community.

Cheers!
Ted
