### ISSUE TITLE
how to run good_job on a separate machine 

### ISSUE THREAD

**Issue by jimchild49** [bensheldon/good_job#162]
Can you please explain :

```
$ bundle exec good_job start

Ideally the command-line tool should be run on a separate machine or container from the web process. For example, on Heroku:

web: rails server
worker: bundle exec good_job start
```

Not everyone is using heroku, I use a load balancer in front of multiple containers that hold my rails app, not clear to me what **a separate machine or container from the web process** means

**Comment by bensheldon** [comment]
Thanks you pointing out some awkward phrasing in need of context. I think better the line should read `should be run on a machine or container separate from the web process`.

How are you managing your containers? For example, I assume that somewhere you have a line like `bundle exec rails s --port=PORT`. The documentation is intended to describe adding an additional process to whatever manager you are using:

PaaS:
- Heroku: additional line in Procfile
- Digital Ocean App Platform PaaS: New worker component
- Kubectl: new deployment

EC2 / Digital Ocean Droplet:
- Systemd: new service file
- Upstart: new service file
