### ISSUE TITLE
Goodjob startup script for FreeBSD

### ISSUE THREAD

**Issue by lauer** [bensheldon/good_job#214]
I am working on a startup script for goodjob working for FreeBSD

But maybe someone already has created this, without sharing?

It must follow the guidelines described here: 
https://docs.freebsd.org/en_US.ISO8859-1/books/handbook/configtuning-starting-services.html

But would it be included in this project, if I add a pull request?

**Comment by bensheldon** [comment]
@lauer yes, please do share if you have a working script 🙏  There is an initd script in these comments: https://github.com/bensheldon/good_job/issues/88#issuecomment-689482818

Everything right now is going into the Readme, I think adding a new section that included some examples of service/startup scripts would be good. And if it gets too long, maybe the Readme could reference an `examples` directory in the project.
