### ISSUE TITLE
How do you enqueue a job to be executed immediately outside of Rails (eg. creating a new record of good_jobs in Postgresql)?

### ISSUE THREAD

**Issue by vtt** [bensheldon/good_job#225]
What parameter is needed for the new row of record?  Also, is it possible to make the worker run the job immediately instead of waiting for the next polling interval?

**Comment by bensheldon** [comment]
@vtt by default, I believe what you're asking for is achieved:

`YourJob.perform_later` will enqueue a job, and use Postgres LISTEN/NOTIFY to have a worker's execution thread (assuming one is available) wake up, fetch and process the job. 

Happy to help!

**Comment by vtt** [comment]
I specifically asked how to do this outside of Rails.  For example, using another language or directly create a new record of "good_jobs" table by issuing SQL commands directly (eg. INSERT INTO good_jobs(…) VALUES (…);

My question is about the required fields and the format of "serialized_params" column?

**Comment by vtt** [comment]
To clarify, how do you push a job to good_job worker for immediate execution without ruby?

**Comment by bensheldon** [comment]
@vtt sorry, I misunderstood your question. 

For immediate execution, the postgres statement is simply `NOTIFY good_job` which will notify all workers.

https://github.com/bensheldon/good_job/blob/83b59e0c48566825e7ecec6459276744a999ada4/lib/good_job/notifier.rb#L41

If you want to fully simulate GoodJob, the message payload keys are `queue_name` and `scheduled_at`:

```json
NOTIFY good_job, '{"queue_name":"test","scheduled_at":"2021-01-22T16:09:18.976Z"}'
 ```

**Comment by vtt** [comment]
That won't work if the message json exceeds 8000 characters.   Jobs that have big texts or data (as argument) won't be able run.  In any case, I asked this question before I created skiplock.  I've since used skiplock for my project.  Thanks.
