### ISSUE TITLE
Cannot run db:migrate when execution mode is :async

### ISSUE THREAD

**Issue by Systho** [bensheldon/good_job#229]
Hello, 

I'm using good_job in a team project and the gem was introduced in a PR along with a change in rails config : 

```
  config.good_job.execution_mode = :async
```

This causes max_cache to be different than 0 and therefore it tries to warm_cache upon initialization.

The problem is that I do not have the `good_jobs` table yet and my `rails db:migrate` is supposed to create it but it crashes dues to `warm_cache` failing because the table does not exists.

**Comment by bensheldon** [comment]
Thanks for opening an issue! That is not a good situation.

Could you give this configuration a try and let me know if it solves your problem?

```ruby
if Rails.const_defined?("Server")
  config.good_job.execution_mode = :async
else
  config.good_job.execution_mode = :external
end
```

The intention is that it will only run GoodJob in async mode running the webserver, which should make any other commands, tasks or interactive console _not_ run GoodJob in async mode.

**Comment by Systho** [comment]
The suggested workaround works, thanks for the suggestion !

But this should probably be done in a more natural way by the gem itself in a future version :)

**Comment by Systho** [comment]
It probably related to #194

**Comment by bensheldon** [comment]
Happy I could help unblock you 🙌 

And I agree. Thanks for linking to #194, which is where I plan to improve this experience.
