### ISSUE TITLE
Add GoodJob to Ruby Toolbox

### ISSUE THREAD

**Issue by bensheldon** [bensheldon/good_job#243]
GoodJob can be listed here: https://www.ruby-toolbox.com/categories/Background_Jobs

**Comment by bensheldon** [comment]
PR here: https://github.com/rubytoolbox/catalog/pull/541

**Comment by sandstrom** [comment]
I think we can close this: https://www.ruby-toolbox.com/projects/good_jobhttps://www.ruby-toolbox.com/projects/good_job
