### ISSUE TITLE
Jobs not visible in dashboard

### ISSUE THREAD

**Issue by petebytes** [bensheldon/good_job#245]
I see the job being added to good_jobs and it completes
GoodJob::Job Create (0.7ms)  INSERT INTO "good_jobs" ("queue_name", "priority", "serialized_params", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["queue_name", "default"]

The dashboard does not show any jobs.

**Comment by bensheldon** [comment]
@petebytes thanks for opening an issue. 

Can you open up the Rails console and verify that the job records are still present (`GoodJob::Job.all`)? 

By default, GoodJob deletes jobs after they are executed: https://github.com/bensheldon/good_job#monitor-and-preserve-worked-jobs

**Comment by petebytes** [comment]
@bensheldon

Thanks added the following to config/initializers/good_job.rb
```GoodJob.preserve_job_records = true```

And seems to be working!

**Comment by bensheldon** [comment]
🎉 awesome! Glad it was configuration 😅
