### ISSUE TITLE
Add Frozen String Literal to all files

### ISSUE THREAD

**Issue by bensheldon** [bensheldon/good_job#298]
Something overlooked in the initial project set up.

- [x] Update Rubocop to remove disabling of `Style/FrozenStringLiteralComment` rule (not sure why that was initially there; probably merely copy-pasta from some other project)
- [x] Run Rubocop to add the literal to all the files

**Comment by tedhexaflow** [comment]
https://github.com/bensheldon/good_job/pull/302

**Comment by bensheldon** [comment]
@tedhexaflow Thank you 🙏
