### ISSUE TITLE
Unsubscribed LISTEN forever after database connection lost

### ISSUE THREAD

**Issue by nsilva-ta** [bensheldon/good_job#303]
If I break the database connection (with a service postgresql restart):

```
[GoodJob] [13272] GoodJob started scheduler with queues=* max_threads=2.
[GoodJob] Notifier subscribed with LISTEN
FATAL:  terminating connection due to administrator command
[GoodJob] Notifier unsubscribed with UNLISTEN
[GoodJob] [13272] [GoodJob::Scheduler(queues=* max_threads=2)-worker-2] Executed GoodJob 759a041c-9fcb-4656-b2bb-04ea4c8b0243
[GoodJob] [13272] [GoodJob::Scheduler(queues=* max_threads=2)-worker-3] Executed GoodJob 4b2388f5-a31f-41f2-a55a-31fc28615076
[GoodJob] [13272] [GoodJob::Scheduler(queues=* max_threads=2)-worker-2] Executed GoodJob 9aa9c6bc-3a53-4edc-9a5e-a29b0e6205a2
[GoodJob] [13272] [GoodJob::Scheduler(queues=* max_threads=2)-worker-3] Executed GoodJob 833f2c60-da32-4c4a-b3f9-36abd1c15702
[GoodJob] [13272] [GoodJob::Scheduler(queues=* max_threads=2)-worker-2] Executed GoodJob 276fdbf6-4374-4c44-bcb5-770cd0066b87
[GoodJob] [13272] [GoodJob::Scheduler(queues=* max_threads=2)-worker-3] Executed GoodJob 781d2302-d838-429a-8591-b3cd81bcb402
```

The notifier is still unsubscribed! Only polling is working but executing only one job at the time.
With max_threads=2 the log shows a worker-3.

_Originally posted by @nsilva-ta in https://github.com/bensheldon/good_job/issues/296#issuecomment-884126725_

**Comment by bensheldon** [comment]
@nsilva-ta Thank you for continuing to track these down. I'll take a look at this. I really appreciate you finding these issues with database connection lifecycle. I wanted to doublecheck if these things are blocking you from adopting GoodJob? (if so, I'll increase them in my own priority)

Also, wanted to note that the thread numbers are really interesting. Those `-worker-#` are coming from Concurrent Ruby's threadpool executor. It makes me wonder what happened to `worker-1` 😄 . Thanks again for surfacing this!

**Comment by nsilva-ta** [comment]
I didn't give up yet 😄 
For now I'l be using version 1.11.1 with this configuration
```ruby
# config/initializers/good_job.rb
GoodJob.retry_on_unhandled_error = false
GoodJob.preserve_job_records = true

GoodJob.on_thread_error = lambda do |exception|
  # https://github.com/bensheldon/good_job/issues/296
  case exception
  when ActiveRecord::ConnectionNotEstablished, PG::UnableToSend
    sleep(30)
  when ActiveRecord::StatementInvalid
    GoodJob::Job.advisory_lockable_column = 'id' if GoodJob::Job._advisory_lockable_column.blank?
  end

  sleep(5)
end
```
