### ISSUE TITLE
ERROR:  relation "good_jobs" does not exist at character 454

### ISSUE THREAD

**Issue by petebytes** [bensheldon/good_job#308]
Seeing this error repeat. running good_job v 1.11.2

`postgres_1      | 2021-07-25 20:39:26.577 UTC [131] ERROR:  relation "good_jobs" does not exist at character 454
postgres_1      | 2021-07-25 20:39:26.577 UTC [131] STATEMENT:  SELECT a.attname, format_type(a.atttypid, a.atttypmod),
postgres_1      |              pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
postgres_1      |              c.collname, col_description(a.attrelid, a.attnum) AS comment
postgres_1      |         FROM pg_attribute a
postgres_1      |         LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
postgres_1      |         LEFT JOIN pg_type t ON a.atttypid = t.oid
postgres_1      |         LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
postgres_1      |        WHERE a.attrelid = '"good_jobs"'::regclass
postgres_1      |          AND a.attnum > 0 AND NOT a.attisdropped
postgres_1      |        ORDER BY a.attnum`

![image](https://user-images.githubusercontent.com/676739/126912848-6d37bdfb-ce27-4a69-bd09-e34b1db13324.png)

good_job:update shows migration files are identical

Migrations are all UP

bash-5.1# bin/rails g good_job:update
        skip  db/migrate/20210725203837_create_good_jobs.rb
   identical  db/migrate/20210701172249_add_active_job_id_concurrency_key_cron_key_to_good_jobs.rb
   identical  db/migrate/20210701172250_add_active_job_id_index_and_concurrency_key_index_to_good_jobs.rb

**Comment by bensheldon** [comment]
@petebytes that's strange. Are you seeing this in the development environment or in production? And also, is this a new install or did you recently update GoodJob?

I think that query is coming out of ActiveRecord. I found this SO post that looks like it's a similar class of problem: https://stackoverflow.com/questions/19097558/pg-undefinedtable-error-relation-users-does-not-exist

**Comment by petebytes** [comment]
Development - I deleted the Postgres volume and rebuilt.
Seems to be gone :)

**Comment by petebytes** [comment]
Exact same problem happening again in development.  Running good_job 3.0.0
Postgres version 11.6
Not sure how to troubleshoot.

`2022-07-02 15:43:18.905 UTC [5739] ERROR:  relation "good_job_processes" does not exist at character 454
2022-07-02 15:43:18.905 UTC [5739] STATEMENT:  SELECT a.attname, format_type(a.atttypid, a.atttypmod),
          pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
          c.collname, col_description(a.attrelid, a.attnum) AS comment
     FROM pg_attribute a
     LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
     LEFT JOIN pg_type t ON a.atttypid = t.oid
     LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
    WHERE a.attrelid = '"good_job_processes"'::regclass
      AND a.attnum > 0 AND NOT a.attisdropped
    ORDER BY a.attnum`

**Comment by petebytes** [comment]
The solution was listed on the post you linked to @bensheldon 
I ran docker compose exec app bin/rails db:prepare RAILS_ENV=test
and the issue is gone :)

PS Loving using cron with good_job!

**Comment by bensheldon** [comment]
Glad you continue to find a fix. I'm a little curious why your  database keeps getting out of sorts. 

Also, you might save a few keystrokes with:

`rails db:test:prepare`
