### ISSUE TITLE
Store in database if a job has been ActiveJob retried

### ISSUE THREAD

**Issue by bensheldon** [bensheldon/good_job#321]
When a job is retried through ActiveJob, it generates a new `GoodJob::Job` record. The `id` of the newly created record should be stored on the originating job: `good_jobs.retried_good_job_id`.

Storing this will make it possible to only show the "head" `GoodJob::Job` record on the dashboard and identify "dead" jobs (described in #271)

**Comment by reczy** [comment]
Hi @bensheldon!

If you approached it this way, wouldn't that mean the originating job would need to store an array of ids (since there can be 0 to many retries)? If that's the case, then an alternative could potentially be storing the originating id on every record (eg, `good_jobs.originating_good_job_id` where `originating_good_job_id = id` on the originating job). Or name it `parent_id` as a shorter alternative. Then, ordering by `created_at` gets us the first, last, and full history of the job.

**Comment by bensheldon** [comment]
@reczy great question! Thanks for engaging on this. 

You're right that if this value attempted to be comprehensive and track all subsequent retries, it would need to be an array... but I am really just interested in the boolean value was this job retried? That's really all that's needed to track whether the `good_job` is the _head_ execution and the _dead_ one too.

```ruby
class GoodJob::Job
  scope(:head) { where(retried_good_job_id: nil) }
  scope(:dead) { head.finished.errored }
end
```

For any individual record in the `good_jobs` table, each of records should ever be "retried" once, though there would then be chain of jobs:

| id | active_job_id | retried_good_job_id |
|----|---------------|---------------------|
| 1  | abc           | 2                   |
| 2  | abc           | 3                   |
| 3  | abc           |                     |

There's nothing really stopping this from being a boolean (`is_retried`), or a timestamp (`retried_at`) but I like having it be referential because that (hopefully) reinforces the intention that the execution chain is linear e.g. a single good_job should never result directly in 2 retried good_job records.

And this is on my mind wholly for thinking about how to improve the Dashboard. I am learning people are most interested in the `active_job_id` and its status (at least on the Index), so querying on `head` would be able to achieve that more efficiently than a `GROUP BY active_job_id` this would still allow clicking into the Show to display all the individual executions / `good_jobs`.

**Comment by reczy** [comment]
Thanks for delineating your thoughts! In my head, I was considering the originating job to be the same for all subsequent retries, but I like the approach proposed here more.
