### ISSUE TITLE
Lockable should accept an explicit keys on class methods too

### ISSUE THREAD

**Issue by bensheldon** [bensheldon/good_job#341]
I'd like to be able to create an arbitrary advisory lock from the Class; currently, that's only possible from an instance.

e.g. `MyClass.with_advisory_lock ...`

Would help clean up this: https://github.com/bensheldon/good_job/blob/8e1a0f334dc83aae6a04faa521c9c9953c0a9783/lib/good_job/active_job_extensions/concurrency.rb#L25

**Comment by pandwoter** [comment]
Hey, I've tried to dig into this and so far I see two options: 
1. Copy instance variant of the `Lockable#with_advisory_lock` method to class level (this would bloat class level methods in my opinion)
2. We modify a `Lockable.advisory_lock` scope to include only one record if an additional argument was passed (eg key: ...). 
![image](https://user-images.githubusercontent.com/44208683/151324252-345bce4b-8897-4df5-b664-824ee640e8c3.png)
This approach has a downside: we perform all of the hassles with `cte_table` even for one record.

I think both variants is not worth it and it would be better to keep everything as it is right now (creating a useless instance of an `Execution` is cheaper than going with either of these variants)

Let me know what do you think @bensheldon

**Comment by bensheldon** [comment]
@pandwoter Thanks for looking into this. I'm ok with Option 1.

**Comment by pandwoter** [comment]
@bensheldon well, I'll prepare a PR nearest time then 👍 , thanks for the response
