### ISSUE TITLE
Does Good job support delay method?

### ISSUE THREAD

**Issue by sasharevzin** [bensheldon/good_job#344]
Hello 👋 ,

I see that Good job was Inspired by Delayed job but does it have something similar to what Delayed job [has](https://github.com/collectiveidea/delayed_job#queuing-jobs) 🤔  : 
_Call `.delay.method(params)` on any object and it will be processed in the background._ 

Thank you in advance

**Comment by bensheldon** [comment]
Of course, GoodJob [fully supports ActiveJob](https://guides.rubyonrails.org/active_job_basics.html#enqueue-the-job). You can use the syntax: `ExampleJob.set(wait: 1.week).perform_later`.

I'm not sure if you've given GoodJob a try, but FYI, [in the Rails development environment GoodJob executes `:inline`](https://github.com/bensheldon/good_job#configuration-options), though this will change in [upcoming GoodJob v2.0 to `:async`](https://github.com/bensheldon/good_job/issues/139).

**Comment by sasharevzin** [comment]
Im sorry, I wasn't clear enough. What I meant is that with Delayed job I can use `delay` call on every method in the class and it eliminates adding *_job.rb files completely. 
For example:

```ruby
class User
  def send_email
    # long task
  end
end

User.new.delay.send_email

**Comment by bensheldon** [comment]
Ah, sorry about my confusion. No, GoodJob doesn't provide an enqueuing interface separate from ActiveJob.

You could write your own, something like this, or suggest it upstream to Ruby on Rails.

```ruby
# Example:
#
#     class MyModel
#       include Jobbable
#
#       def do_something
#         # ...
#       end
#     end
#
#     MyModel.new.job(wait: 2.hours).do_something
#

module Jobbable
  extend ActiveSupport::Concern

  class_methods do
    def job(set: {})
      Jobbable::Proxy.new(self, set: set)
    end
  end

  class Proxy #:nodoc:
    def initialize(object, set: {})
      @object = object
      @set = set
    end

    def method_missing(method_name, *args)
      Jobbable::Job.set(@set).perform_later(@object, method_name, *args)
    end

    def respond_to_missing?(method_name, *args)
      @object.respond_to?(method_name, *args)
    end
  end

  class Job < ::ApplicationJob
    def perform(object, method_name, *args)
      object.send(method_name, *args)
    end
  end
end
```
