### ISSUE TITLE
Hacktoberfest 2021

### ISSUE THREAD

**Issue by morgoth** [bensheldon/good_job#393]
I'm wondering if good_job could opt in into hactoberfest https://hacktoberfest.digitalocean.com/

The idea is cool, but in last few editions there were problems, as some people were trying to submit no value commits just to get a t-shirt.
On the other hand if taken normally by community it could bring a lot of value, like pull requests or just bring some recognition in the community.

To opt in, the repo would need to have a "hacktoberfest" topic, vide https://hacktoberfest.digitalocean.com/resources/participation

What do you think?

**Comment by bensheldon** [comment]
👍👍 I think this is a great idea. I'm happy to handle the burden of drive-bys. 

Can you create the topic? I can tag suitable Issues. 

I've also had thoughts of putting stuff on CodeTriage too. Managing a project specifically for community contributions is a lot of work 😊

**Comment by morgoth** [comment]
Looks like I cannot edit the topics.
You can add them like this https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics#adding-topics-to-your-repository

**Comment by bensheldon** [comment]
I added `hacktoberfest` as a topic:

<img width="345" alt="Screen Shot 2021-10-01 at 11 19 44 AM" src="https://user-images.githubusercontent.com/47554/135668468-3dc31c32-3eb1-4921-a7f6-3046e19d2536.png">

For reference:

> A repository/project is considered to be participating in Hacktoberfest if the 'hacktoberfest' topic is present and is accepting public contributions via pull requests. An individual pull request can also be opted-in directly by adding the 'hacktoberfest-accepted' label.
>
> A pull request is considered approved once it has an overall approving review from maintainers, or has been merged by maintainers, or has been given the 'hacktoberfest-accepted' label. A pull request with any label containing the word 'spam' or 'invalid' will be considered ineligible for Hacktoberfest.

**Comment by morgoth** [comment]
See you next year ;-)
