### ISSUE TITLE
Internationalize/I18n the Dashboard Engine

### ISSUE THREAD

**Issue by bensheldon** [bensheldon/good_job#408]
It would be nice to have English UI strings extracted to a `yml` file to allow support for other locales.

We're liable to run into some RTL and spacing challenges once other translations are added, but we can address those as they arise. Ideally dates/times should be localized (as we they are currently locked to English in #407)

**Comment by bensheldon** [comment]
@query-string I'd love the help. Maybe you could scope down to doing the Cron screen of the dashboard. 

I'm imagining there might be a messy merge because all the strings will end up in the same en.yml, but I can get us past that barrier when it happens.

**Comment by effgenij** [comment]
@bensheldon @query-string If it's not urgent, I'll have it done by the end of the week. If it is urgent, you can pass it on to someone else.

**Comment by Liberatys** [comment]
@bensheldon is this still a feature you'd like to see? :D I'd like to start contributing to good_job(as I'm using it in all my new projects ^^ 👍🏻  Great job btw). So I think this would be a good first issue to setup the project and get to know the structure and process :D

**Comment by bensheldon** [comment]
@Liberatys yep! Still a feature I'd like to see. Thank you!

**Comment by JuanVqz** [comment]
@bensheldon one more try hahaha, I would like to work on this, but I'll be honest I have no experience doing things in gems, (that is part of the reason I just want to contribute). could you help me if I get stuck? I know maybe I'll ask several times but if you agree I can tackle it.

**Comment by bensheldon** [comment]
@JuanVqz I'm happy to help. Btw, if you just want to help, this might be a better starting issue: https://github.com/bensheldon/good_job/issues/341

**Comment by JuanVqz** [comment]
> @JuanVqz I'm happy to help. Btw, if you just want to help, this might be a better starting issue: https://github.com/bensheldon/good_job/issues/341

Thank you for your faster response, since you will be helping me I think, I can tackle both of them. 😃

**Comment by bensheldon** [comment]
I think we can call this done for now. Improvements are still invited, but the main thrust has been completed 🎉
