### ISSUE TITLE
Inline adapter should raise unhandled exceptions during execution

### ISSUE THREAD

**Issue by sedubois** [bensheldon/good_job#410]
Thanks for this gem!

I'm trying to migrate to GoodJob. As per the README I wanted to add `retry_on StandardError, wait: :exponentially_longer, attempts: Float::INFINITY` to `ApplicationJob`.

However then the naive test below fails, see scenario 3 (adapted from some tests which started failing in the app):
```rb
class User < ApplicationRecord
  after_update_commit { ErrorJob.perform_later }
end

class ErrorJob < ApplicationJob
  def perform
    raise "nope"
  end
end

class ApplicationJob < ActiveJob::Base
  # scenario 1: don't use retry_on. This is how it was initially.
  # scenario 2: retry_on StandardError, wait: :exponentially_longer, attempts: 5
  # scenario 3: retry_on StandardError, wait: :exponentially_longer, attempts: Float::INFINITY
end

class UserUpdateTest < ActiveSupport::TestCase
  # The test passes with scenario 1 and scenario 2, but not scenario 3
  test "name gets updated" do
    user = users(:my_user)

    user.update(name: 'john')

    assert_equal "john", user.name
  end
end
```

The outcome of the test changes depending on whether `retry_on` uses an infinite amount of attempts or a small amount, which looks inconsistent. My understanding is that if the code is asynchronous, then the test should be green in both cases, and if the code is synchronous, then the test should fail in both cases. How should this be resolved?

**Comment by bensheldon** [comment]
@sedubois Glad you're giving it a try! By default GoodJob's test adapter runs jobs `:inline`. You can change it to be `:async`:

```ruby
# config/environments/test.rb
# ....
config.good_job.execution_mode = :async
```

Or, if you just want it for a single test, you can use `ActiveJob::Base.queue_adapter = GoodJob::Adapter.new(execution_mode: :async`) in your setup/before (and remember to reset it after your test).

FYI, you can change `after_update_commit` to `after_update` if you're using the same Postgres database for your application and GoodJob; it will have transactional integrity.

**Comment by bensheldon** [comment]
> I'm not sure if this is relevant but I did not configure retry_on_unhandled_error, which according to the README is therefore true.

That will also contribute to the behavior you're seeing. ActiveJob will retry 3 times, then automatically raise it to the backend (GoodJob) which will continue re-running it. 

You should set `retry_on_unhandled_error` to false. Also, you should write your ActiveJob retry handlers with a block, which causes them not to re-raise the error. 

`retry_on(StandardError, wait: :exponentially_longer, attempts: 5) { nil }

**Comment by sedubois** [comment]
> That will also contribute to the behavior you're seeing. ActiveJob will retry 3 times, then automatically raise it to the backend (GoodJob) which will continue re-running it.

If GoodJob continues re-running the job, why is the test passing instead of getting stuck forever like in scenario 3?

Anyway thank you, it seems I have a few options to deal with the situation at the moment.

**Comment by bensheldon** [comment]
@sedubois oh, I understand.

> If GoodJob continues re-running the job, why is the test passing instead of getting stuck forever like in scenario 3?

Expected Behavior: When an ActiveJob execution raises an unhandled exception to the backend, the GoodJob _Inline_ adapter should raise that exception to the caller of `perform_later`. 

I'm not sure if this is a bug, or an enhancement, but things changed significantly in #241.

I'm going to re-open this issue to address it. Thank you!
