### ISSUE TITLE
GoodJob should automatically clean up after itself and delete old job records

### ISSUE THREAD

**Issue by bouk** [bensheldon/good_job#412]
It would be useful if there was a built-in ActiveJob that just calls `GoodJob.cleanup_preserved_jobs`, which could then be used with the Cron feature. That way it would be very easy to set up periodic finished job cleaning.

**Comment by AxelTheGerman** [comment]
Love this feature, just one word of caution. Running automagically without the developer being able to change the default could cause issues in production, e.g. using resources to clean up at a bad time (think of classic GC)

**Comment by bensheldon** [comment]
@AxelTheGerman thank you for the comment! Do you have any ideas for what would be good configuration options? I'm exposing two in my spike on the feature:

- `cleanup_interval_jobs` (integer) Number of jobs a Scheduler will execute before cleaning up preserved jobs. Defaults to `nil`. Can also be set with  the environment variable `GOOD_JOB_CLEANUP_INTERVAL_JOBS`.
- `cleanup_interval_seconds` (integer) Number of seconds a Scheduler will wait before cleaning up preserved jobs. Defaults to `nil`. Can also be set with  the environment variable `GOOD_JOB_CLEANUP_INTERVAL_SECONDS`.

**Comment by AxelTheGerman** [comment]
That's probably a good starting point!

So it will be whichever is hit first, i.e. 1000 jobs or 1 hour.

The potential issues I mentioned in my previous post probably won't happen until someone is running `good_job` under high load - at which point they could turn it off and implement their own clean up. Or then we could come up with a better "algorithm" to decide when to clean up

🚀

**Comment by AxelTheGerman** [comment]
> until GoodJob 3.0, when it will 1 hour

Not sure 1 hour is enough for systems with low throughput. In my apps I don't have many jobs running so I'd probably keep them around for 1 day - 1 week just in case.

But again, it's configurable - via code or ENV (which I love)
