### ISSUE TITLE
Improve security of Gem releases

### ISSUE THREAD

**Issue by bensheldon** [bensheldon/good_job#422]
See https://guides.rubygems.org/security/

- [ ] Sign Gems
- [x] Sign release commits
- [x] Generate checksums during release and store in repository

**Comment by bf4** [comment]
I'm not sure anyone really uses gem signing or that it's worth the effort.  If you enjoy it, sure, but I wouldn't do it again.

**Comment by bensheldon** [comment]
I will skip signing gems for now because it is little used.
