### ISSUE TITLE
Allow multiple schedulers within the same process. e.g. `queues=mice:2,elephants:4`

### ISSUE THREAD

**Issue by bensheldon** [bensheldon/good_job#45]

**Comment by manojmj92** [comment]
Hello @bensheldon 👋 ,

I would like to pick this up, but need some clarity on the requirement:

Do you mean to say that jobs in `elephants` should now be twice as likely to be picked as the jobs in `mice`?

ie, similar to specifying `[mice, mice, elephants, elephants, elephants, elephants]`  as the `queue`, but without the ordering of the queue itself not mattering (it is likely that we could pick up a job in `elephants` queue, even if there are pending jobs in `mice`, and that is okay)

Thanks for this gem and thanks for your time 🙂

**Comment by bensheldon** [comment]
Awesome! Thanks jumping in 🙏  Let me try to explain a bit more of what I was thinking about.

The goal is isolation of execution pools. I'd like this:

```bash
$ good_job --queues=mice:2,elephants:4
```

...to be equivalent (but in a single `good_job` process rather than 2 processes) to:

```bash
$ good_job --queues=mice --max-threads=2 & good_job --queues=elephants --max-threads=4
```
In the example of`queues=mice:2,elephants:4`, Mice would always have two worker threads available, and elephants would always have worker 4 threads available.  A large number of jobs on the elephants queue would never block jobs on the mice queue and vice versa.

Implementation-wise, we're limited here by what's possible with Concurrent::Ruby.  `GoodJob::Scheduler` is the abstraction around a threadpool. 

- My initial thought is that `queues=mice:2,elephants:4` would have the result of creating 2 different `GoodJob::Scheduler` objects. 
- I haven't looked deeply into what kind of isolation is possible on a single threadpool, but I think it might be overly-complex.

To point you to a starting place, this is where the scheduler is currently configured: https://github.com/bensheldon/good_job/blob/e7c7b223bdca300397c7faed95fddaa5291c4eb2/lib/good_job/cli.rb#L39-L59

I think it would be possible to wrap that with a `queue_names.split(';').each do...` loop initially. Though there's the question then of testing. I also had the idea of having a `MultiScheduler` object that would be instantiated with an array of Scheduler objects and delegate methods (`#shutdown`) so that the MultiScheduler would quack like a Scheduler and be reusable/interchangeable in situations like #27.

**Comment by manojmj92** [comment]
Thanks @bensheldon,

when you put it like 

```
$ good_job --queues=mice --max-threads=2 & good_job --queues=elephants --max-threads=4
```

it makes a lot of sense. The question I had in my head is "how can we have multiple schedulers without increasing the prescribed thread size too" but your description makes it clear that the thread sizes increases too.

Also, question: In such a case, what happens to any `--max_threads` defined alongside, so like

```
good_job --queues=mice:2,elephants:4 max_threads=10
```

Do we quietly discard the `10` here?

Also, what about cases like

```
good_job --queues=mice:2,elephants:4,tigers
```

Do we give a default of 1 thread to tiger or would it be a different value?
 
It looks like there could be multiple combinations of these here.

Also, opinion: Isn't this just ultimately syntactic sugar/shorthand for starting multiple new processes? If so, should we really dedicate time and developer effort at this stage of the project towards such a thing? I would kindly even suggest that we look into ways to specify queue weightage, so like `mice, mice, elephants, elephants, elephants, elephants` as the queue name and where a job in elephants is twice as likely to be picked as one in mice. Features like these could have much more impact in the community and chances of increased adoption of the library. Would love to know your thoughts 🙂

**Comment by manojmj92** [comment]
Oops, my apologies, please disregard the part about being "syntactic sugar for starting multiple new processes" - I was mistaken. This is indeed inside the same process.

**Comment by bensheldon** [comment]
Great questions about the interface. 

> what happens to any --max_threads defined alongside

Agreed: Discard it. You could also `$stdout.put` out a warning about that.

> good_job --queues=mice:2,elephants:4,tigers

Raising an `ArgumentError` in this case would be fine. Strongly enforcing that the format is either `QUEUE,...` or `QUEUE,...:N;QUEUE,...:N;...` is good for now.

**Comment by bensheldon** [comment]
@manojmj92 Just wanted to check-in. Are you still interested in making a PR for this feature? That would be awesome 🙌

**Comment by manojmj92** [comment]
@bensheldon apologies, I am quite busy with my day job now, I don't think I will be able to work on this anytime soon. Sorry!
