### ISSUE TITLE
Updating good_job breaks my Rails 7 alpha 2 local development

### ISSUE THREAD

**Issue by leehericks** [bensheldon/good_job#462]
> bundle outdated
good_job        2.7.0    2.7.2    ~> 2.4, >= 2.4.2  default

After running `bundle update` good_job gets mixed in with Puma initialization messages and then I can't get `rails server` to server pages in local development. Just hangs.

On the otherhand, at `good_job 2.7.0` I'm also getting
[GoodJob] Notifier unsubscribed with UNLISTEN
[GoodJob] Notifier errored: no connection to the server
but I can access the site in the browser...

**Comment by leehericks** [comment]
This is the hanging on 2.7.2

<img width="1338" alt="Screen Shot 2021-11-30 at 11 42 49" src="https://user-images.githubusercontent.com/2021411/143976309-170e6848-3a3e-48ef-8c73-5954e73f36ef.png">

**Comment by bensheldon** [comment]
@leehericks thanks for reporting this. Sounds like a deadlock. I'll try to reproduce.

Could you share how and where you're setting up `:good_job` as the `queue_adapter`? Thank you!

**Comment by leehericks** [comment]
<img width="714" alt="Screen Shot 2021-11-30 at 12 15 51" src="https://user-images.githubusercontent.com/2021411/143979541-142c484a-bb7e-4ab7-9e96-e782e3524a5e.png">

<img width="628" alt="Screen Shot 2021-11-30 at 12 16 02" src="https://user-images.githubusercontent.com/2021411/143979571-92049652-3109-446b-a079-9231afeb4036.png">

**Comment by bensheldon** [comment]
@leehericks nuts, I'm having trouble reproducing it. Here is instructions for how you can try to diagnose a deadlock yourself: https://github.com/bensheldon/good_job/issues/236#issuecomment-822094297

Also, if you wanted to find some time on my calendar, I'd love to Zoom on this: https://calendly.com/bensheldon/out-of-office-hours

**Comment by leehericks** [comment]
@bensheldon Despite running `ENV=RBTRACE bin/rails server --binding=0.0.0.0` I do not get output with the commands to run...

**Comment by leehericks** [comment]
*** attached to process 6908
>> puts output = ActionDispatch::DebugLocks.new(nil).send(:render_details, nil); output
=> [200, {"Content-Type"=>"text/plain", "Content-Length"=>0}, [""]]
*** detached from process 6908

**Comment by leehericks** [comment]
<img width="1340" alt="Screen Shot 2021-11-30 at 15 27 33" src="https://user-images.githubusercontent.com/2021411/143996858-58a9aabb-51b5-457b-b134-61f93d6e3090.png">

**Comment by leehericks** [comment]
Does any of this apply to your project?

[https://weblog.rubyonrails.org/2021/9/3/autoloading-in-rails-7-get-ready/](https://weblog.rubyonrails.org/2021/9/3/autoloading-in-rails-7-get-ready/)

**Comment by bensheldon** [comment]
@leehericks probably not? GoodJob has used Zeitwerk internally for [more than a year](https://github.com/bensheldon/good_job/issues/87). Rails Alpha 2 also has been in the test matrix for [a few months](https://github.com/bensheldon/good_job/pull/384).

Unfortunately these kinds of issues are tricky to trace down. A few more questions:

- Are you able to ctrl-c to exit, or is the terminal hanging?
- Does it hang if you change your `WEB_CONCURRENCY` to zero? e.g. running Puma in single process mode
- Could you try GoodJob `v2.7.1` and tell me if you experience the same behavior? That would help me narrow down some of the changes.

Thank you again for the help here 🙏

**Comment by leehericks** [comment]
@bensheldon 

1. ctrl-c hangs on `^C[11022] - Gracefully shutting down workers...` but does finally finish with `[11022] === puma shutdown: 2021-12-01 10:21:31 +0900 ===
[11022] - Goodbye!
Exiting
[GoodJob] Notifier unsubscribed with UNLISTEN`

2. Putting Puma web concurrency to 1 booted up but errored on first web request:

<img width="1333" alt="Screen Shot 2021-12-01 at 10 04 28" src="https://user-images.githubusercontent.com/2021411/144153031-adebbf2e-e964-4d60-9225-1848023f46e1.png">

3. Putting Puma web concurrency to 0 booted up and indeed the web request took a second but went through and then everything worked speedily.

<img width="1336" alt="Screen Shot 2021-12-01 at 10 07 34" src="https://user-images.githubusercontent.com/2021411/144153698-5163e7a5-6e5b-47db-a52b-0b0423c663f3.png">

4. You don't have a version 2.7.1 in Ruby Gems

**Comment by bensheldon** [comment]
Just a quick reply re: 4. There should be a v2.7.1 in Ruby Gems:

https://rubygems.org/gems/good_job/versions/2.7.1

That's weird if it's not fetchable.

**Comment by bensheldon** [comment]
This is progress that web concurrency affects the behavior. Thank you for debugging this with me; I appreciate it!

Could you try adding something like this to your puma config? It explicitly shuts down and restarts GoodJob's thread pools when Puma forks worker processes:

https://github.com/bensheldon/good_job/blob/fe8b2c32f4f7b7883832e9d3a12966ca9450821a/spec/test_app/config/puma.rb#L37-52

**Comment by leehericks** [comment]
> Just a quick reply re: 4. There should be a v2.7.1 in Ruby Gems:
> 
> https://rubygems.org/gems/good_job/versions/2.7.1
> 
> That's weird if it's not fetchable.

Ok, now it worked with a `bundle install`. Before it actually showed all versions outside of 2.7.1 saying it wasn't available. 🤷🏼‍♂️

**Comment by leehericks** [comment]
2.7.1 let's the http requests run, but good_job must not be loading because trying to access the job dashboard yields

```
Showing /Users/leehericks/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/good_job-2.7.1/engine/app/views/good_job/executions/_table.erb where line #31 raised:

No route matches {:action=>"show", :controller=>"good_job/jobs", :id=>nil}, possible unmatched constraints: [:id]
```

**Comment by bensheldon** [comment]
Oh! I don't think this is the root cause, but one thing at a time: it looks like you have `good_jobs` records with null `active_record_id` columns. That became a required attribute as part of the 0.x -> 1.x upgrade process. Run this in your Rails console to update those records:

```ruby
GoodJob::Execution.where(active_job_id: nil).update_all("active_job_id = (serialized_params->>'job_id')::uuid")
```

**Comment by leehericks** [comment]
> Oh! I don't think this is the root cause, but one thing at a time: it looks like you have `good_jobs` records with null `active_record_id` columns. That became a required attribute as part of the 0.x -> 1.x upgrade process. Run this in your Rails console to update those records:
> 
> ```ruby
> GoodJob::Execution.where(active_job_id: nil).update_all("active_job_id = (serialized_params->>'job_id')::uuid")
> ```

That's interesting. I've got the migrations in my db folder...
Ran that, still have issues with "no connection to the server".

I'm going to set up an example app from scratch and see if I can reproduce this.

**Comment by leehericks** [comment]
@bensheldon Ok, it completely comes down to the `puma.rb` web concurrency.

<img width="764" alt="Screen Shot 2021-12-01 at 14 23 26" src="https://user-images.githubusercontent.com/2021411/144176810-526feb76-d3fb-4bb6-a75d-c9b0378e5926.png">

If both of these lines are commented out then the deadlock will not occur.

In Rails 6.1.4.1, it works with web concurrency while still getting this after the first request:
```
[GoodJob] Notifier unsubscribed with UNLISTEN
[GoodJob] Notifier errored: no connection to the server

[GoodJob] Notifier subscribed with LISTEN
```

As a note, I upgraded good_job from 2.4.2 to 2.7.3. Both versions work with puma web concurrency enabled in development on Rails 6.1.4.1.

So this problem specifically comes out in Rails 7.0.0-alpha2 unless that "Notifier errored" is also not normal.

**Comment by bensheldon** [comment]
The "notifier errored" message is not normal. 

You could add `GoodJob.on_thread_error = ->(e) { put e }` to your initializer to see if it outputs a better error message.

I'll pick this up tomorrow (Pacific time).

**Comment by leehericks** [comment]
I couldn't get anything outputted with adding that to my initializer.
On a good note, for single mode the "Notifier errored" message has disappeared miraculously.

We completely overlooked this debugger starting on launch! I will have to figure out how to dive into that.
<img width="936" alt="Screen Shot 2021-12-01 at 15 29 11" src="https://user-images.githubusercontent.com/2021411/144183605-b5289e54-4b50-48db-a29b-293660cba2c2.png">

Thank you for your support!

**Comment by bensheldon** [comment]
@leehericks I just set up a new Rails 7.0.0.alpha2 with GoodJob and _still_ can't duplicate the behavior you're seeing 😭  I added you as a collaborator on the repo if you want to pull it down and see if it gives you a different experience, or add your configuration and push it back up for me to try:

https://github.com/bensheldon/good_job_rails7/commits/main

<img width="1512" alt="Screen Shot 2021-12-01 at 7 41 55 AM" src="https://user-images.githubusercontent.com/47554/144266092-497fc232-87aa-431f-af8a-2a3e794acb64.png">

**Comment by leehericks** [comment]
> oops that may be because there is a typo in the code: `put -> puts`.

No, I had found that one. ☺️

**Comment by leehericks** [comment]
After comparing and disabling gem by gem I think that good_job is not the cause of the hang. 😅
Seems like I need to check in with shioyama/mobility

**Comment by leehericks** [comment]
@bensheldon I'm sorry to use so much of your time pinpointing the culprit.
