### ISSUE TITLE
finished_at should be indexed and clean up should clean up all of a job's executions

### ISSUE THREAD

**Issue by zarqman** [bensheldon/good_job#476]
Thanks for adding the new option to automatically cleanup preserved jobs!

I noticed that `GoodJob::Execution.finished(timestamp).delete_all` inside of `cleanup_preserved_jobs` is querying `finished_at` but that column isn't indexed resulting in a table scan. I'm thinking `finished_at` needs an index (possibly conditional on being `not null`)?

**Comment by bensheldon** [comment]
@zarqman thank you! 🙏 

I'll add an index. That also caused me to notice that the cleanup task should retain Execution records until the Job itself completes successfully, then cleanup all the Job's executions at once.
