### ISSUE TITLE
Error on GJ admin UI search form

### ISSUE THREAD

**Issue by morgoth** [bensheldon/good_job#487]
When putting something like `Something::Namespaced` into search input, it throws an error:
"ActionView::Template::Error: PG::SyntaxError: ERROR: syntax error in tsquery"

This can be reproduced on https://goodjob-demo.herokuapp.com/good_job

**Comment by bensheldon** [comment]
@morgoth thanks! I'll dig into that.

**Comment by bensheldon** [comment]
I released a fix for this in [v2.9.2](https://github.com/bensheldon/good_job/releases/tag/v2.9.2).
