### ISSUE TITLE
The navbar icon doesn't show the navbar menu when clicking it

### ISSUE THREAD

**Issue by JuanVqz** [bensheldon/good_job#503]
When seeing the /good_job page in mobile the navbar toggler icon is not triggering the event to show the navbar menu.

![image](https://user-images.githubusercontent.com/7331511/151690011-ff7be094-8d4b-43d6-abb6-dce035c23d53.png)

**Comment by bensheldon** [comment]
I think this was caused by #492 adding a responsive Meta tag, but the Bootstrap Navbar HTML must have something wrong with it. Would you be able to look at that?

https://getbootstrap.com/docs/5.1/components/navbar/#toggler

**Comment by JuanVqz** [comment]
> I think this was caused by #492 adding a responsive Meta tag,

I'll check it out before that commit to see if that breaks the navbar.

but the Bootstrap Navbar HTML must have something wrong with it. Would you be able to look at that?
> 
> 
> 
> https://getbootstrap.com/docs/5.1/components/navbar/#toggler

I already checked it and it seems like it is ok.

**Comment by bensheldon** [comment]
@JuanVqz I think I found the problem. The attribute should be `data-bs-toggle` (missing the `-bs-`):

https://github.com/bensheldon/good_job/blob/68fb9603d895b18b588b11285f52d7f83c28679a/engine/app/views/layouts/good_job/base.html.erb#L24

Could you give that a try, and if it does fix it, please make a PR?

**Comment by JuanVqz** [comment]
You are right that was the issue, PR #506  

![Peek 2022-01-31 08-21](https://user-images.githubusercontent.com/7331511/151810398-53ed1649-688e-4357-bc7c-83ea7b7a9c15.gif)
