### ISSUE TITLE
"Live Poll" dashboard

### ISSUE THREAD

**Issue by danielwestendorf** [bensheldon/good_job#526]
Add UX to automatically reload the contexts of the good job dashboard ever X seconds. This could be as simple as a

```javascript
setInterval(function() { window.location.reload() }, 5000)
```

or something more complex that dom-diffs or something.

I'd be happy to implement this if it belongs in the project.

**Comment by bensheldon** [comment]
@danielwestendorf definitely. The simpler the better. What do you think of these requiements:

- disabled by default 
- enableable with a checkbox
- enableable by a query param
- frequency can be changed by a query param

I'm imagining the purpose is for a dashboard/wallboard?

**Comment by bensheldon** [comment]
@danielwestendorf thank you for the contribution 🙏 This feature has been released in [v2.11.0](https://github.com/bensheldon/good_job/releases/tag/v2.11.0) 🎉
