### ISSUE TITLE
How do I ensure that a the same job can't run twice? (unique job / avoid duplicates)

### ISSUE THREAD

**Issue by rgaufman** [bensheldon/good_job#531]
I am looking for something like this for good_job: https://github.com/mhenrixon/sidekiq-unique-jobs

To be able to do specifically the equivalent of this:

```
sidekiq_options queue: :default, lock: :until_executed
```

Is this the equivalent with good_job? <

```
 good_job_control_concurrency_with(total_limit: 1, key: arguments)
```

Or am I misunderstanding?

**Comment by bensheldon** [comment]
Exactly. [GoodJob's ActiveJob Concurrency](https://github.com/bensheldon/good_job#activejob-concurrency) extension can provide equivalent functionality to sidekiq-unique-jobs

This would be the equivalent of `lock: :until_executed`

```ruby
class MyJob < ApplicationJob
  include GoodJob::ActiveJobExtensions::Concurrency

  good_job_control_concurrency_with(total_limit: 1)
  
  # ....
end
```

**Comment by rgaufman** [comment]
Just to confirm:

1. This allow many of the same job to run concurrently with different arguments
2. But it won't allow queuing a new job if one is already running with the same arguments

Is that right?

**Comment by bensheldon** [comment]
Concurrency is limited based on whatever the `key:` value is. By default the key is the name of the class that the concurrency control is declared within, but you can use the lambda to make it based on anything (queue name, job arguments, some database call, anything) by using the Proc that returns a String that is compared against.

**Comment by rgaufman** [comment]
Ah. ok, so then this should work and allow multiples of the same job, as long as arguments are different? (whatever the arguments are):

```good_job_control_concurrency_with(total_limit: 1, key: arguments)```

**Comment by bensheldon** [comment]
That exact code won't execute because `arguments` only exist in the context of a particular instance of a job. You'd need to stringify the arguments within a proc. e.g. 

```ruby
# an example scalpel based on your specific method signature
good_job_control_concurrency_with(total_limit: 1, key: -> { arguments[0] })

# or with a hammer
good_job_control_concurrency_with(total_limit: 1, key: -> { arguments.to_json })

**Comment by rgaufman** [comment]
Why is .to_json necessary? - can I specify just arguments in the lambda?

**Comment by bensheldon** [comment]
You'll get whatever `arguments.to_s` stringifies to. Which is probably a consistent marshalling of the object, but I dunno. Give it a shot.

**Comment by rgaufman** [comment]
Ah, understood, thank you!
