### ISSUE TITLE
ArgumentError: wrong number of arguments (given 1, expected 0; required keyword: schedule) - cron

### ISSUE THREAD

**Issue by hiendinhngoc** [bensheldon/good_job#546]
I got this error when setting for my job with argument:
```ruby
class External::BlazerJob < ApplicationJob
  queue_as :default

  def perform(schedule:)
    Blazer.run_checks(schedule: schedule)
  end
end
```

and here is my setting:
```ruby
five_mins_interval_check_task: {
        cron: "10/5 * * * *",
        class: "External::BlazerJob",
        args: {schedule: "5 minutes"},
        desciption: "Run 5-minute interval checks",
      }
```

I expected the job should be `Blazer.run_checks(schedule: "5 minutes")` after passing the argument.

What was I wrong here?

**Comment by bensheldon** [comment]
@hiendinhngoc Try passing the args as an array:

```ruby
args: [{schedule: "5 minutes"}],
```

**Comment by bensheldon** [comment]
🙌  woot!

**Comment by hiendinhngoc** [comment]
I am sorry, reopen this because after deploying to staging, I'm still getting this error regarding the update, active job params:
```json
{
  "job_id": "c8fc128a-05de-495d-9d68-cu92483c56d8",
  "locale": "en",
  "priority": null,
  "timezone": "UTC",
  "arguments": [
    {
      "schedule": "5 minutes",
      "_aj_hash_with_indifferent_access": true
    }
  ],
  "job_class": "External::BlazerJob",
  "executions": 0,
  "queue_name": "default",
  "enqueued_at": "2022-03-29T04:25:00Z",
  "provider_job_id": null,
  "exception_executions": {
  }
}
```

Does it due to the old jobs which were already in the queue before? If yes how do I remove all the old ones?

**Comment by bensheldon** [comment]
@hiendinhngoc I looked into it deeper and I think it may not work with kwargs. I'm a bit stumped on how to appropriately construct/pass a configuration value that has both args and kwargs to a method. Could you share the version of Ruby, and Ruby on Rails you're using?

I'm doing some more research on how to handle this.

**Comment by hiendinhngoc** [comment]
I am using ruby 3.0.2 and rails 6.0.4

**Comment by bensheldon** [comment]
@hiendinhngoc I just released a new version ([v2.11.3](https://github.com/bensheldon/good_job/releases/tag/v2.11.3)) that splits out an explicit `kwargs`.

```ruby
five_mins_interval_check_task: {
        cron: "10/5 * * * *",
        class: "External::BlazerJob",
        kwargs: {schedule: "5 minutes"}, # <-- change this to `kwargs`
        desciption: "Run 5-minute interval checks",
      }
```

**Comment by hiendinhngoc** [comment]
@bensheldon thank you for your quick support. If the arguments are more than one, what should be correct?
`[{from: 7.days}, {to: 6.days}]` or `{from: 7.days, to: 6.days}`

**Comment by bensheldon** [comment]
Yay! One single hash.

**Comment by hiendinhngoc** [comment]
thank you so much!
