### ISSUE TITLE
I18n::InvalidLocale (:en is not a valid locale):

### ISSUE THREAD

**Issue by brentgreeff** [bensheldon/good_job#549]
We have an application with `config.i18n.available_locales = [:fr, :nl]`

Crazy but we dont support English - as important as it is in the world :)

I might have some time to hack on this if you want me to try?

```
Processing by GoodJob::ExecutionsController#index as HTML
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms | Allocations: 901)

I18n::InvalidLocale (:en is not a valid locale):
  
i18n (1.10.0) lib/i18n.rb:357:in `enforce_available_locales!'
i18n (1.10.0) lib/i18n/config.rb:15:in `locale='
actionview (6.1.4.3) lib/action_view/lookup_context.rb:296:in `locale='
actionview (6.1.4.3) lib/action_view/rendering.rb:21:in `locale='
i18n (1.10.0) lib/i18n.rb:74:in `locale='
i18n (1.10.0) lib/i18n.rb:326:in `with_locale'
good_job (2.11.3) engine/app/controllers/good_job/base_controller.rb:30:in `switch_locale'
```

**Comment by morgoth** [comment]
I guess GJ should use `I18n.default_locale`. Not sure if this would have any negative effects that are not visible right now.

The language switch was added to ensure consistent UI, vide https://github.com/bensheldon/good_job/pull/407

**Comment by bensheldon** [comment]
Interesting! Maybe `I18n.default_locale || :en`. There are some changes in #497 around locale. I'll make a repro app and get this sorted.

**Comment by bensheldon** [comment]
I think this has been fixed via #497:

https://github.com/bensheldon/good_job/pull/497/files#diff-8011773e348f307cae2abd9599b14c581bae63b00db465646a1491f6f498917cR37-R45

**Comment by brentgreeff** [comment]
`Fetching good_job 2.12.0 (was 2.11.3)`

I get the same error

```
Processing by GoodJob::ExecutionsController#index as HTML
  Parameters: {"poll"=>"value value value value value value value value value ", "job_class"=>"", "state"=>"finished", "queue_name"=>"", "query"=>"fail@example.com"}
Completed 500 Internal Server Error in 30ms (ActiveRecord: 0.0ms | Allocations: 3322)  

I18n::InvalidLocale (:en is not a valid locale):
  
i18n (1.10.0) lib/i18n.rb:357:in `enforce_available_locales!'
i18n (1.10.0) lib/i18n/config.rb:15:in `locale='
actionview (6.1.4.3) lib/action_view/lookup_context.rb:296:in `locale='
actionview (6.1.4.3) lib/action_view/rendering.rb:21:in `locale='
i18n (1.10.0) lib/i18n.rb:74:in `locale='
i18n (1.10.0) lib/i18n.rb:326:in `with_locale'
good_job (2.12.0) engine/app/controllers/good_job/application_controller.rb:34:in `switch_locale'
activesupport (6.1.4.3) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
active_decorator (1.4.0) lib/active_decorator/view_context.rb:37:in `block (3 levels) in <module:Filter>'
active_decorator (1.4.0) lib/active_decorator/view_context.rb:25:in `run_with'
active_decorator (1.4.0) lib/active_decorator/view_context.rb:36:in `block (2 levels) in <module:Filter>'
activesupport (6.1.4.3) lib/active_support/callbacks.rb:126:in `instance_exec'
```

I might be doing something wrong, but my `config/application.rb` looks like this:

```
module Website
  class Application < Rails::Application
    config.load_defaults 6.1

    config.i18n.available_locales = [:fr, :nl]
  end
end
```

adding `:en` back in - `config.i18n.available_locales = [:fr, :nl, :en]`
that works.

I could have some time to try fix this on the weekend if you like?

**Comment by bensheldon** [comment]
Are you setting a default_locale? 

I think I assumed that there would be a default locale. I guess maybe in the absence of a default locale it should default to the first of available_locales. Does that seem right?

**Comment by brentgreeff** [comment]
I don't think I am setting a `default_locale` anywhere.

In my case - yes the first locale in `config.i18n.available_locales` is correct when it comes to the good_job_dashboard.

I didn't actually code the locale specific stuff in my app - not that experienced with it. - but am digging into it now.

**Comment by brentgreeff** [comment]
Thanks - I will do that. - thanks for putting time into this - I thought it must be somewhere in your code.
