### ISSUE TITLE
undefined method `relative_time' when include_all_helpers is false

### ISSUE THREAD

**Issue by shouichi** [bensheldon/good_job#550]
When `include_all_helpers` is set to `false`, only a helper which matches the name of the controller is included.

https://api.rubyonrails.org/classes/ActionController/Helpers.html

GoodJob engine defines some helpers in `ApplicationHelper`, thus only the `ApplicationController` (and its children) can access those helpers. Currently, the base controller is named `BaseController` and those helpers are not available.

Thank you.

**Comment by bensheldon** [comment]
@shouichi thank you for reporting this! There's likely a lot of Rails configuration assumptions being made 😓 

I can make a quick fix for this (explicitly requiring the helpers in the BaseController), unless you'd like to make the PR.

**Comment by shouichi** [comment]
Thanks for the reply!

Sure, we can quickly fix it by explicitly including the helper. I have a small question before making that change. Can we rename BaseController to ApplicationController (which is more common I believe)? That way, we can follow the rails convention.

**Comment by bensheldon** [comment]
Yep, BaseController can be renamed. I don't have much experience with Engine conventions, but change is easy 😊

**Comment by shouichi** [comment]
Thanks for the feedback. I'll submit a PR!
