### ISSUE TITLE
Improve the "Gem development" section of README?

### ISSUE THREAD

**Issue by shouichi** [bensheldon/good_job#551]
It is instructed to run `bin/setup` but it does not always work (depends on the ruby version). For example, with ruby 3.1.x, it does not work because the `matrix` gem was removed. Instead `bundle exec appraisal` should be used.

https://github.com/bensheldon/good_job#gem-development

Also, it might be a good idea to move this entire section to "CONTRIBUTING file".

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

Thank you.

**Comment by bensheldon** [comment]
@shouichi thank you for the feedback and suggestions! I'll work on improving this section.

**Comment by shouichi** [comment]
Thank you! Feel free to close this when you think it's done :+1:
