### ISSUE TITLE
Finished without Error

### ISSUE THREAD

**Issue by brentgreeff** [bensheldon/good_job#552]
It would be great to be able to filter the dashboard by jobs that have finished-successfully or with an error.

Also - how can I replay jobs that have failed - Our app will see situations where dozens or hundreds of jobs have failed because of config errors. - once the config is corrected - it would be nice to select the specific jobs ( with checkboxes next to the job, maybe ) and re-run. -

I guess I can change the state in the DB?

It would be nice if there was a convenient AR model - something I could use in the console to do updates manually on job records.
it could be generated - with a rails generator - and include some default scopes.

`GoodJobs.finished.with_error` for instance.

or even cooler

`GoodJobs.finished.with_error(ActiveRecord::RecordNotFound)`

- Is it possible to split the exception class into a different column in the `good_jobs` table?

You know - just for starters :)

**Comment by bensheldon** [comment]
@brentgreeff If you look at the `Jobs` tab of the Dashboard, it will show you "State":

<img width="202" alt="Screen Shot 2022-04-05 at 6 10 11 AM" src="https://user-images.githubusercontent.com/47554/161761223-55922879-7371-4814-b7ce-84f581ea4f51.png">

These correspond to scopes in [`GoodJob::ActiveJobJob`](https://github.com/bensheldon/good_job/blob/main/lib/good_job/active_job_job.rb#L48-L59) (in the next major version of GoodJob this will turn into the more straightforwardly named`GoodJob::Job`). There is also a method [`GoodJob::ActiveJobJob#retry_job`](https://github.com/bensheldon/good_job/blob/4b2332a1bd983768ae28452455c363473ddc2bbe/lib/good_job/active_job_job.rb#L159-L162)

For your use-case, you could write something like:

```ruby
GoodJob::ActiveJobJob.discarded.where("error LIKE ?", "%MyErrorClass%").each(&:retry_job)
```

I'll warn that these methods don't come with a contract as I don't consider them part of the public interface of GoodJob; you should write a test around your code in case they change in the future. 

> Is it possible to split the exception class into a different column in the good_jobs table?

I'm a little reluctant to add more columns for the sole purpose of making querying slightly cleaner (there's also been a request to add backtraces). If you wanted to make a new issue with use cases, I'm open to discussing.

**Comment by brentgreeff** [comment]
Hi - thanks for the detail reply.

My dashboard state select looks a bit different
I have `finished` and `unfinished` - am I correct in saying that those 2 states could then be split into `with` or `without` errors ?

Maybe its just me, or maybe I don't follow the possible states. - but from a UI perspective, - it might be nice to select either : `finished` OR `unfinished` and then have a toggle button for `successful` or `failed`

`#retry_job` - I understand that `GoodJob::ActiveJobJob` is used internally - but what about the idea of generating a AR model that people can edit that sits in their codebase? - then you can keep your `GoodJob::ActiveJobJob` private?
people can add whatever scopes they like.

Something like `rails g good_job:job_model`

Thanks for the snippets though - I will add those immediately to our project README.


### Sorry if I am conflating - I can open separate issue, but I have the following use case:

- I am sending emails in an ActiveJob - its not using ActionMailer
- I am getting a response from the external web service.
- In the case of an error - the dashboard is awesome - it gives our team a great first place to look if emails are not being delivered.
- whats much more common though is that the external service returns an http error code and message.
- In those cases, I could detect that error code, and raise an exception, so that this information is recorded into the job.
- What would be really amazing, is if I could record ALL responses from this web service on the job.

Do you have an advice in this regard?
- At the moment, I am considering creating a new AR model, saving the responses from the external service in a model
- but then in the case of a mail delivery issue - I need to look in 2 places.
- I need to check the dashboard for errors, and then check the response model for a possible HTTP error code.
- I was thinking of maybe linking my response_model to the ActiveJob table
- and then creating my own admin view that shows me both the job info and my recorded responses in a single view.

Is this not something that generally useful for a Job service?
- that it records both responses for jobs no matter if they succeed or fail?

I think that maybe `retry_on` & `retry_on_unhandled_error` are overused. - 
What I need to do is let the jobs run - record the responses I get from the external web service - and then over a few weeks, I can determine that - in these special cases - with these specific responses - I should `raise` and `retry`, - but in most cases, the job should be discarded.

I don't know, maybe my case seems overly important right now - but when the background job is communicating with a web service - I ALWAYS want to record the HTTP response, - 
and then once we get experience with the specific service, over time I would then know what jobs are worth retrying.

Do you know if I can hook into `ActiveJob::Base#perform` - and capture the return value of this method for all jobs?

Sorry for rambling.
Thanks

**Comment by bensheldon** [comment]
@brentgreeff thanks for the detailed reply! I'll try to respond to it all.

> My dashboard state select looks a bit different

You might be on an old version. This is the current GoodJob dashboard: https://goodjob-demo.herokuapp.com/good_job

> What would be really amazing, is if I could record ALL responses from this web service on the job.

You're not the first person who has asked for this, but it's not really the responsibility of the ActiveJob Backend (GoodJob). GoodJob is responsible for running your job code, as soon as possible, successfully exactly once. Even error handling is primarily following ActiveJob's semantics.

If you need to track every API call that your application is making, you should create a separate model for that in your application.

> Do you know if I can hook into ActiveJob::Base#perform - and capture the return value of this method for all jobs?

```ruby

# config/initializers/active_job.rb

Rails.application.reloader.to_prepare do
  ActiveJob::Base.around_perform do |job, block|
    result = block.call
  ensure
    # do something with result / $!
  end
end

If you don't want to do that, it's also possible to create a custom ActionMailer delivery job: https://www.bigbinary.com/blog/rails-5-2-allows-mailers-to-use-custom-active-job-class

### The way I (Ben) do job retries

I do a lot of web-scraping, which has a general problem of not knowing what errors you're going to get. I configure my jobs to retry infinitely with incremental backoff. _And_ I use Sentry (or Airbrake, etc.) to report and manage exceptions. I'll use the GoodJob dashboard to get an aggregate feel for how things are running, but I don't really use it manually. 

When I have exceptions in Sentry, I'll fix them, and deploy, and _usually_ I won't even go back and manually retry the job. It'll just happen, whenever the incremental backoff kicks in. If it's a repetitive job (e.g. scrape this website every hour), I'll use GoodJob's Concurrency Control to ensure that there is only ever 1 job (even if it's failing) on the queue. That means that when I fix the job, there isn't a cascade of jobs with duplicate behavior, there's just the 1 (the opposite strategy is to just not retry jobs that get triggered repetitively, which is also fine).

I hope that's helpful 😄

**Comment by bensheldon** [comment]
Oops, I didn't cover this:

> but what about the idea of generating a AR model that people can edit that sits in their codebase?

I think that has the same problem of just using `GoodJob::ActiveJobJob`: it will rely on an underlying code and database schema that is subject to change. You should use `GoodJob::ActiveJobJob`, and just wrap it with a lightweight test in case it does change.

**Comment by brentgreeff** [comment]
This was very helpful - thanks. - working ok with a separate model to capture the http response.

**Comment by bensheldon** [comment]
@brentgreeff happy to help! nice to discuss with you 😄
