### ISSUE TITLE
TimeTask timeouts are now ignored as these were not able to be implemented correctly

### ISSUE THREAD

**Issue by sedubois** [bensheldon/good_job#555]
My rails server using GoodJob 2.11.3 now shows the above warning upon startup. The warning disappears when removing GoodJob (when commenting out `config.active_job.queue_adapter = :good_job`).

It appears that the warning is [thrown](https://github.com/ruby-concurrency/concurrent-ruby/blob/4cfc0a107b10d3ab213396d53411a1ee487200af/lib/concurrent-ruby/concurrent/timer_task.rb#L268) by concurrent-ruby when using the option `timeout` or `timeout_interval`.

**Comment by bensheldon** [comment]
oh, that's annoying. Thanks for reporting that. I'll fix it.
