### ISSUE TITLE
how to get the number of tasks in the queue and the size of the queue?

### ISSUE THREAD

**Issue by Mr0N** [bensheldon/good_job#564]
Hello, how to get the number of tasks in the queue and the size of the queue?

**Comment by bensheldon** [comment]
You can chain query methods onto `GoodJob::ActiveJobJob`:

https://github.com/bensheldon/good_job/blob/bd5cd69428dff872bd37a0139231ddaba9058875/lib/good_job/active_job_job.rb#L48-L59

For example:

```ruby
GoodJob::ActiveJobJob.queued.count 
```
