### ISSUE TITLE
Error Job Not Preserved 

### ISSUE THREAD

**Issue by fameoflight** [bensheldon/good_job#594]
The job should be preserved if it's in error state, even if preserve_job_records is set to true. 

Also can we include call stack for last error inside the job

**Comment by bensheldon** [comment]
@fameoflight thanks for opening the issue. I think the [breaking changes planned for GoodJob 3.0](https://github.com/bensheldon/good_job/issues/507) will address your desire to preserve jobs.

Could you open a separate issue if you want to discuss design for storing backtraces? I'm open but curious (both about the use case, and also about what a usable implementation would be)
