### ISSUE TITLE
dashboard/engine – i18n: Wrong translation scope

### ISSUE THREAD

**Issue by Jay-Schneider** [bensheldon/good_job#605]
Hi there,

I encountered a problem when updating good_job from `2.14.2` to `2.15.0` regarding the hereby introduced internationalization.

The application I am running is configured to raise an exception instead of falling back to display the key in question.
When I visit the dashboard I receive a `I18n::MissingTranslationData in GoodJob::Jobs#index` stating `translation missing: en.status.scheduled`.

I figured out that this is actually a problem in the gem, where the view refers to `scope: '.status'` while the locale file actually has the translations nested under `good_job.status` (which might be the better choice here imho).
 https://github.com/bensheldon/good_job/blob/265f5bfabb07f91295840a8f3c826a3dcdd2b64e/engine/app/views/good_job/shared/_filter.erb#L10-L13

https://github.com/bensheldon/good_job/blob/265f5bfabb07f91295840a8f3c826a3dcdd2b64e/engine/config/locales/en.yml#L48-L65

So maybe the fix just constists of adjusting to scope to `.goodjob.status`?

Additionally one might consider configuring i18n to raise during tests so that such mistakes are not concealed.

Best regards 👋

**Comment by bensheldon** [comment]
@Jay-Schneider This has been released in [v2.5.1](https://github.com/bensheldon/good_job/releases/tag/v2.15.1)
