### ISSUE TITLE
Cron schedule page in dashboard not showing kwargs

### ISSUE THREAD

**Issue by baka-san** [bensheldon/good_job#608]
Very small UX issue/suggestion. The cron schedule page of the dashboard shows args but not kwargs. For example, in the following images, you can see that I have kwargs which show up in the job details page, but not the cron list.

### Can't see kwargs here
<img width="1431" alt="Screen Shot 2022-05-24 at 4 09 25" src="https://user-images.githubusercontent.com/15086337/169890580-c048f2cf-9a1d-4de8-a51a-d567a3808e05.png">

### Can see kwargs here
<img width="1431" alt="Screen Shot 2022-05-24 at 4 09 59" src="https://user-images.githubusercontent.com/15086337/169890649-73a0492c-ad75-48e6-9c14-5400669260cb.png">

**Comment by bensheldon** [comment]
Thanks for reporting! You're right! I think this was overlooked with https://github.com/bensheldon/good_job/pull/548

Is this something you'd be able to make a PR for?
