### ISSUE TITLE
Concurrency controlled jobs cause infinite loops when perform_limit is exceeded in test environments

### ISSUE THREAD

**Issue by pgvsalamander** [bensheldon/good_job#609]
If a background job created using perform_later exceeds the concurrency limit in the test environment it will get stuck in a loop:

1. perform_later is called
2. The job is executed immediately because it's running in a test environment (`execution_mode = :inline`)
3. The job throws ConcurrencyExceededError
4. The job is re-queued with a delay
5. goto 2

This is tangentially related to #591, which was initially addressed in #593 by having the job skip concurrency limits if perform_now is used.  I would expect perform_later/retry_job to ignore the limit the same way when executing inline.

Example code:
```
class InfiniteLoopTestJob < ActiveJob::Base
	include GoodJob::ActiveJobExtensions::Concurrency

	queue_as :bug_repro_job

	good_job_control_concurrency_with(
		total_limit: 2,
		perform_limit: 1,
		key: "key"
	)

	def perform(*args)
		ap "jobs to queue: #{$jobs_to_queue}"
		$jobs_to_queue -= 1
		return if $jobs_to_queue < 0

		InfiniteLoopTestJob.perform_later
	end
end

```
(Run this task with RAILS_ENV=test)
```
namespace :infinite_loop_test do
	task :run => :environment do
		$jobs_to_queue = 5

		ap "starting task"

		InfiniteLoopTestJob.perform_later
	end
end
```

Output:
```
"starting task"
"jobs to queue: 5"
rails aborted!
SystemStackError: stack level too deep
/home/user/git_repos/repo/app/jobs/infinite_loop_test_job.rb:17:in `perform'
/home/user/git_repos/repo/lib/tasks/infinite_loop_test.rake:9:in `block (2 levels) in <main>'
/home/user/git_repos/repo/bin/rails:5:in `<top (required)>'
/home/user/git_repos/repo/bin/spring:10:in `block in <top (required)>'
/home/user/git_repos/repo/bin/spring:7:in `tap'
/home/user/git_repos/repo/bin/spring:7:in `<top (required)>'
Tasks: TOP => infinite_loop_test:run
(See full trace by running task with --trace)
```

**Comment by bensheldon** [comment]
@pgvsalamander oops! You're totally right. Looks like there should be another guard here that bails if the adapter is an inline one:

https://github.com/bensheldon/good_job/blob/c8f19ee54b92e20e1f67bcb71b0ed7daebac58be/lib/good_job/active_job_extensions/concurrency.rb#L17-L21

Is that a PR you'd be able to make?

**Comment by bensheldon** [comment]
I made a PR to ignore `perform_limit` when the adapter is inline.

This does make me wonder whether the Inline adapter should have different behavior. The inline adapter's use case is in the test environment. I'm thinking that Inline should execute inline _once_ and then either:

- The exception is raised (e.g. it ignores retry handlers)
- The job is re-enqueued via the retry-handler, but is treated as if the execution mode is `:external` e.g. the job is stored to execute in the future, but it won't be executed by the inline adapter.

I'll make another issue to discuss.

**Comment by pgvsalamander** [comment]
> The exception is raised (e.g. it ignores retry handlers)

I don't think it should always raise an exception.  In my case a job causing another instance of itself to be queued is the desired behavior, and I imagine it may be for others as well.

I can't get into too may details but for my case I have a job A that maintains some preprocessed calculations for items in the database, and depending on the state of the calculations queues job B to do additional work on more items.  This eventually flows back to queueing job A to update the first item again, which does not queue job B this time as the calculations would be fully up to date at this point.  This works great when running in the async environment as it allows me to insert updated data at any point in the workflow and the jobs will run and queue additional jobs as necessary, always returning to a deterministic state.

> The job is re-enqueued via the retry-handler, but is treated as if the execution mode is :external e.g. the job is stored to execute in the future, but it won't be executed by the inline adapter.

Perhaps there could be some method to run all the jobs in the queue inline at that point?  That would allow better control over where/when the jobs in the test execute.



An alternative option is that if you're currently executing a job, you could send any further jobs to the queue and then run them once the current job exits.  This would ensure that two jobs don't overlap while still allowing jobs to run immediately within tests.



I have also encountered some issues where the job never runs because there are jobs from previous tests still in the DB causing it to exceed the total_limit.  It's not really a bug, but it may be relevant to the changes made because of this discussion.

**Comment by bensheldon** [comment]
@pgvsalamander sorry, I've slept on this one too many nights. I think I'm leaning now toward your suggestion:

>  if you're currently executing a job, you could send any further jobs to the queue and then run them once the current job exits. This would ensure that two jobs don't overlap while still allowing jobs to run immediately within tests.

I think that would resolve the stack-level-too-deep problem. Here's my thoughts:

- When in an inline adapter, if you enqueue inside of an already executing job, the job is put into the external queue.
- At the end of the outermost inline enqueing/execution, the inline adapter will then loop over and execute all of the jobs in the external queue
- Have a callable/public adapter method like `ApplicationJob.queue_adapter.execute_inline` that does the looping over and executing of all of the jobs on the external queue.
- [breaking change?] subsequently, I think inline should only execute jobs that are immediate/past-due-scheduled. That would ensure that:
  - Instead of stack-level-too-deep, infinite retries with backoff does not result in an infinite loop [similarly bad to current behavior, maybe even worse because it will hang rather than blow up]
  - You could use timecop/time-travel in your tests to execute scheduled jobs (e.g. `travel_to(5.minutes.from_now) { ApplicationJob.queue_adapter.execute_inline }`) and have better behavior than currently.

**Comment by bensheldon** [comment]
@pgvsalamander thank you for all of the feedback and suggestions. I just put together a pull request that I think addresses your needs, and is a good improvement: https://github.com/bensheldon/good_job/pull/615

**Comment by pgvsalamander** [comment]
No, thank you for the rapid implementation!  GoodJob is quickly becoming a core component of our project and I don't know how we'd get anything done without it.

**Comment by bensheldon** [comment]
@pgvsalamander I just released v2.16.0 that includes #617

**Comment by pgvsalamander** [comment]
I'm not sure how you prefer to handle issue tickets, are you expecting me to close this issue now that the update is released or would you like it left open for future discussion?

**Comment by bensheldon** [comment]
@pgvsalamander no sweat. I can close this out.
