### ISSUE TITLE
Should `:inline` adapter mode retry jobs?

### ISSUE THREAD

**Issue by bensheldon** [bensheldon/good_job#611]
This came up in #609. 

Currently, when GoodJob is in inline execution mode and a job raises an exception that hits a `retry_on` handler, the job will be immediately re-executed and ignore any incremental backoff. This can happen recursively until the job hits stack-level too deep. This is not a great experience.

The inline adapter's primary use case is in the test environment, especially for integration testing. 

I'm thinking that he behavior of inline should change. Instead, Inline would execute once and then either:

A. The exception is simply raised e.g. it ignores retry handlers. Maybe GoodJob could raise a slightly different error specifically on retries (e.g. `GoodJob::RetriedInlineError` with the original error inside it)
B. The job is re-enqueued via the retry-handler, but is treated as if the execution mode is :external e.g. the job is stored to execute in the future, but it won't be executed by the inline adapter.

I'm thinking about this carefully because there are some overlapping concerns:

- I don't think there is _any_ value to recursively retrying jobs until it gets to stack-level too deep.
- I do see value in someone to have visibility into an exception in their job (and not have it masked with stack-level too deep)
- I do see there being value in someone wanting to test that a `retry_on` handler is working

Is there any other thoughts/concerns/ideas that might help drive this towards an improvement?

**Comment by pgvsalamander** [comment]
Perhaps there could be a limit set for the adapter on how many times a job can be retried while running with :inline (`config.good_job.max_inline_retries`?).  If a job fails and retries 10 times with no limit in the retry_on you could raise your error to break out of the loop.  That would allow people to test that their retry_on handler is working properly, and give some confidence that the error in the job wasn't a fluke that would be resolved if the job just runs again.

(copied from my [other comment](https://github.com/bensheldon/good_job/issues/609#issuecomment-1137426651)) Another option is that if you're currently executing a job, you could send any further jobs to the queue and then run them once the current job exits.  This would solve the stack depth issue at least, although you could still get yourself stuck in an infinite loop if your job always fails.

**Comment by bensheldon** [comment]
@pgvsalamander Thanks for the feedback. Can you share how you're using the Inline adapter? 

Eg is it just in test? What kind of tests (eg unit testing jobs or models or controllers). And also what kind of exceptions your handling?

**Comment by pgvsalamander** [comment]
I'm just using it in some unit tests.  My jobs are part of a larger system that gets attached to models as a concern, so I'm interacting with the models in my tests which cause the jobs to be executed.

I'm not doing any special exception handling in the jobs (aside from always retrying on concurrency exceptions), that was just a general though of something we could do - I don't have a good example for it.  I do have some other jobs that interact with external services which do fail occasionally and need to be retried (e.g. the service is overloaded and times out, etc), but that's not something I have testing around so I haven't run into that issue with the inline adapter.

**Comment by bensheldon** [comment]
@dillonhafer ugh, sorry about that. If you set the configuration variable mentioned in the notice, it should not output the deprecation.

**Comment by dillonhafer** [comment]
I'm not sure where the discussion about inline adapter usage is, but my main question is this: In order to upgrade to good_job 3.0 will I need to go to each of my 237 specs that raise the warning and wrap them in a travel_to block in order for the jobs to be run in the test? That would defeat the purpose of running them inline. Or do I need to override perform_later on my ApplicationJob in the test env?

**Comment by bensheldon** [comment]
@dillonhafer try setting the config and tell me how many tests fail. If you aren't asserting on the behavior, it'll be a noop. 

If it is a huge amount of failures, let me know and I'll reopen whether to add an additional mode of "inline_now".

**Comment by dillonhafer** [comment]
I'm also wondering if I'm not testing properly and this is all my own fault.

My failures seem to be around how to test job failures.

A lot of my error tests are written like this (because GoodJob raises the exception?)
```ruby
      it "raises the error" do
        allow(ApiAdapter).to receive(:make_request).and_return(ApiError[ok: false])
        expect {
          MyJob.perform_now
        }.to raise_error("Error when contacting API")
      end
```

When setting the `inline_execution_respects_schedule` to true, perform_now no longer raises the error, but instead returns it.

So am I simply testing wrong?


With config
<img width="738" alt="config-true" src="https://user-images.githubusercontent.com/1136388/175569416-0f9bd065-e420-4720-9ea6-3ae869bb5361.png">


Without config:

<img width="967" alt="config-false" src="https://user-images.githubusercontent.com/1136388/175569459-96fb003c-a48b-4805-a6a5-fddb05393bbd.png">

**Comment by dillonhafer** [comment]
So I'm wondering if I just need to rewrite my test to assert that perform_now returns an error instead of expecting an error to be raised?

**Comment by bensheldon** [comment]
@dillonhafer no one tests ActiveJob the same way 🤗 

I think there's a couple things happening here.

- `perform_now` never touches the queue adapter (GoodJob); ActiveJob runs it directly. That's how ActiveJob works. 
- I _think_ what is happening is that your `perform_now` is raising an exception, which is getting caught in a retry_on handler, and then being `perform_later`ed with an exponential backoff _into_ the queue adapter (GoodJob).
- Prior to you setting the `inline_execution_respects_schedule = true` flag, GoodJob just ran the job several more times until the retry_on count was exhausted, and then the error was raised.
- When `perform_now` raises an error that is caught by a retry_on handler, the exception is returned.

This is where unit testing ActiveJob is _hard_ (or at least wildly inconsistent). There's a couple of different strategies.

- You can unit test `#perform` directly with `MyJob.new.perform`. This will sidestep any error handling/retry hooks (good), but if you have any functional `*_perform` blocks, they won't be tested (bad)
- You can unit test using `perform_now`, but that now means that all those error handling/retry hooks have been added into the mix. But `perform_now` sidesteps the queue adapter, which can be surprising, and you have to pay attention to the interface, like it returns errors instead of raising them (unless you exhaust the retry handler, in which case they're raised, unless it is given a block, etc.).
- You can unit test using `perform_later`, which utilizes the queue adapter. Which then puts your tests at the mercy of queue adapter changes (sorry!).
- You can use the [ActiveJob TestAdapter](https://api.rubyonrails.org/classes/ActiveJob/QueueAdapters/TestAdapter.html) which is probably the most _unit_ testing of all the options, but that also means you should be using the test helpers. Looks like you're using [RSpec](https://relishapp.com/rspec/rspec-rails/docs/job-specs/job-spec).

In my personal applications, I use the ActiveJob Test Adapter in all my unit tests (jobs, models, controllers), and _only_ use the GoodJob inline adapter in my System Tests. But like I say, I haven't seen consistency across developers. 

My recommendations to move you forward expediently:

Change your tests so that they assert on the return value, instead of a raise. (this assumes that you want your tests to reflect that the error was caught in a retry handler)

**Comment by dillonhafer** [comment]
Oh wonderful! Thank you, ActiveJob TestAdapter is actually what I wanted all along. 🤦 I made two changes and I feel this is much better and actually what I wanted all along:

```ruby
# application.rb
config.active_job.queue_adapter = Rails.env.test? ? :test : :good_job
```

```
# rails_helper.rb
config.around(:each) do |example|
  perform_enqueued_jobs do
    example.run
  end
end
```

And now background jobs always run and my suite is passing.

**Comment by bensheldon** [comment]
Closed because the behavior has been updated in #615.
