### ISSUE TITLE
dashboard "delete all" does not work

### ISSUE THREAD

**Issue by jrochkind** [bensheldon/good_job#630]
Trying out good_job.  (good_job `2.16.1`). 

In the dashboard, I can delete a single job. But if I try the "delete all" icon in column header, I get an alert saying "No jobs were destroyed", and indeed the jobs are still there. 

<details>
<summary>
Screen recording:
</summary>

![delete](https://user-images.githubusercontent.com/149304/175337796-e73861e6-90f4-4618-ab17-7b33364c49dc.gif)
</details>

No errors present in Application log:

```
Started PUT "/admin/good_job/jobs/mass_update?locale=en&state=finished" for ::1 at 2022-06-23 11:31:30 -0400
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ config/routes.rb:9:in `matches?'
Processing by GoodJob::JobsController#mass_update as HTML
  Parameters: {"authenticity_token"=>"[FILTERED]", "mass_action"=>"destroy", "locale"=>"en", "state"=>"finished"}
Redirected to http://localhost:3000/admin/good_job/jobs?locale=en&state=finished
Completed 302 Found in 1ms (ActiveRecord: 0.0ms | Allocations: 476)
```

**Comment by bensheldon** [comment]
Thanks for flagging this! The buttons only act upon items that have been checked. If nothing is checked, then nothing will be acted upon.

There is a bit of a visual distance between the checkboxes and the action buttons, so I'm not sure how to conceptually link think. 

Idea: Disable the buttons unless any rows are checked. 

(Still might benefit from some kind of on-hover or text that explains their functionality)

**Comment by jrochkind** [comment]
OK though, that enticing `if params[:all_job_ids] ` in the sourcecode though.. 

is there a way in the UI to trigger that, to really delete _everything_ (possibly across multiple paginated sets)?  I wasn't sure if "delete all" was going to do that. Should there be a way to do that? Say if you have thousands to delete, more than fit on screen to check. (Say, for instance in the [heroku-deployed demo I found](https://www.google.com/search?q=good_job+heroku+demo&rlz=1C5CHFA_enUS996US996&oq=good_job+heroku+demo&aqs=chrome..69i57j33i10i160l3.1911j0j7&sourceid=chrome&ie=UTF-8)! Which is really slow, possibly cause it's got so many jobs!)

(Not sure if this feature is needed or not in a normal app for most people, I am not yet using this in production, so don't know what my usage patterns or needs will be for sure).
