### ISSUE TITLE
"uninitialized constant GoodJob::Execution" in development env

### ISSUE THREAD

**Issue by doits** [bensheldon/good_job#634]
Trying to enqueue Rails' job in development mode:

```rb
TestJob.perform_later
```

... gives:

```
Failed enqueuing TestJob to GoodJob(default): NameError (uninitialized constant GoodJob::Execution

      execution = GoodJob::Execution.enqueue(
                         ^^^^^^^^^^^
Did you mean?  Exception)
/.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/good_job-2.17.0/lib/good_job/adapter.rb:72:in `enqueue_at': uninitialized constant GoodJob::Execution (NameError)

      execution = GoodJob::Execution.enqueue(
                         ^^^^^^^^^^^
Did you mean?  Exception
```

To fix it I can do a `require 'good_job/execution'`. Looks like autoloader does not catch it?

- Happens on GoodJob `2.17`.
- `2.16.1` works fine.
- Production and Test env are not affected, seems like only development
- Rails 7.0.3
- Ruby 3.1.2

Can you reproduce it? I'll provide more details if you need them.

**Comment by bensheldon** [comment]
@doits thanks for being quick to upgrade to the new version, and flagging this. Let me try to reproduce on a new project and I'll get this fixed.

I'm going to assume that you haven't mounted the Dashboard? (that shouldn't be required, but I'm still learning about how Engines and autoloading work apparently)

**Comment by doits** [comment]
Thanks for you quick help! If you cannot reproduce it, please ping me, so I can try my best to do so.

> I'm going to assume that you haven't mounted the Dashboard?

That is correct.

**Comment by bensheldon** [comment]
I'm not able to (easily) reproduce it.

```
rails new lograge_repro \
	-d postgresql \
  --no-assets \
	--skip-action-text \
  --skip-action-mailer \
  --skip-action-mailbox \
  --skip-action-cable \
  --skip-sprockets \
  --skip-listen \
  --skip-javascript \
  --skip-turbolinks \
  --skip-system-test \
  --skip-test-unit \
  --skip-bootsnap \
  --skip-spring \
  --skip-active-storage

bundle add good_job

bin/rails db:create

bin/rails g good_job:install

bin/rails db:migrate
```

and then edit `config/application/rb` to add `config.active_job.queue_adapter = :good_job`.

I'm able to run `bin/rails s` and see GoodJob make successful database queries with `GoodJob::Execution`.

😬

**Comment by doits** [comment]
For me it seems to be the gem `stringex`.

@bensheldon can you reproduce it in your test app after `bundle add stringex`?

**Comment by doits** [comment]
Glad you could reproduce it!

Not sure who is to blame though, maybe `stringex` messes up the autoloader (at least it monkey patches `String`, so who knows ...)

**Comment by redareda9** [comment]
Same problem here. 
And it's random. 
The first execution of the JOB works perfectly. Then, a few executions later, it suddenly stops working and gives me the Uninitialized constant, which is really weird/unpredictable and hard to reproduce.

**Comment by bensheldon** [comment]
I think I have a fix in #635: 

> My hypothesis is that when the model files are in gem `app` they are managed by Rails's autoloader, which is lazy-loaded, but the model files are sometimes referenced from gem `lib` which is eager-loaded, and that causes pain.

**Comment by bensheldon** [comment]
I've release https://github.com/bensheldon/good_job/releases/tag/v2.17.1 which I hope fixes this. Please confirm 🙏🏻

**Comment by doits** [comment]
Fixed it for me 👍

**Comment by dillonhafer** [comment]
Fixed it for me, I was able to remove the `require "good_job/engine"`

**Comment by bensheldon** [comment]
Thanks everyone! 🎉
