### ISSUE TITLE
How to suppress repetitive logs in development?

### ISSUE THREAD

**Issue by sedubois** [bensheldon/good_job#658]
This gets printed every 10 seconds in my development environment:
```rb
  GoodJob::Execution Load (0.6ms)  SELECT "good_jobs".* FROM "good_jobs" WHERE "good_jobs"."id" IN (WITH "rows" AS MATERIALIZED ( SELECT "good_jobs"."id", "good_jobs"."active_job_id" FROM "good_jobs" WHERE "good_jobs"."finished_at" IS NULL AND ("good_jobs"."scheduled_at" <= '2022-07-10 08:44:41.505487' OR "good_jobs"."scheduled_at" IS NULL) ORDER BY priority DESC NULLS LAST ) SELECT "rows"."id" FROM "rows" WHERE pg_try_advisory_lock(('x' || substr(md5('good_jobs' || '-' || "rows"."active_job_id"::text), 1, 16))::bit(64)::bigint) LIMIT $1) ORDER BY priority DESC NULLS LAST  [["LIMIT", 1]]
  GoodJob::Lockable Unlock Session (0.2ms)  SELECT pg_advisory_unlock_all()::text AS unlocked
```

It's mentioned in https://github.com/bensheldon/good_job/issues/455#issuecomment-972992699 that there shouldn't be any polling, however AFAIK I didn't configure anything specific in this regard, here is my initializer:

<details>

```rb
Rails.application.configure do
  config.good_job.preserve_job_records = true
  config.good_job.retry_on_unhandled_error = false
  config.good_job.on_thread_error = -> (exception) do
    Sentry.set_extras(good_job_on_thread_error: true)
    Sentry.capture_exception(exception)
  end
end

ActionMailer::MailDeliveryJob.retry_on StandardError,
                                       wait: :exponentially_longer, attempts: Float::INFINITY
ActionMailer::MailDeliveryJob.around_perform do |_job, block|
  block.call
rescue StandardError => e
  Sentry.set_extras(action_mailer_standard_error: true)
  Sentry.capture_exception(e)
  raise
end
```

</details>

How can the polling be disabled, or what is otherwise the recommended way to avoid those repetitive logs while developing?

Using Rails 7.0.3, GoodJob 3.0.1.

**Comment by bensheldon** [comment]
That's weird. Can you try running in your console (or `puts` it after the initializer)

```ruby
GoodJob::Configuration.new({}).poll_interval
```

Here's where that's calculated: https://github.com/bensheldon/good_job/blob/eebf63fd3bb614774c9801c978ebea617ca69f57/lib/good_job/configuration.rb#L106-L120

**Comment by sedubois** [comment]
Okay my mistake, `config.good_job.poll_interval = 10 # seconds` was defined in application.rb since starting to use GoodJob 2.4.0. Probably a misunderstanding in how to configure GoodJob back then.

**Comment by bensheldon** [comment]
fhew! 😅
