### ISSUE TITLE
Use timestamps with timezone when set as the default for postgresql.

### ISSUE THREAD

**Issue by thomasdziedzic** [bensheldon/good_job#668]
I have the following in `config/initializers/active_record.rb`:

```ruby
require "active_record/connection_adapters/postgresql_adapter"
ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.datetime_type = :timestamptz
```

As documented in https://guides.rubyonrails.org/configuring.html#activerecord-connectionadapters-postgresqladapter-datetime-type which sets the default to use `timestamp with time zone`.

When I installed good_job with `bin/rails g good_job:install` and ran `bin/rails db:migrate` it used timestamps without a timezone for the good_job fields and a datetime for the created_at and updated_at columns:

```ruby
    t.timestamp "scheduled_at"
    t.timestamp "performed_at"
    t.timestamp "finished_at"
...
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
...
    t.timestamp "cron_at"
```

I am trying to use timestamps with timezones throughout my application, so I was wondering:

1. Would it be possible for good_job to use the value for `ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.datetime_type` to generate the good_job migration?
2. Could I change the timestamps to a datetime in the migration without issue?

**Comment by bensheldon** [comment]
Yep, I don't foresee any problems with your configuration. I would expect GoodJob's migration to pick up the base configuration. GoodJob is not doing anything special with ActiveRecord.

**Comment by bensheldon** [comment]
Oh, also thank you for flagging the inconsistency of timestamp vs datetime. They should be functionally equivalent and is just an inconsistent oversight on my part.

**Comment by bensheldon** [comment]
@thomasdziedzic I wanted to follow-up. Are you successful in creating GoodJob timestamps with timezones?

**Comment by dillonhafer** [comment]
I use the same postgres initializer and it appears to use `timestamptz` for me
<img width="672" alt="Screenshot 2022-12-18 at 13 31 49" src="https://user-images.githubusercontent.com/1136388/208313444-41c0f527-73b2-4587-a0dd-c3263300d486.png">

**Comment by thomasdziedzic** [comment]
@bensheldon I can confirm that I've been successfully using timestamps with timezones on the good_job tables.
