### ISSUE TITLE
Calculating database connections

### ISSUE THREAD

**Issue by esasse** [bensheldon/good_job#669]
I'm trying to understand the correct size for my database pool. I'm following the information in the readme but one part is not clear to me:

> 1 connection per query pool thread e.g. --queues=mice:2;elephants:1 is 3 threads. Pool thread size defaults to --max-threads

I use only default Rails queues (default and mailers). So it should be 2? One for each queue? I also don't specify --max-threads.

I'm using cron scheduler and running async. I tried using the suggested formula:

```ruby
pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5).to_i + 3 + ENV.fetch("GOOD_JOB_MAX_THREADS", 5).to_i %>
```

But I'm still getting `ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.002 seconds); all pooled connections were in use` from time to time.

Thanks!

**Comment by bensheldon** [comment]
@esasse Can you share the setting you're using for `GOOD_JOB_QUEUES=`?

If you're using all default values (e.g. `GOOD_JOB_QUEUES=* GOOD_JOB_MAX_THREADS=5`) then the formula there _should_ be the correct one: 
- One pool of 5 executor threads, pulling job from default and mailers, each with their own database connection = 5 connections.
- One LISTEN/NOTIFY connection = 1 connections.
- Goodjob Cron enqueuer = 2 connections.

= 8 db connections for GoodJob 

+ the Puma web threads = 5 db connections

= 13 db connections total.

Are you doing any other custom multithreading within your Rails Application?

**Comment by esasse** [comment]
I'm using all default values and not doing any other custom multithreading (not that I'm aware of).

**Comment by bensheldon** [comment]
@esasse are you seeing this in Development or Production? (it's a little easier to help debug in Development). 

I want to also say there isn't a downside to over-provisioning the pool-side. If you try bumping it up by 1 or 2, does that fix it?

**Comment by esasse** [comment]
Production. I will try to bump it up and reopen the issue if that doesn't fix it. Thanks!

**Comment by esasse** [comment]
> I want to also say there isn't a downside to over-provisioning the pool-size. If you try bumping it up by 1 or 2, does that fix it?

I bumped by 2 last month but I'm still getting this error once a day. Any other ideas? Thanks!

**Comment by bensheldon** [comment]
@esasse nuts! Would you be able to run `self.total_estimated_threads(warn: true)` in a Production console and share the output? I added that in #645.

Also, I'm curious if you're seeing that error from all places within your app, or just somewhere within GoodJob, or in the exact same place? (i.e. is there any pattern with the backtrace). Thank you!

**Comment by esasse** [comment]
> @esasse nuts! Would you be able to run `GoodJob.total_estimated_threads(warn: true)` in a Production console and share the output? I added that in #645.

```
irb(main):002:0> GoodJob::Configuration.total_estimated_threads(warn: true)
=> 3
```

> Also, I'm curious if you're seeing that error from all places within your app, or just somewhere within GoodJob, or in the exact same place? (i.e. is there any pattern with the backtrace). Thank you!

Always in the exact sample place and it's not a background job, so it's not directly related to GoodJob, but it started exactly when I moved this project to GoodJob.

**Comment by bensheldon** [comment]
@esasse thanks! oh nuts, I realized that in a production console, it won't output the true number of threads if it were actually running `async`. So that's not very useful. Could you try this instead:

```ruby
puts "queue_string: #{GoodJob.configuration.queue_string}\nmax_threads: #{GoodJob.configuration.max_threads}\npool_size: #{GoodJob::Execution.connection_pool.size}"
```

Also, are you seeing the `ActiveRecord::ConnectionTimeoutError` error at the same time that your cron jobs are scheduled to run? Could you share your cron configuration?

**Comment by esasse** [comment]
I didn't see the error for almost two weeks. I'll reopen the issue if it comes back. Thanks, Ben!

**Comment by esasse** [comment]
@bensheldon the error was back yesterday.

```ruby
irb(main):001:0> puts "queue_string: #{GoodJob.configuration.queue_string}\nmax_threads: #{GoodJob.configuration.max_threads}\npool
_size: #{GoodJob::Execution.connection_pool.size}"
queue_string: *
max_threads: 5
pool_size: 15
```

> Also, are you seeing the ActiveRecord::ConnectionTimeoutError error at the same time that your cron jobs are scheduled to run? Could you share your cron configuration?

Yes. I have a cron job scheduled for the same time the error happens. I could change the time of this job if it helps in some way.

**Comment by bensheldon** [comment]
@esasse I'm still at a loss, but maybe poking away at this will help uncover the problem. Is it only a single cron job, or are there multiple cron jobs all scheduled at the same time (and how many)?

**Comment by esasse** [comment]
I did not see the issue anymore after changing the schedule time.
