### ISSUE TITLE
Add `cron_enabled` to Process state

### ISSUE THREAD

**Issue by bensheldon** [bensheldon/good_job#673]
Whether cron is enabled should show up in the state hash in the Process view on the dashboard.

<img width="1510" alt="Screen Shot 2022-07-21 at 6 56 59 AM" src="https://user-images.githubusercontent.com/47554/180231795-8cfb89d8-83f6-4c50-ae4a-7379e888d138.png">

**Comment by saksham-jain** [comment]
@bensheldon Created PR #675 for this issue.

**Comment by bensheldon** [comment]
Thank you @saksham-jain 🎉
