### ISSUE TITLE
Uninitialized constant GoodJob::JobsController

### ISSUE THREAD

**Issue by mdavidn** [bensheldon/good_job#674]
I can consistently break `good_job`'s code reloading in my app, confirmed in Rails 6.1 and 7.0.

I never need `good_job` to reload its code while my application is running, so it's not clear to me why `zeitwerk` is a runtime dependency. #87 didn't shed any light on this. Perhaps it should be a development dependency?

### Steps to reproduce

1. Create a new Rails app
2. Add `good_job`, mount engine
3. Start and wait for server
4. Make _any_ change to application code
5. Try http://localhost:3000/good_job.

```sh
gem install rails
rails new good_job_demo --database=postgresql
cd good_job_demo
bundle add good_job
bin/rails generate good_job:install
bin/rails db:create db:migrate
cat <<RUBY > config/routes.rb
Rails.application.routes.draw do
  mount GoodJob::Engine => 'good_job'
end
RUBY
bin/rails server

open http://localhost:3000/good_job # Confirm working, optionally

touch config/routes.rb # or app/controllers/application_controller.rb 
open http://localhost:3000/good_job # Broken
```

**Comment by bensheldon** [comment]
@mdavidn thank for opening this issue. I'll try to reproduce it.

btw, I don't _think_ the problem is Zeitwerk. GoodJob uses Zeitwerk as a convenience to avoid writing `require` statements in `lib`; controllers are autoloaded by Rails via the Rails Engine (not that I presume to understand how Engines work).

**Comment by bensheldon** [comment]
@mdavidn sorry to not follow up earlier. In #677, I removed Zeitwerk entirely. Could you see if the latest release of GoodJob fixes this problem for you?

**Comment by morgoth** [comment]
@bensheldon it fixes the issue for me mentioned in https://github.com/bensheldon/good_job/issues/646

**Comment by mdavidn** [comment]
@bensheldon I confirmed this morning that 3.4.1 does not have this issue.

`Rails::Engine` does provide [a hook to add paths](https://github.com/rails/rails/blob/82bab92cfe9ab62793cc82d25e6662e4359352e9/railties/lib/rails/engine.rb#L47) to the Zeitwerk loaders managed by Rails, but I would be reluctant to modify global inflectors in a gem. Explicit requires may be the best approach. (The [behavior matching `app/*`](https://github.com/rails/rails/blob/82bab92cfe9ab62793cc82d25e6662e4359352e9/railties/lib/rails/engine/configuration.rb#L46-L50) is `eager_load_paths`.)
