### ISSUE TITLE
Do we need to implement concurrency with scheduled cron jobs?

### ISSUE THREAD

**Issue by adeeb1** [bensheldon/good_job#690]
Hi, and thank you for your amazing work on this gem! Under the [Cron section](https://github.com/bensheldon/good_job#cron-style-repeatingrecurring-jobs) of the README, it states:

>Cron-style jobs are run on every GoodJob process (e.g. CLI or async execution mode) when config.good_job.enable_cron = true, but GoodJob's cron uses unique indexes to ensure that only a single job is enqeued at the given time interval.

Let's say I have two VMs each running GoodJob workers, and I'd like a daily cron job to run only one time each day. Would the default cron unique index work for this use case, or do I also need to implement concurrency to ensure the job runs only once?

**Comment by bensheldon** [comment]
@adeeb1 great question!

GoodJob cron will handle concurrency on its own. You do not need to implement concurrency separately.

You can double-check that. Your database should have a unique compound index on `cron_key, cron_at`: 

https://github.com/bensheldon/good_job/blob/8990bc073681cebffcf69fa611f6838d005f64c5/spec/test_app/db/schema.rb#L52

The `cron_at` column should be populated with the cron job's scheduled time, and thus prevent duplicate jobs from being enqueued at the same time.

**Comment by adeeb1** [comment]
Thanks for the quick response @bensheldon! At what point does it create this record? On server initialization? I had some difficulties finding the logic, so any pointers would be helpful.

**Comment by bensheldon** [comment]
GoodJob's cron implementation enqueues the ActiveJob job at the scheduled time. That timing is managed with `Concurrent::ScheduledTasks`: https://github.com/bensheldon/good_job/blob/8990bc073681cebffcf69fa611f6838d005f64c5/lib/good_job/cron_manager.rb#L84-L99

Here's where the CronEntry model rescues the duplicate entry: https://github.com/bensheldon/good_job/blob/8990bc073681cebffcf69fa611f6838d005f64c5/app/models/good_job/cron_entry.rb#L103-L113

**Comment by adeeb1** [comment]
Wonderful, thank you @bensheldon! I greatly appreciate the quick response.
