### ISSUE TITLE
Broken upgrade to v3.

### ISSUE THREAD

**Issue by stas** [bensheldon/good_job#703]
Hi there,
I'm upgrading `good_job` from v2 to v3 and it looks like the migration instructions are incomplete.

Running:
```sh
/app # bin/rails g good_job:update
        skip  db/migrate/20220815115425_create_good_jobs.rb
        skip  db/migrate/20220815115425_create_good_job_settings.rb
```

But then starting the queue:
```
/app # bundle exec good_job
[GoodJob] [375] GoodJob started scheduler with queues=* max_threads=5.
[GoodJob] Notifier subscribed with LISTEN
[GoodJob] Notifier unsubscribed with UNLISTEN
[GoodJob] Notifier errored: ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "good_job_processes" does not exist
LINE 9:  WHERE a.attrelid = '"good_job_processes"'::regclass

```

I'll be adding manually the missing migrations, not sure though how this could have happened.

**Comment by bensheldon** [comment]
Hmmm. Did you upgrade through v2.99 and generate the migrations for v2.99?

I squash down the migrations every major release.

**Comment by stas** [comment]
I did run the update and the only migration that was generated was:
```
db/migrate/20220815115425_create_good_job_settings.rb
```

Btw, manually bringing the missing migrations worked.

**Comment by bensheldon** [comment]
If you got the migration for settings, that would mean you ran the update generator for a 3.x version, rather than 2.99. 

I'm glad that you were able to copy over the old migrations 👍
