### ISSUE TITLE
Support Sequel

### ISSUE THREAD

**Issue by censoredp** [bensheldon/good_job#713]
Currently GoodJob supports only ActiveRecord for database connectivity. [Sequel](https://github.com/jeremyevans/sequel) is more powerful and very popular alternative. There's also a [gem](https://github.com/TalentBox/sequel-rails) that helps with integration into rails.

Also sequel has [`listen` method](https://sequel.jeremyevans.net/rdoc-adapters/classes/Sequel/Postgres/Database.html#method-i-listen) and [extension for advisory locks](https://github.com/yuryroot/sequel-pg_advisory_lock).

**Comment by bensheldon** [comment]
@censoredp thanks for suggesting this. I don't plan to add support for GoodJob; I think GoodJob is too tightly architected around ActiveRecord. 

I'd be happy to advise someone else who believed otherwise and wanted to build an extension for GoodJob or their own Sequel-powered ActiveJob backend.
