### ISSUE TITLE
Changing assets path?

### ISSUE THREAD

**Issue by shouichi** [bensheldon/good_job#717]
We run rails behind nginx and nginx serves all static assets (e.g., css).

```
location ~* /assets|packs/ {
    access_log off;
    add_header Cache-Control public;
    gzip_static on;
    expires max;
}
```

This prevents loading good job assets because they are under `/assets` and nginx doesn't forward requests to rails. I believe this kind of setup is common. Can we change the path to something like `/good_job_assets` to avoid the collision? Thank you.

**Comment by shouichi** [comment]
Sorry, the nginx config was simply wrong. Needed a `^` so that it only matches urls starting with `/assets`. Without the caret sign, it matches urls containing `/assets`.

```
location ~* ^/assets|packs/ {
    access_log off;
    add_header Cache-Control public;
    gzip_static on;
    expires max;
}
```

**Comment by bensheldon** [comment]
@shouichi no worries! Happy you figured out the problem 😄
