### ISSUE TITLE
Assert cancelled jobs

### ISSUE THREAD

**Issue by jofrly** [bensheldon/good_job#724]
Hi!

My application schedules jobs and utilizes the `.set(wait: ...` alot.

Sometimes, I cancel jobs when certain events occur in the application.
I do that by destroying the record in the `good_jobs` table.

```
GoodJob::Execution.where(id: provider_job_id).take.destroy
```

My application grows in complexity so I want to introduce some tests.
I'd like to test one part of the application where a job gets cancelled like explained above.

However the `assert_enqueued_jobs` helper does not "respect" the cancelled jobs.
Is there another way to assert enqueued jobs?

I tried to query them like this

```
GoodJob::Execution.job_class(MyJob).size
```

However that always returns 0 in the test environment somehow.
Scheduling, cancelling and querying them in the way I mentioned works fine in other environments though...

Thankful for any help / advice.

**Comment by jofrly** [comment]
@bensheldon thanks so much for answering so quickly!

The `active_job.queue_adapter` is set to `:good_job` and the execution mode is set to `:inline`. I tried to set it to `:external` but that didn't change anything regarding the tests.

I noticed I was on `good_job (2.9.1)` so I created a new repo with `good_job (3.5.0)` just to test if that changes something: https://github.com/jofrly/goodjobtest/commit/1b19f1d6bd3fef50dda9f5942df9ed9798ce2fe0

I created a job [`SendNotificationJob`](https://github.com/jofrly/goodjobtest/blob/main/app/jobs/send_notification_job.rb) and a test [`SendNotificationJobTest`](https://github.com/jofrly/goodjobtest/blob/main/test/jobs/send_notification_job_test.rb) which schedules the job and then prints out `GoodJob::Execution.count` and `GoodJob::ActiveJobJob.count`.

My assumption is to see a `1` in the output but when running `rails test` I get zeroes:

```
Running 1 tests in a single process (parallelization threshold is 50)
Run options: --seed 25153

# Running:

0
0
.

Finished in 0.021458s, 46.6027 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

So I'm not quite sure what I'm doing wrong. Could you take a look at my repo?

**Comment by bensheldon** [comment]
@jofrly aha! I think you are experiencing Rail's _very aggressive_ ActiveJob test adapter: https://github.com/rails/rails/issues/37270

In your test, if you output `SendNotificationJob.queue_adapter` I think you'll find it's _still_ the Test adapter.

You need to do something like this in your Job setup (I'm not sure what the minitest equivalent is):

https://github.com/bensheldon/good_job/blob/3eb8f185c90566efc63f6f476c4adfe4250de1c0/spec/support/reset_rails_queue_adapter.rb#L2-L7

**Comment by jofrly** [comment]
@bensheldon yes!

logging `SendNotificationJob.queue_adapter` showed that it used the `ActiveJob::QueueAdapters::TestAdapter`.
I added the code you mentioned to the `setup` of my test:

```ruby
class MyTest < ActionDispatch::IntegrationTest
  setup do
    descendants = ActiveJob::Base.descendants + [ActiveJob::Base]
    descendants.each(&:disable_test_adapter)
  end

  ...
```

and now everything works as expected. Thanks so much for helping me. Coffee is on me :)
