### ISSUE TITLE
Add the ability to schedule recurring jobs

### ISSUE THREAD

**Issue by basabin54** [bensheldon/good_job#75]
Delayed Job has a really useful plugin gem for scheduling recurring jobs: https://github.com/amitree/delayed_job_recurring

I think it would be awesome to have something similar added to Good Job!

**Comment by bensheldon** [comment]
@basabin54 thanks for the feature request! There is conversation happening in #53 around this. GoodJob only targets ActiveJob functionality, but there are some alternatives.

**Comment by basabin54** [comment]
@bensheldon  oof, my bad. That's what I get for looking through the issues at 2AM and not spotting the duplicate... 🤦‍♂️

Thanks! I checked out #53 and that all makes sense to me.

Thanks again for all your work on this, I'm loving this project so far. I'll look for a way I can contribute in the future 👍
