### ISSUE TITLE
Dashboard fails to execute JS on latest firefox

### ISSUE THREAD

**Issue by Earlopain** [bensheldon/good_job#792]
> Uncaught TypeError: The specifier “application” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”. [scripts.js:3:7](http://localhost:3000/good_job/assets/scripts.js?v=3.7.3)

![image](https://user-images.githubusercontent.com/14981592/211619867-826640f1-40c6-4576-bfb0-eda82be5bd9f.png)

I believe it has something do to with https://github.com/guybedford/es-module-shims. But I'm not sure what the problem could be. I'm on Firefox 108, which is the latest at the time.

On occasion the js actually gets executed correctly, but 99% of the time it just doesn't work.

**Comment by Earlopain** [comment]
Nice find. Unfortunatly there's no release with that in it yet. I can keep an eye on the release page and pull it in when possible.

**Comment by Earlopain** [comment]
The PR you linked is just a readme update. I looked through the commits in that repo and didn't find anything that looks like it would fix compatibility. https://github.com/guybedford/es-module-shims/compare/1.6.3...main

I noticed that the script gets loaded with the src attribute, while the readme uses the script body.
https://github.com/bensheldon/good_job/blob/d5052861a1bd2846effe970c503f74090c155666/app/views/layouts/good_job/application.html.erb#L21

If I switch it out to this:

```rb
<%= tag.script "", type: "module", nonce: content_security_policy_nonce do %>
  import "application"; // ./modules/good_job/application.js
<% end %>
```

it works in both firefox and chrome. I don't know why it should make a difference, but it does.

**Comment by bensheldon** [comment]
@Earlopain oh yeah! I just discovered that right now too! PR incoming 🚀

**Comment by bensheldon** [comment]
@Earlopain I just released https://github.com/bensheldon/good_job/releases/tag/v3.7.4. Hope that fixes it!

**Comment by Earlopain** [comment]
That seems to have done it. Ty for the quick fix and release ❤️
