### ISSUE TITLE
Nonworking dashboard for job with many retries

### ISSUE THREAD

**Issue by morgoth** [bensheldon/good_job#809]
We have a job:
```ruby
class EveryMinuteJob < ApplicationJob
  after_perform do
    enqueue wait: 1.minute
  end

  def perform
    # do something
  end
end
```

That re-enqueues itself after performing. This is counted as "retry". The retry count can accumulate to a huge number in short time.
With some recent changes on GJ (which I didn't trace yet), such job with many retries kills the dashboard UI, as the retries are stored in database (some time ago they weren't).

Even the main dashboard page with jobs list, where job has only a counter of retries, it is endlessly loading, spiking in huge memory consumption.

We mitigated the problem by changing the job to:
```ruby
class EveryMinuteJob < ApplicationJob
  after_perform do
    EveryMinuteJob.set(wait: 1.minute).perform_later
  end

  def perform
    # do something
  end
end
```
which is not counted as "retry" anymore.

@bensheldon Feel free to close it, as we workaround the problem, just giving you insights on some recent GJ changes.

**Comment by bensheldon** [comment]
Yikes! That is a lot of retries 😬 

This makes me wonder whether ActiveJob has (or should have!) a method for duplicating a job with identical arguments. In your scenario, the job is `enqueued` again with the same ActiveJob `job_id` and GoodJob treats that as a retry. 

FYI, I think this is the change PR (there was a lot of churn on that unfortunately so it's a little hard to trace the conversation): https://github.com/bensheldon/good_job/pull/730

But the Dashboard really shouldn't crash on a ton of retries! I bet it's trying to load all of them into memory and I don't think that should be necessary.
