### ISSUE TITLE
Jobs go back into the queued state when a worker is killed

### ISSUE THREAD

**Issue by TAGraves** [bensheldon/good_job#821]
Today, if a process is running a job and is killed (e.g. by OOM, a kill signal, etc.), the job will go back into the queued state and another worker will pick up the job. This can cause jobs to partially executed multiple times. In the case of something like OOM caused by something going wrong it can be particularly devastating since that job might just keep being run by more workers and causing them to die 😱.

I'm pretty sure this is known and intended behavior, but in case you want a repro:
Create a job like
```
def perform
  `kill -9 #{Process.pid}`
end
```

Enqueue the job via a Rails console and then run `bundle exec good_job start`.

Is it possible within good_job's current architecture to make these jobs get discarded instead of re-enqueued (well, I realize enqueued really just means "no advisory lock")? Resque has [`DirtyExit`](https://www.rubydoc.info/gems/resque/Resque/DirtyExit) which I've found really useful in the past. We try to make our jobs idempotent and also not have them crash the process that's running them, but in the case of someone making a mistake it can be really devastating to have the whole queue become practically inoperational.

**Comment by bensheldon** [comment]
@TAGraves that's interesting! TIL other queue adapters have that setting. I recently added #794 which is semi-related.

You're correct that the current behavior is intended; I am open to adding other modes.

Is this discard-on-interrupt (naming?) behavior something you'd expect to be configured at the global level for all jobs, or would it be more on an individual job/job-class level (as some jobs might be safely idempotent)? If the former, I'd implement it as a GoodJob configuration setting, as the latter I'm imagining it would be an ActiveJob extension. Either way, I'm imagining it could be as simple as checking during dequeue if a job had been interrupted (`performed_at` would already be present) and then cleaning up the record (setting `finished_at` and setting a custom exception):

https://github.com/bensheldon/good_job/blob/430a6a0bc91abfccf5c4621139b5fc3a0b10816f/app/models/good_job/execution.rb#L232-L235

**Comment by TAGraves** [comment]
> Is this discard-on-interrupt (naming?) behavior something you'd expect to be configured at the global level for all jobs or would it be more on an individual job/job-class level (as some jobs might be safely idempotent)?

Hmm, it's a good question. I'm not sure, but I do know we would configure it for all of our jobs. I'd guess you'd want to configure it for all jobs and then add a retry_on: GoodJob::DirtyExit (e.g.) for individual jobs that you know are idempotent.

Glad to hear this should be simple to implement as it's a highly valuable feature for us 😄.
