### ISSUE TITLE
Override locales and conflict with rails-i18n

### ISSUE THREAD

**Issue by julienanne** [bensheldon/good_job#847]
Hello,
(sorry for my English)
First of all thanks for your work, very appreciate it.

In the navbar (app/views/good_job/shared/_navbar.erb) and maybe in other places (with other helpers), you have a call to `number_to_human` helper and in the good_job locales (at least fr.yml) you redefine the "number.human.decimal_units.format".

This locale key is used by the concerning helper and so you redefine the key for the whole project (in my case good_job seems loaded after rails-i18n https://github.com/svenfuchs/rails-i18n/blob/v7.0.6/rails/locale/fr.yml#L178 and override the concerning key).

The impact is not localized to Good Job maybe it can be possible (if you absolutely want to get a specific format), 
- to passed it to the `number_to_human` call instead of redefine the key in good job locale
- or to make a Good Job helper to used other locales specific to Good job
?

Thanks again for your work.
If I have some times, can I make a PR ?

Have a nice day

Julien ANNE

**Comment by bensheldon** [comment]
@julienanne oh no! I'm sorry to have this gem override the translations for your own project.

Let me figure out how to get all of those translations into an appropriate namespace so they don't collide/override with your own projects.

**Comment by bensheldon** [comment]
Thank you for reporting this! Released a fix: https://github.com/bensheldon/good_job/releases/tag/v3.12.2

**Comment by julienanne** [comment]
Thank you, you are moving so fast, very appreciate it ;)
I will perform an update ;)

Hope your project will continue for a long time.

Have a nice day
Julien

**Comment by julienanne** [comment]
Again thank you the correction was perfect ;)
