### ISSUE TITLE
[Not Critical] Too much space (One) in db/migrate/XXXXXX_create_index_good_jobs_jobs_on_priority_created_at_when_unfinished.rb

### ISSUE THREAD

**Issue by julienanne** [bensheldon/good_job#851]
Hi,

Very not critical issue.
When I generate update migration, with `rails generate good_job:update` the file linked after was generated with 3 spaces instead of two on the line 5.
https://github.com/bensheldon/good_job/blob/main/lib/generators/good_job/templates/update/migrations/03_create_index_good_jobs_jobs_on_priority_created_at_when_unfinished.rb.erb#L5

Have a nice day
Julien

**Comment by bensheldon** [comment]
@julienanne thank you for reporting this! Would you be able to make a PR to fix it?

**Comment by julienanne** [comment]
I don't promise but I will try ;)
