### ISSUE TITLE
What is `concurrency_key` used for?

### ISSUE THREAD

**Issue by marcomarcianesi** [bensheldon/good_job#877]
Hello.

It's a little bit unclear what the purpose of  the `concurrency_key` column is and, consequently, how it should be used best (or used at all)

Thanks

**Comment by bensheldon** [comment]
Happy to explain it better! The `concurrency_key` is described in:

https://github.com/bensheldon/good_job/blob/main/README.md#concurrency-controls

Which says:

> A unique key to be globally locked against.

To try to explain in different words: it's your label for a set of your jobs that are treated similarly. In this case, all jobs that share the same `concurrency_key` will share the same concurrency behavior as configured via the `GoodJob::ActiveJobExtensions::Concurrency`.

**Comment by marcomarcianesi** [comment]
Thanks a lot
