### ISSUE TITLE
No route matches [POST] "/scheduler-dashboard/jobs/<id>/retry"

### ISSUE THREAD

**Issue by andreas-it-dev-llc** [bensheldon/good_job#880]
hi, i've got an issue with rescheduling a job via web interface. it just throws a routing error that there would not be a post route to do that. 

if that is important: i use a rails 7.0.4.2 app in api_only mode.

good job bundle info:

```
backend> bundle info good_job
  * good_job (3.12.7)
        Summary: A multithreaded, Postgres-based ActiveJob backend for Ruby on Rails
        Homepage: https://github.com/bensheldon/good_job
        Documentation: https://rdoc.info/github/bensheldon/good_job
        Source Code: https://github.com/bensheldon/good_job
        Changelog: https://github.com/bensheldon/good_job/blob/master/CHANGELOG.md
        Bug Tracker: https://github.com/bensheldon/good_job/issues
        Path: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/good_job-3.12.7
```

routes.rb:

```
Rails.application.routes.draw do
  mount GoodJob::Engine => 'scheduler-dashboard'
  <snip...>
end
```

routing error:

![image](https://user-images.githubusercontent.com/13486613/223011300-50d5cf29-2151-4181-a143-1d89d10192d9.png)

**Comment by bensheldon** [comment]
I think this might be related to being in API-only mode and missing `Rack::MethodOverride` middleware:

https://github.com/bensheldon/good_job#api-only-rails-applications

**Comment by andreas-it-dev-llc** [comment]
hmm, weird, i totally did not see that paragraph in the readme..

anyway, `Rack::MethodOverride` was the missing middleware in my config. adding this did the trick, thanks a lot, Ben
