### ISSUE TITLE
How do I clear queue during tests?

### ISSUE THREAD

**Issue by martinemde** [bensheldon/good_job#887]
I'd like to clear all existing jobs in the test queue before the test run starts. I looked all through the docs and couldn't find anything. Maybe it's something simple?

In particular, the problem I'm having is that there are jobs in the test queue that were enqueued by a different branch. In this branch, the job const doesn't exist so I can't `discard_job`.

Both `GoodJob::Job` and `GoodJob::Execution` have records for these jobs. Should I just use `delete_all` on the ActiveRecord objects?

**Comment by bensheldon** [comment]
Great question! If you're using transactional wrapping, it should _just work_. If you're not...

Yes, you can do `GoodJob::Execution.delete_all` (Execution shares the same table as `GoodJob::Job` so you don't need to specify that). You'll also want to clear `GoodJob::Batch` if you're using it.

Alternatively, you could truncate: `GoodJob::BaseRecord.connection.truncate_tables(GoodJob::Execution.table_name, GoodJob::Batch.table_name).

Just for comprehensiveness of answer, right now there is also `GoodJob::Settings` and `GoodJob::Process` but I think it's less likely they will become polluted during testing.

**Comment by martinemde** [comment]
Thank you for the thorough reply! I set GoodJob::Execution.delete_all to run at the start of the suite to avoid the issue I was seeing.

We did have transactions enabled, but somehow I had polluted the state with jobs that couldn't be loaded due to missing const. Maybe it was a stalled test suite I killed. Clearing those fixed the issue, but before that the transactions were actually preserving the broken jobs.

Thanks for your help!

**Comment by andynu** [comment]
Minor update. GoodJob::Batch is not an active record object. It is a front for GoodJob::BatchRecord.

You can effectively clear the queue with:
```
GoodJob::BaseRecord.connection.truncate_tables(GoodJob::Execution.table_name, GoodJob::BatchRecord.table_name)
````

**Comment by bensheldon** [comment]
@andynu thank you! I'll update my original comment 🙇
