### ISSUE TITLE
good_job is a terrible name for Google searches

### ISSUE THREAD

**Issue by brentgreeff** [bensheldon/good_job#92]
Love the project - but name is a problem

**Comment by bensheldon** [comment]
Thanks for the kind words about the project 🙌  ...name aside.

In an Incognito window, searching `good job rails` brings up the repo, blog posts and reddit shares. Though I dunno how much Incognito means these days 😓 

Is there a name collision that you're seeing?

**Comment by brentgreeff** [comment]
Yea - I had 2 searches in 2 days that returned loads of results about "jobs" - I guess "Rails" is probably a good additive. - Let me keep trying and come back to you :)

**Comment by jimchild49** [comment]
I think what most people are typing is "rails background job with good_job" that's what we do, it turned out that google is thinking somehow that we are looking for a background job/processing that do a good job, personally the term "good job rails" never comes to my mind! others can confirm...

**Comment by tedhexaflow** [comment]
Every time we search ruby gem, we normally add 'gem' at the end.

Type 'good job gem' and this repo list on top. 

I think the name good job is great 😀

**Comment by GregLMcDonald** [comment]
For what it's worth, I found my way to this gem by searching for `rails gem database backed queue`, reading a bit of a thread on YCombinator (https://news.ycombinator.com/item?id=23928891) and then searching for `goodjob gem rails`. I like the name and frankly am surprised it hadn't already been used for a gem!

**Comment by sandstrom** [comment]
I think the name is great, don't change it.
