### ISSUE TITLE
Cleaning up preserved jobs giving me timeout

### ISSUE THREAD

**Issue by murparreira** [bensheldon/good_job#933]
Hey guys, thanks for the wonderful gem.
I am getting a timeout on my postgresql database when i run a task for deleting preserved jobs.
Right now we have more than 500k jobs succeeded.

![image](https://user-images.githubusercontent.com/709760/232914801-28eed576-40c2-4021-9d2a-862452a80e06.png)

This is the code inside the task.

`GoodJob.cleanup_preserved_jobs(older_than: 1.days)`

Can anyone point me in the right direction here?

![image](https://user-images.githubusercontent.com/709760/232914693-94c7d0e0-3e2f-4163-baf0-764ce5a2e688.png)

**Comment by bensheldon** [comment]
@murparreira nuts! Can you tell me what your query timeout is?

I have a PR that I think might help. Would you be willing to try running that? https://github.com/bensheldon/good_job/pull/934

**Comment by murparreira** [comment]
This PR is just what i have implemented here.

![image](https://user-images.githubusercontent.com/709760/232931504-37831445-3c10-4e81-9b4c-ac47f1439797.png)

This code worked, the change on this PR is very useful.

**Comment by murparreira** [comment]
This PR #934, when merged fixes this problem.

**Comment by bensheldon** [comment]
@murparreira thank you for reporting this and the help fixing it! I released the change: https://github.com/bensheldon/good_job/releases/tag/v3.15.2
