### ISSUE TITLE
`active_job.enqueue` Performance Issue

### ISSUE THREAD

**Issue by jtannas** [bensheldon/good_job#939]
First off - thank you for the awesome tool :bow: 
We've just switched over and the visibility & user-friendliness of GoodJob is miles ahead of our previous job adapter.

---

That being said, I'm looking pretty closely at the performance during the switch and am seeing a lot more database time from enqueing a job than I'd hoped. Here's the trace information from an instance of `active_job.enqueue` from our monitoring service.

![image](https://user-images.githubusercontent.com/22785056/234705776-ab28ec40-c207-406f-bb69-09fb0a9eb005.png)

![image](https://user-images.githubusercontent.com/22785056/234705917-34a23709-5be6-425f-914e-7d2a0d88c2ba.png)

Is there any way to reduce the amount of overhead from enqueing a job?

I'm not familiar with the internals of GoodJob, but in the past I've been able to avoid the `BEGIN/COMMIT` overhead from ActiveRecord `create` in performance sensitive cases by using [insert](https://api.rubyonrails.org/classes/ActiveRecord/Persistence/ClassMethods.html#method-i-insert) so I wonder if that's applicable here.

**Comment by bensheldon** [comment]
Hi! Thanks for asking. Those `BEGIN`/`COMMIT` take some unexpected time 🥵 

You could do a straight `insert` right now, because there isn't any other callbacks being done on GoodJob. But I will say that it could always change in the future and I would consider it "possible but unsupported".

Rails 7.1 will ship with bulk enqueueing ([`perform_all_later`](https://github.com/rails/rails/pull/46603)) which GoodJob already implements as `GoodJob::Adapter#enqueue_all` which does an [`insert_all`](https://github.com/bensheldon/good_job/blob/095f10f5902a67da832bd2922ce2a23d3a541762/lib/good_job/adapter.rb#L66). You could try using that directly, e.g.

```ruby
job = MyJob.new(*args)
MyJob.queue_adapter.enqueue_all(job) 
```

**Comment by jtannas** [comment]
Thank you for the fast reply & the ideas :slightly_smiling_face: 
I'll take that `perform_all_later` trick and wrap it into `fast_perform_later` method on our ApplicationJob to test the effects.

> You could do a straight insert right now, because there isn't any other callbacks being done on GoodJob. But I will say that it could always change in the future and I would consider it "possible but unsupported".

Regarding this point - since there aren't any callbacks being done would you consider making switching to `insert` for now? If you need callbacks later then you can always change it back to `create` later.

**Comment by bensheldon** [comment]
> since there aren't any callbacks being done would you consider switching to insert for now?

I thought about that. I think I'm reluctant to micro-optimize Active Record. Also, while GoodJob doesn't have any callbacks, I've been historically upfront that "it's an Active Record model" so it feels like a breaking change to go through a different save path if other folks have extended the model with their own callbacks.

**Comment by jtannas** [comment]
I'm running into a hiccup with the `enqueue_all` trick though - PG is rejecting it due to 

> I thought about that. I think I'm reluctant to micro-optimize Active Record. Also, while GoodJob doesn't have any callbacks, I've been historically upfront that "it's an Active Record model" so it feels like a breaking change to go through a different save path if other folks have extended the model with their own callbacks.

Makes sense - we've got a weird use case due to some legacy code that causes us to have to deal with micro-optimizations but that shouldn't be imposing on the interface for the larger userbase.

> I'll take that perform_all_later trick and wrap it into fast_perform_later method on our ApplicationJob to test the effects.

In case anyone else stumbles across this thread - here's what I ended up implementing so that it'd be compatible with `async` and `inline` adapters in dev & test mode.

```rb
  def self.fast_perform_later(...)
    if queue_adapter.respond_to?(:enqueue_all)
      queue_adapter.enqueue_all([new(...)])
    else
      perform_later(...)
    end
  end
  ```
