### ISSUE TITLE
Issue with performing jobs that use ActionMailer::Parameterized

### ISSUE THREAD

**Issue by RailsCod3rFuture** [bensheldon/good_job#944]
I am receiving an error for a missing method on ActionMailer object.

`[ActiveJob] [Noticed::DeliveryMethods::Email] [53d92cb5-747e-4939-b4e1-1ef03594711c] Error performing Noticed::DeliveryMethods::Email (Job ID: 53d92cb5-747e-4939-b4e1-1ef03594711c) from GoodJob(default) in 92.31ms: NoMethodError (undefined method `report_notification' for #<ActionMailer::Parameterized::Mailer:0x000000011b536d28 @mailer=ReportNotificationMailer, @params={:report=>#<Report id: 2...`

How do you get GoodJob to work with parameterized mailers?

**Comment by bensheldon** [comment]
GoodJob should work out of the box with ActionMailer.

From the error you shared, it looks like you're calling something like this:

```ruby
ReportNotificationMailer.with(report: my_report).report_notification.deliver_later
```

Does that match up with what you expect? I imagine that there is some problem with the `report_notification` method (that "method missing" error). Is that the correct name of the Mailer action? Also, are you running this locally in development/async, or are you seeing this when running the `good_job` cli? If it's the `good_job` cli I think you need to restart it you just created the method.

**Comment by RailsCod3rFuture** [comment]
I believe its an issue with the gem noticed. I opted to call the mailer exactly how you have it written above in the same action that does the noticed background job. Its working as expected now. Thank you! -- I would have forgotten to update this thread if you hadn't responded - I appreciate the promptness!

**Comment by bensheldon** [comment]
@RailsCod3rFuture yay! happy to help 🤗
