### ISSUE TITLE
Support for customized job display name

### ISSUE THREAD

**Issue by paul** [bensheldon/good_job#956]
In our app, we make extensive use of the Command pattern, and have a meta-job that allows us to enqueue any Command as a job:

```ruby
class CommandJob
  def perform(command_class_name:, args: [])
    command_class_name.constantize.new.call(*args)
  end
end
```

This means that in our GoodJob dashboard, we just have a bunch of "CommandJob", without any details. The dashboard gets the "job name" from the `GoodJob::BaseExecution#job_class` model method. 

I can monkey-patch GoodJob::BaseExecution to provide a better name:

```ruby
  def job_class
    name = super
    if name == "CommandJob"
      cmd_name = serialized_params.dig("arguments", 0, "command_class_name")
      name += "[#{cmd_name}]"
    end
    name
  end
```

This renders as something like "CommandJob[ImportUsers]" in the dashboard, which is much more useful. However, I'm concerned that replacing "job_class" that doesn't return exactly the job class name would break the operation of GoodJob, if not now then possibly with a future update.

Would you be open to a PR that allows the name of the job on the dashboard to be customized? I can think of a few approaches:

1. Add `BaseExecution#job_display_name`, which can be monkey-patched
2. Add `GoodJob::ApplicationHelper#job_display_name(job)`, which can be monkey-patched
3. Add an optional method to the jobs themselves, like `MyJob.good_job_display_name(job)`, so no monkey-patching is required.

Let me know which of these would be preferred, and I'll open up a PR.

**Comment by bensheldon** [comment]
@paul I think my preference is for option `1. BaseExecution#job_display_name`. I feel sorta bad about encouraging monkey patching, but that also seems simplest and I don't like that (3) would require deserializing the ActiveJob.

**Comment by paul** [comment]
Hi @bensheldon. I'm finally finding some time to tackle this, but I'm struggling getting my monkeypatch loading late enough. In my app, I've tried several ways to load this, eg:

```ruby
Rails.application.configure do
  ActiveSupport.on_load(:good_job) do
    GoodJob::BaseExecution.prepend(GoodJobDisplayName)
  end
end
```

but I always end up with a `uninitialized constant GoodJob::BaseExecution (NameError)`. 

Do you have any suggestions on how I can trigger the monkeypatch to load late enough? I saw recently in #1004 you added a `:good_job_base_record` hook, (which also isn't late enough, fwiw). Do you think I also need to add a similar `:good_job_base_execution_record` hook?

**Comment by paul** [comment]
Actually, nevermind. I dug into all the available keys (since they're not really documented), and it looks like `  ActiveSupport.on_load(:after_initialize)` happens late enough in the Rails boot process that GoodJob has finally loaded all its models.
