### ISSUE TITLE
BaseExecution::discrete_support?  hardcodes the DiscreteExecution table_name

### ISSUE THREAD

**Issue by gap777** [bensheldon/good_job#957]
It seems like the BaseExecution::discrete_support? is giving us a false answer, b/c we're using custom table names and this has the table_name for DiscreteExecution hardcoded.

Instead of base_execution.rb, L37 being:

```
     def discrete_support?
        if connection.table_exists?('good_job_executions')
          true
        else
          migration_pending_warning!
          false
        end
      end
```

I believe it should be 

```
     def discrete_support?
        if connection.table_exists?(DiscreteExecution.table_name)
          true
        else
          migration_pending_warning!
          false
        end
      end
```

If you agree, I can open a PR.

Thanks, and keep up the great work!

**Comment by bensheldon** [comment]
Nice catch! Yes, please open a PR.

**Comment by gap777** [comment]
https://github.com/bensheldon/good_job/pull/958 is open

**Comment by bensheldon** [comment]
@gap777 thank you! Released in https://github.com/bensheldon/good_job/releases/tag/v3.15.8
