### ISSUE TITLE
uninitialized constant DiscreteExecution

### ISSUE THREAD

**Issue by adzap** [bensheldon/good_job#962]
Originating from method `discrete_support?` (app/models/good_job/base_execution.rb:38)` in v3.15.9

**Comment by bensheldon** [comment]
@adzap thanks for reporting this. I'm not sure why the constant lookup isn't working here, but I'll namespace it in `GoodJob::` just to be sure:

https://github.com/bensheldon/good_job/blob/1c4fc07814de0ff02f1602d19ed6e517848c78b8/app/models/good_job/base_execution.rb#L38-L38

**Comment by bensheldon** [comment]
I just released: https://github.com/bensheldon/good_job/releases/tag/v3.15.10

**Comment by adzap** [comment]
Excellent, thanks.

I was going to say it might have something to do with zeitwerk but I see you removed it. I did have other const loading issues when I was first using the gem which I resolved myself with an explicit require.

**Comment by adzap** [comment]
Has there been a regression?

Here is the fix https://github.com/bensheldon/good_job/pull/963/files? 

But here is the latest code https://github.com/bensheldon/good_job/blob/1ce9aef52cf2c126fd7115888a1353215a691d26/app/models/good_job/base_execution.rb#L38

**Comment by bensheldon** [comment]
>  I did have other const loading issues when I was first using the gem which I resolved myself with an explicit require.

Re-reading through this, I imagine something is wrong in your application because it shouldn't be necessary to do any explicit requires with Rails and Rails's Zeitwerk loader.

Can you try running `bin/rails zeitwerk:check`?

**Comment by adzap** [comment]
Thanks!

**Comment by adzap** [comment]
I don’t use the zeitwerk loader.
