### ISSUE TITLE
Dashboard as separate package?

### ISSUE THREAD

**Issue by leemeichin** [bensheldon/good_job#965]
Would there be any value in offering the `good_job` dashboard as a separate package so it could be deployed independently? For example, I don't want to mount the dashboard on the same service as my API, on the same public domain, I'd rather put it behind a VPN on its own thing.

Could I just make a fake Rails app, mount the `good_job` engine into it at the root, and build a docker image on that? or does it need to know the application you are enqueuing the jobs from?

**Comment by bensheldon** [comment]
> does it need to know the application you are enqueuing the jobs from?

Yes, the Dashboard does need to know the application, including:

- Same Rails framework version
- Same GoodJob configuration and version
- Database connection
- The application's Active Job classes

That's not everything, but I don't think it's safe to attempt and the list could expand in the future. I don't imagine it being possible to decouple that.

To try to solve your problem better, what service are you hosting on? You can do something simple like this in its own container, but on the same service and route to it with different auth:

```ruby
# config/routes.rb

if ENV['ADMIN_MODE']
  mount GoodJob::Engine => 'good_job'
  return # pretty sure early return works here rather than nesting a full if/else
end

# ...the rest of your routes
```

**Comment by leemeichin** [comment]
Thanks for the response :) that does seem less simple than I hoped.

We're on k8s but the issue I ran into was that mounting the engine and setting up an auth middleware somehow interfered with authentication in the main app:

```ruby
NoMethodError

undefined method `public_id' for nil:NilClass (NoMethodError)

          session_data["session_id"] = sid.public_id
```

Using this code:

```ruby
if Rails.env.production?
  GoodJob::Engine.middleware.use(Rack::Auth::Basic) do |username, password|
    next unless username.ends_with?('@our.company.email.address')

    user = User.find_by(email: username)
    user&.authenticate(password)
  end
end
```

It seems like adding the CookieStore middleware was responsible so it sounds like we'd need to do something like you'd suggested or otherwise just live with exposing it on the public internet and hiding it behind our SSO or something.

**Comment by bensheldon** [comment]
I created #1041 as a solution to hopefully make this easier/beter.

**Comment by mroach** [comment]
I can share our solution to this which may be handy to others.

We're using Google Cloud and they have an [Identity-Aware Proxy](https://cloud.google.com/iap) which is a managed proxy server that requires user to authenticate before accessing the protected resources. Per backend service, you configure which users are allowed to access them. 

Since we don't want the app trusting that it's protected in release environments, we use Rails route constraints to enforce it in the app without having to modify GoodJob's middleware (and we use it to protected other internal-only resources). With this setup, users would get a 404 if the IAP were somehow disabled. 

```ruby
scope :internal do
  constraints(lambda do |req|
    next true unless EnvConfig.secure_internal_routes?

    Security::Middleware::GoogleIapAuth.authenticated?(req)
  end) do
    mount GoodJob::Engine, at: "/jobs"
    mount Admin::Engine, at: "/admin"
  end
end
```
