### ISSUE TITLE
Dark mode for the dashboard ?

### ISSUE THREAD

**Issue by wJoenn** [bensheldon/good_job#974]
It'd be nice to have a dark theme too.
Just a dark theme would do as far as I'm concerned 😅

I wouldn't mind looking into a solution if you're not interested in working on that yourself

**Comment by wJoenn** [comment]
Hey Ben, thanks for being open to the idea 🙌 
I haven't touched Bootstrap for quite some times now and I'm not really in a mood to get into that right now.
As soon I have some time for this I'll have a look at whether this issue is still open or not and I'll let you know !
Cheers

**Comment by bensheldon** [comment]
No sweat! I appreciate you opening the issue; maybe I'll get to it first 😊
