### ISSUE TITLE
Persisting ActiveSupport::CurrentAttributes 

### ISSUE THREAD

**Issue by davidalejandroaguilar** [bensheldon/good_job#981]
Is there a way to persist [`Current` attributes](https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html), similar to [how Sidekiq does it](https://github.com/sidekiq/sidekiq/blob/main/lib/sidekiq/middleware/current_attributes.rb)? Here's [Mike explaining this](https://www.mikeperham.com/2022/07/29/sidekiq-and-request-specific-context/) in more detail.

**Comment by davidalejandroaguilar** [comment]
Didn't notice there was a Discussions tab, my bad, closing and opening there.

**Comment by bensheldon** [comment]
No worries! I remembered that I had discussed this generally: https://github.com/bensheldon/good_job/discussions/901#discussioncomment-5394194
