### ISSUE TITLE
Dashboard error when trying to display 0 running/queued/retried jobs due to missing 'zero' translation

### ISSUE THREAD

**Issue by Roko131** [bensheldon/good_job#990]
Hi, getting: `translation data {:one=>"Apply to all 1 job.", :other=>"Apply to all %{count} jobs."} can not be used with :count => 0. key 'zero' is missing.`

When clicking : for example clicking **0 queued jobs**
![image](https://github.com/bensheldon/good_job/assets/3532929/444ca255-ca26-4941-9ae5-20aee60ec06f)

Because no `zero` value at **apply to all (at any of the languages):**
https://github.com/bensheldon/good_job/blob/7971c8febdca9ee76555ec756e1257c34da4cd9a/config/locales/en.yml#L130-L134
So need to either add `zero` in all translations languages or adjust line 54 : `t ".actions.apply_to_all", count: filter.filtered_count` and somehow avoid `count` being _zero_

https://github.com/bensheldon/good_job/blob/7971c8febdca9ee76555ec756e1257c34da4cd9a/app/views/good_job/jobs/_table.erb#L48-L57

**Comment by bensheldon** [comment]
Thanks for opening this issue! I'll add a `zero` onto those keys.

**Comment by bensheldon** [comment]
hmmm, I'm having trouble reproducing this. Those helpers don't require a `zero` for me, so I'm a little confused about why your setup would 🤔

**Comment by bensheldon** [comment]
Doing a little research, it seems like the i18n gem asserts `pluralize` "...will pick the :zero subkey in the special case where count is equal to 0 and there is a :zero subkey present."

https://github.com/ruby-i18n/i18n/blob/7cf09474b77fd41e65d979134b0525f67cf371b0/lib/i18n/backend/base.rb#L168-L170

Which matches up with the code:

https://github.com/ruby-i18n/i18n/blob/7cf09474b77fd41e65d979134b0525f67cf371b0/lib/i18n/backend/pluralization.rb#L48

😕 So I'm not sure why your application is specifically expecting a `zero` key. Are there other I18n-related gems that you're using or something that has been patched into your application?

**Comment by Roko131** [comment]
You are correct, it is specifically related to my application- my bad.

This is the culprit:
`config/locales/plurals.rb`:

```ruby
{:en =>
  { :i18n =>
    { :plural =>
      { :keys => [:zero, :one, :other],
        :rule => lambda { |n|
          if n == 1
            :one
          elsif n == 0
            :zero
          else
            :other
          end
        }
      }
    }
  }
}
```
