### ISSUE TITLE
Explicitly write that jobs with higher priority jobs run first (unlike Que or DelayedJob) at readme.

### ISSUE THREAD

**Issue by Roko131** [bensheldon/good_job#991]
Hi,

I am switching from [DelayedJob](https://github.com/collectiveidea/delayed_job).
To my surprise, totally by chance, I found out that unlike [DelayedJob's execution order](https://github.com/collectiveidea/delayed_job#parameters) which is:
`:priority (number): lower numbers run first`
![image](https://github.com/bensheldon/good_job/assets/3532929/d90cbdfd-d2b4-475e-8ad3-b53edbb66bb4)

[Que Gem](https://github.com/que-rb/que#usage) also uses `lower priority runs first`
```ruby
  # taken from Que doc
  # We use the Linux priority scale - a lower number is more important.
```

At `GoodJob` it's the other way around, meaning higher numbers run first (at least according to my tests).

The only place which hints about it is https://github.com/bensheldon/good_job#queue-performance-with-queue-select-limit
![image](https://github.com/bensheldon/good_job/assets/3532929/1d235630-0d99-4ca7-ad77-4d84c1e60b76)

I think it would be a good idea to add somewhere in `readme`- (I gave it a look, not sure exactly where),
so it would be obvious without a doubt, explicitly written.

`good_job (3.15.13)`

**Comment by bensheldon** [comment]
Sorry about that confusion. That should be added to the readme. Would you be able to make the PR to add it? I think you'd be good at identifying where you'd see it.

Something along the lines of:

<blockquote markdown=1>

`priority:`: higher numbers run first. This is changing: the next major version of GoodJob (v4.0) will change job `priority` to give smaller numbers higher priority (default: `0`), in accordance with Active Job's definition of priority. To opt-in to this behavior now, set `config.good_job.smaller_number_is_higher_priority = true` in your GoodJob initializer or application.rb.

</blockquote>

FYI, there should be a deprecation warning from #883.
